"""Class progression skill and spell catalogs."""

from __future__ import annotations

from .base import (
    CallContract,
)

from .skills import (
    BattleCry,
    Charge,
    DoubleStrike,
    Doublecast,
    DrunkenBrawler,
    FavoredEnemy,
    FinalAssault,
    FlurryBlades,
    Hadouken,
    Headbutt,
    Hyakuretsukyaku,
    Jump,
    LastStand,
    MonkeyGrip,
    MonkeyGrip2,
    MortalStrike,
    MortalStrike2,
    PiercingStrike,
    PolearmExcellence,
    PolearmProficiency,
    ShieldBlock,
    ShieldSlam,
    SongRenewal,
    SongShelter,
    SongValor,
    SpinningBackElbow,
    StealAsWell,
    StealSpell,
    StealSpell2,
    Suplex,
    TripleStrike,
    Triplecast,
    TruePiercingStrike,
    TrueStrike,
    Uppercut,
)

from .promotions import (
    BraceWall,
    Bulwark,
    CenteredGuard,
    CheatDeath,
    CitadelAegis,
    ConduitCommand,
    ConsecratedConduit,
    CoveringGuard,
    DeathMark,
    DeflectSpell,
    Eclipse,
    FindersKeepers,
    FourfoldSurge,
    GreatBenediction,
    GuardPartner,
    HarryPrey,
    HoldTheLine,
    InvokeAgloolik,
    InvokeBardi,
    InvokeCacus,
    InvokeDilong,
    InvokeFuath,
    InvokeGrigori,
    InvokeHala,
    InvokeIzulu,
    InvokeKobalos,
    InvokePatagon,
    InvokeZahhak,
    IronwallReprisal,
    LastBastionSurge,
    MartialMastery,
    MendWounds,
    MirrorBreath,
    PackStrike,
    PurgingKata,
    RelicAegis,
    SanctuaryWard,
    ScavengersEye,
    ShieldBash,
    ShieldRiposte,
    Supplication,
    ThreadedCast,
    TotemSurge,
    Wayfinding,
    WingedPounce,
)

from .utility import (
    AbsorbEssence,
    Backstab,
    Cartography,
    ChiHeal,
    Cover,
    DefensiveRegen,
    Disarm,
    DispelSlash,
    ElementalStrike,
    EnhanceArmor,
    EnhanceBlade,
    Evasion,
    EvasiveGuard,
    ExploitWeakness,
    Familiar,
    Familiar2,
    Familiar3,
    Goad,
    GoldToss,
    HealSummon,
    HealthDrain,
    HealthManaDrain,
    ImbueWeapon,
    Inspect,
    KeenEye,
    KidneyPunch,
    LearnSpell,
    LearnSpell2,
    LegSweep,
    LifeTap,
    Lockpick,
    MaelstromWeapon,
    ManaDrain,
    ManaShield,
    ManaShield2,
    ManaSlice,
    ManaSlice2,
    ManaTap,
    MasterLockpick,
    Mug,
    Parry,
    PiousBounty,
    PocketSand,
    PoisonStrike,
    Posturing,
    PurityBody,
    PurityBody2,
    Quickstep,
    RaiseSummon,
    Retaliate,
    Reveal,
    SleepingPowder,
    SlotMachine,
    SmokeScreen,
    SneakAttack,
    StaffConduit,
    Steal,
    Summon,
    Summon2,
    Tame,
    ThirdEye,
    Totem,
    Transform,
    Transform2,
    Transform3,
    Zephyrstrike,
)

from .powerups import (
    DimMak,
    FrozenArmor,
)

from .spell_types import (
    Corruption2,
    EnterWall,
    Foretell,
    Invisibility,
    Nightmare,
    PlantSeeds,
    ResistEarth,
    ResistElectric,
    ResistFire,
    ResistIce,
    ResistWater,
    ResistWind,
    Rewind,
    TwistFate,
    VilePotion,
    Volitation,
    Wormhole,
)

from .spells import (
    AstralShift,
    BallLightning,
    Berserk,
    Bless,
    Bolt,
    Boost,
    CalmingBreeze,
    Cleanse,
    Corruption,
    Desoul,
    Dispel,
    DivineProtection,
    Doom,
    Enfeeble,
    Firebolt,
    Gust,
    Haste,
    Heal,
    Heal2,
    Heal3,
    Hex,
    Holy,
    Holy2,
    Holy3,
    Hydration,
    IceBlock,
    IceLance,
    MagicMissile,
    MirrorImage,
    MirrorImage2,
    NatureShield,
    PoisonDart,
    Reflect,
    Regen,
    Regen2,
    Regen3,
    Regrowth,
    ResistAll,
    Resurrection,
    Sanctuary,
    Scorch,
    ShadowBolt,
    ShadowBolt2,
    ShadowBolt3,
    Shell,
    Shock,
    Silence,
    Sleep,
    Smite,
    Smite2,
    Smite3,
    SoulDrain,
    StoneSkin,
    Teleport,
    Terrify,
    Tremor,
    TurnUndead,
    TurnUndead2,
    Vulcanize,
    WaterJet,
    WeakenMind,
    WindSpeed,
    Windswept,
)


def ability_classes_for(entry):
    """Normalize one or more ability classes stored for a single level."""
    if entry is None:
        return []
    if isinstance(entry, (list, tuple)):
        return list(entry)
    return [entry]


def ability_classes_for_level(source: dict, class_name: str, level: int | str):
    return ability_classes_for(source.get(class_name, {}).get(str(level)))


# Parameters
skill_dict = {
    "Warrior": {
        "3": ShieldSlam,
        "8": PiercingStrike,
        "10": Disarm,
        "15": Charge,
        "23": Parry,
        "25": TrueStrike,
        "28": BattleCry,
    },
    "Weapon Master": {
        "1": MortalStrike,
        "6": DoubleStrike,
        "21": TruePiercingStrike,
        },
    "Berserker": {
        "3": FinalAssault,
        "5": MortalStrike2,
        "10": MonkeyGrip,
        "20": MonkeyGrip2,
        "30": TripleStrike,
        },
    "Paladin": {
        "6": ShieldBlock,
        "13": Goad,
        "18": DoubleStrike,
        },
    "Crusader": {
        "1": Posturing,
        "5": MortalStrike,
        "22": TripleStrike,
        "30": TruePiercingStrike,
        },
    "Lancer": {
        "1": [Jump,
              PolearmProficiency],
        "12": Zephyrstrike,
        },
    "Dragoon": {
        "1": PolearmExcellence,
        "5": TruePiercingStrike,
        "10": ShieldBlock,
        },
    "Sentinel": {
        "1": ShieldBlock,
        "3": Goad,
        "5": HoldTheLine,
        "6": ShieldBash,
        "7": BraceWall,
        "9": Retaliate,
        "10": ShieldRiposte,
        "12": CoveringGuard,
        "14": DeflectSpell,
        "16": Bulwark,
        },
    "Stalwart Defender": {
        "1": [CitadelAegis,
              IronwallReprisal,
              LastBastionSurge],
        "18": LastStand,
        },
    "Mage": {
        "25": ManaShield,
        },
    "Sorcerer": {
        "1": FrozenArmor,
        "10": Doublecast,
        "18": MirrorImage,
        },
    "Wizard": {
        "5": ManaShield2,
        "15": Triplecast,
        "30": MirrorImage2,
        },
    "Warlock": {
        "1": Familiar,
        "5": HealthDrain,
        "9": LifeTap,
        "15": ManaDrain,
        "20": Familiar2,
    },
    "Shadowcaster": {
        "4": ManaTap,
        "6": Eclipse,
        "10": HealthManaDrain,
        "20": Familiar3,
        },
    "Demonologist": {
        "1": CallContract,
        },
    "Spellblade": {
        "1": EnhanceBlade,
        "6": ManaSlice,
        "10": ImbueWeapon,
        "15": Parry,
        "21": ElementalStrike,
        "28": TrueStrike,
    },
    "Knight Enchanter": {
        "1": EnhanceArmor,
        "6": ManaTap,
        "10": DoubleStrike,
        "14": ManaSlice2,
        "20": DispelSlash,
        "30": TruePiercingStrike,
    },
    "Summoner": {
        "1": Summon,
        "12": HealSummon,
    },
    "Grand Summoner": {
        "1": Summon2,
        "2": ConduitCommand,
        "3": [InvokePatagon,
              InvokeDilong,
              InvokeAgloolik,
              InvokeCacus,
              InvokeFuath,
              InvokeIzulu,
              InvokeHala,
              InvokeGrigori,
              InvokeBardi,
              InvokeKobalos,
              InvokeZahhak],
        "8": RaiseSummon,
    },
    "Footpad": {
        "2": Quickstep,
        "3": Disarm,
        "5": SmokeScreen,
        "6": PocketSand,
        "8": KidneyPunch,
        "10": Steal,
        "12": Backstab,
        "16": DoubleStrike,
        "19": SleepingPowder,
        "22": EvasiveGuard,
        "25": Parry,
    },
    "Thief": {
        "1": ScavengersEye,
        "5": Lockpick,
        "12": GoldToss,
        "15": Mug,
        "20": PoisonStrike,
    },
    "Rogue": {
        "1": FindersKeepers,
        "3": Zephyrstrike,
        "4": CheatDeath,
        "5": SneakAttack,
        "8": KeenEye,
        "10": SlotMachine,
        "12": TripleStrike,
        "15": MasterLockpick,
    },
    "Inquisitor": {
        "1": Reveal,
        "2": PiercingStrike,
        "5": Inspect,
        "10": ExploitWeakness,
        "14": KeenEye,
        "15": ShieldBlock,
        "22": TrueStrike,
    },
    "Seeker": {
        "1": Cartography,
        "3": Wayfinding,
        "5": ThirdEye,
        "16": TripleStrike,
        "25": TruePiercingStrike,
        },
    "Assassin": {
        "1": DeathMark,
        "8": PoisonStrike,
        "15": Lockpick,
        "18": TripleStrike,
        },
    "Ninja": {
        "8": Mug,
        "25": FlurryBlades,
        },
    "Spell Stealer": {
        "1": StealSpell,
        "12": StealAsWell,
        "18": ImbueWeapon,
        },
    "Arcane Trickster": {
        "1": StealSpell2,
        "4": ThirdEye,
    },
    "Healer": {},
    "Cleric": {
        "1": SanctuaryWard,
        "6": ShieldSlam,
        "12": ShieldBlock,
        "24": PiousBounty,
        "27": TrueStrike,
        },
    "Templar": {
        "1": Parry,
        "4": PiercingStrike,
        "6": Goad,
        "8": RelicAegis,
        "14": Charge,
        "22": DoubleStrike,
        "30": TruePiercingStrike,
    },
    "Hierophant": {
        "1": StaffConduit,
        "8": ConsecratedConduit,
    },
    "Priest": {
        "1": Supplication,
        "4": DefensiveRegen,
        "10": ManaShield,
        },
    "Archbishop": {
        "5": Doublecast,
        "8": GreatBenediction,
        "15": ManaShield2,
        },
    "Monk": {
        "1": ChiHeal,
        "3": DoubleStrike,
        "5": LegSweep,
        "7": TrueStrike,
        "10": PurityBody,
        "11": CenteredGuard,
        "12": Uppercut,
        "14": MirrorBreath,
        "16": Headbutt,
        "18": PurgingKata,
        "20": DrunkenBrawler,
        "25": Parry,
    },
    "Master Monk": {
        "1": Evasion,
        "5": Hyakuretsukyaku,
        "10": TripleStrike,
        "12": SpinningBackElbow,
        "15": PurityBody2,
        "18": MartialMastery,
        "20": Suplex,
        "25": Hadouken,
        "30": DimMak,
        },
    "Bard": {
        "1": SongValor,
        "2": SongShelter,
        "3": SongRenewal,
        },
    "Troubadour": {},
    "Pathfinder": {},
    "Druid": {
        "1": Transform,
        "15": Transform2,
        "17": MortalStrike,
        },
    "Archdruid": {
        "10": FourfoldSurge,
    },
    "Lycan": {
        "1": Transform3,
        "11": Charge,
        "15": BattleCry,
        "18": WingedPounce,
        "25": MortalStrike2,
        },
    "Diviner": {
        "1": LearnSpell,
        "18": Doublecast,
        },
    "Astromancer": {
        "1": LearnSpell2,
        "12": ThreadedCast,
        "25": Triplecast,
        },
    "Shaman": {
        "1": Totem,
        "3": TotemSurge,
        "4": ElementalStrike,
        "6": PiercingStrike,
        "10": MaelstromWeapon,
        "19": TrueStrike,
        "24": DoubleStrike,
    },
    "Soulcatcher": {
        "1": AbsorbEssence,
        "2": Parry,
        "3": TotemSurge,
        "9": TripleStrike,
        "29": TruePiercingStrike,
    },
    "Ranger": {
        "1": [Tame, FavoredEnemy],
    },
    "Beast Master": {
        "5": Cover,
        "7": Zephyrstrike,
        "9": PackStrike,
        "10": GuardPartner,
        "11": HarryPrey,
        "12": MendWounds,
    },
}

spell_dict = {
    "Warrior": {},
    "Weapon Master": {},
    "Berserker": {},
    "Paladin": {
        "1": Heal,
        "4": Smite,
        "24": DivineProtection,
        },
    "Crusader": {
        "3": Smite2,
        "8": Heal2,
        "16": Cleanse,
        "18": Smite3,
        "20": Dispel,
        },
    "Lancer": {},
    "Dragoon": {},
    "Sentinel": {},
    "Stalwart Defender": {},
    "Mage": {
        "1": Firebolt,
        "4": Tremor,
        "5": MagicMissile,
        "8": IceLance,
        "13": Shock,
        "15": WaterJet,
        "16": Enfeeble,
        "19": Gust,
    },
    "Sorcerer": {
        "6": Reflect,
        "10": Sleep,
        "16": Dispel,
        "20": WeakenMind,
        "30": IceBlock,
    },
    "Wizard": {
        "7": Boost,
        "16": Volitation,
        "20": Teleport,
    },
    "Warlock": {
        "1": ShadowBolt,
        "4": Corruption,
        "10": Terrify,
        "12": ShadowBolt2,
        "15": Doom,
        "19": Dispel,
    },
    "Shadowcaster": {
        "8": ShadowBolt3,
        "12": Invisibility,
        "16": Nightmare,
        "18": Desoul,
        },
    "Demonologist": {
        "8": Corruption2,
        },
    "Spellblade": {
        "20": Reflect,
        },
    "Knight Enchanter": {},
    "Summoner": {},
    "Grand Summoner": {},
    "Footpad": {},
    "Thief": {},
    "Rogue": {},
    "Inquisitor": {
        "3": Dispel,
        "8": Silence,
        "12": Enfeeble,
        "15": Reflect,
        "18": ResistFire,
        "19": ResistIce,
        "20": ResistElectric,
        "21": ResistWater,
        "22": ResistEarth,
        "23": ResistWind,
        },
    "Seeker": {
        "1": Teleport,
        "4": ResistAll,
        "10": Sanctuary,
        "12": Volitation,
        "14": EnterWall,
        "16": WeakenMind,
        },
    "Assassin": {
        "10": Invisibility,
        },
    "Ninja": {
        "12": Haste,
        "20": Desoul,
        },
    "Spell Stealer": {
        "8": WindSpeed,
        "27": Silence,
        },
    "Arcane Trickster": {
        "4": WeakenMind,
        },
    "Healer": {
        "1": Heal,
        "3": Holy,
        "8": Regen,
        "10": TurnUndead,
        "26": Heal2,
        },
    "Cleric": {
        "1": Smite,
        "5": Bless,
        "14": Cleanse,
        "15": Silence,
        "16": Smite2,
        "19": TurnUndead2,
    },
    "Templar": {
        "6": Regen2,
        "10": Smite3,
        "18": Dispel,
        },
    "Hierophant": {
        "4": Holy2,
        "12": Regen2,
        "18": Dispel,
        },
    "Priest": {
        "1": Regen2,
        "3": Holy2,
        "6": Shell,
        "11": Cleanse,
        "15": Bless,
        "17": Dispel,
        "21": Berserk,
    },
    "Archbishop": {
        "1": Heal3,
        "4": Holy3,
        "6": Silence,
        "7": Regen3,
        "20": Resurrection,
    },
    "Monk": {
        "15": Shell,
        },
    "Master Monk": {
        "2": Reflect,
        "12": Dispel,
        },
    "Bard": {},
    "Troubadour": {},
    "Pathfinder": {
        "1": Tremor,
        "7": WaterJet,
        "14": Gust,
        "19": Scorch,
        },
    "Druid": {
        "1": PoisonDart,
        "5": StoneSkin,
        "9": Regrowth,
        "17": CalmingBreeze,
        },
    "Archdruid": {
        "1": PlantSeeds,
        "4": Bolt,
        "6": VilePotion,
        "8": Windswept,
        "12": NatureShield,
        "16": BallLightning,
        },
    "Lycan": {
        "8": Dispel,
        },
    "Diviner": {
        "3": Enfeeble,
        "8": Haste,
        "14": Dispel,
        "23": Berserk,
        },
    "Astromancer": {
        "1": Vulcanize,
        "6": Foretell,
        "10": WeakenMind,
        "15": Boost,
        "18": TwistFate,
        "22": Wormhole,
        "28": Rewind,
        },
    "Shaman": {
        "2": Hex,
        "9": Hydration,
        "16": AstralShift,
        },
    "Soulcatcher": {
        "4": SoulDrain,
        "6": Dispel,
        "12": Desoul,
        },
    "Ranger": {},
    "Beast Master": {},
}
