"""Footpad-line ability-tree declarations."""

from __future__ import annotations

THIEF_TREE_NODE_SPECS = (
    {
        "id": "scavengers-eye",
        "kind": "ability",
        "identifier": "ScavengersEye",
        "lane": "Fortune",
        "position": (0, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "read-the-room",
        "kind": "talent",
        "identifier": "thief.read-the-room",
        "name": "Read the Room",
        "description": "Successful meaningful luck outcomes grant an extra Fortune 25% of the time.",
        "lane": "Fortune",
        "position": (0, 1),
        "level": 35,
        "prerequisites": ("scavengers-eye",),
    },
    {
        "id": "gold-toss",
        "kind": "ability",
        "identifier": "GoldToss",
        "lane": "Fortune",
        "position": (0, 2),
        "level": 40,
        "owned_if_known": True,
        "prerequisites": ("read-the-room",),
    },
    {
        "id": "fortune-vitality",
        "kind": "health",
        "identifier": "Health",
        "lane": "Fortune",
        "position": (0, 3),
        "level": 45,
        "level_band_gate": True,
        "prerequisites": ("gold-toss",),
    },
    {
        "id": "gilt-edge",
        "kind": "talent",
        "identifier": "thief.gilt-edge",
        "name": "Gilt Edge",
        "description": "Fortune spent on a risky action grants 2.5 additional accuracy points per stack.",
        "lane": "Fortune",
        "position": (0, 4),
        "level": 50,
        "prerequisites": ("fortune-vitality",),
    },
    {
        "id": "fortune-favors-bold",
        "kind": "talent",
        "identifier": "thief.fortune-favors-bold",
        "name": "Fortune Favors the Bold",
        "description": "A clean Fortune payoff preserves one spent stack once per action.",
        "lane": "Fortune",
        "position": (0, 5),
        "level": 55,
        "prerequisites": ("gilt-edge",),
    },
    {
        "id": "mug",
        "kind": "ability",
        "identifier": "Mug",
        "lane": "Misfortune",
        "position": (1, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "hard-lessons",
        "kind": "talent",
        "identifier": "thief.hard-lessons",
        "name": "Hard Lessons",
        "description": "Misfortune damage and severity scaling increases from 8% to 10% per stack.",
        "lane": "Misfortune",
        "position": (1, 1),
        "level": 35,
        "prerequisites": ("mug",),
    },
    {
        "id": "spiteful-attack",
        "kind": "rating",
        "identifier": "Attack",
        "lane": "Misfortune",
        "position": (1, 2),
        "level": 40,
        "level_band_gate": True,
        "prerequisites": ("hard-lessons",),
    },
    {
        "id": "turn-the-tables",
        "kind": "ability",
        "identifier": "TurnTheTables",
        "lane": "Misfortune",
        "position": (1, 3),
        "level": 45,
        "prerequisites": ("spiteful-attack",),
    },
    {
        "id": "spiteful-streak",
        "kind": "talent",
        "identifier": "thief.spiteful-streak",
        "name": "Spiteful Streak",
        "description": "A Misfortune status payoff adds one further turn to the affected condition.",
        "lane": "Misfortune",
        "position": (1, 4),
        "level": 50,
        "prerequisites": ("turn-the-tables",),
    },
    {
        "id": "reversal",
        "kind": "talent",
        "identifier": "thief.reversal",
        "name": "Reversal",
        "description": "Turn the Tables grants 5 points per stack and lasts four turns.",
        "lane": "Misfortune",
        "position": (1, 5),
        "level": 55,
        "prerequisites": ("spiteful-streak",),
    },
    {
        "id": "lockpick",
        "kind": "ability",
        "identifier": "Lockpick",
        "lane": "Tools",
        "position": (2, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "careful-hands",
        "kind": "talent",
        "identifier": "thief.careful-hands",
        "name": "Careful Hands",
        "description": "Reduce Lockpick Kit break chance by 10 percentage points.",
        "lane": "Tools",
        "position": (2, 1),
        "level": 35,
        "prerequisites": ("lockpick",),
    },
    {
        "id": "trap-lore",
        "kind": "talent",
        "identifier": "thief.trap-lore",
        "name": "Trap Lore",
        "description": "Find Traps gains 15 percentage points of detection chance.",
        "lane": "Tools",
        "position": (2, 2),
        "level": 40,
        "prerequisites": ("careful-hands",),
    },
    {
        "id": "pilfering-strike",
        "kind": "ability",
        "identifier": "PilferingStrike",
        "lane": "Tools",
        "position": (2, 3),
        "level": 45,
        "prerequisites": ("trap-lore",),
    },
    {
        "id": "master-tools",
        "kind": "talent",
        "identifier": "thief.master-tools",
        "name": "Master Tools",
        "description": "Pilfering Strike steals twice as much gold and tool break chance falls further.",
        "lane": "Tools",
        "position": (2, 5),
        "level": 55,
        "prerequisites": ("pilfering-strike",),
    },
    {
        "id": "cut-and-run",
        "kind": "ability",
        "identifier": "CutAndRun",
        "lane": "Escape",
        "position": (3, 0),
        "available_on_promotion": True,
    },
    {
        "id": "smoke-tactician",
        "kind": "talent",
        "identifier": "thief.smoke-tactician",
        "name": "Smoke Tactician",
        "description": "Smoke Screen has a 25% chance not to consume its Smoke Bomb.",
        "lane": "Escape",
        "position": (3, 1),
        "level": 35,
        "prerequisites": ("cut-and-run",),
    },
    {
        "id": "fleet-footed",
        "kind": "talent",
        "identifier": "thief.fleet-footed",
        "name": "Fleet Footed",
        "description": "Cut and Run grants 12 Speed instead of 8.",
        "lane": "Escape",
        "position": (3, 2),
        "level": 40,
        "prerequisites": ("smoke-tactician",),
    },
    {
        "id": "lasting-head-start",
        "kind": "talent",
        "identifier": "thief.lasting-head-start",
        "name": "Lasting Head Start",
        "description": "Cut and Run's Speed bonus lasts one additional turn.",
        "lane": "Escape",
        "position": (3, 3),
        "level": 45,
        "prerequisites": ("fleet-footed",),
    },
    {
        "id": "clean-getaway",
        "kind": "talent",
        "identifier": "thief.clean-getaway",
        "name": "Clean Getaway",
        "description": "A successful Smoke Screen escape grants one Fortune before combat ends.",
        "lane": "Escape",
        "position": (3, 5),
        "level": 55,
        "prerequisites": ("lasting-head-start",),
    },
)


ROGUE_TREE_NODE_SPECS = (
    {
        "id": "finders-keepers",
        "kind": "ability",
        "identifier": "FindersKeepers",
        "lane": "Loaded Odds",
        "position": (0, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "stacked-odds",
        "kind": "talent",
        "identifier": "rogue.stacked-odds",
        "name": "Stacked Odds",
        "description": "Fortune grants 2.5 additional accuracy points per spent stack.",
        "lane": "Loaded Odds",
        "position": (0, 1),
        "level": 65,
        "prerequisites": ("finders-keepers",),
    },
    {
        "id": "slot-machine",
        "kind": "ability",
        "identifier": "SlotMachine",
        "lane": "Loaded Odds",
        "position": (0, 2),
        "level": 70,
        "owned_if_known": True,
        "prerequisites": ("stacked-odds",),
    },
    {
        "id": "rigged-reels",
        "kind": "talent",
        "identifier": "rogue.rigged-reels",
        "name": "Rigged Reels",
        "description": "Slot Machine treats Misfortune as 25% stronger when scaling a winning result.",
        "lane": "Loaded Odds",
        "position": (0, 3),
        "level": 75,
        "prerequisites": ("slot-machine",),
    },
    {
        "id": "triple-strike",
        "kind": "ability",
        "identifier": "TripleStrike",
        "lane": "Loaded Odds",
        "position": (0, 4),
        "level": 80,
        "owned_if_known": True,
        "upgrade_without_source": True,
        "prerequisites": ("rigged-reels",),
    },
    {
        "id": "all-in",
        "kind": "ability",
        "identifier": "AllIn",
        "lane": "Loaded Odds",
        "position": (0, 5),
        "level": 85,
        "cost": 2,
        "prerequisites": ("triple-strike",),
    },
    {
        "id": "house-always-wins",
        "kind": "talent",
        "identifier": "rogue.house-always-wins",
        "name": "The House Always Wins",
        "description": "A successful All In preserves one Fortune when any Fortune was spent.",
        "lane": "Loaded Odds",
        "position": (0, 6),
        "level": 90,
        "prerequisites": ("all-in",),
    },
    {
        "id": "sneak-attack",
        "kind": "ability",
        "identifier": "SneakAttack",
        "lane": "Comebacks",
        "position": (1, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "cruel-reversal",
        "kind": "talent",
        "identifier": "rogue.cruel-reversal",
        "name": "Cruel Reversal",
        "description": "Misfortune damage and severity scaling increases by 2 percentage points per stack.",
        "lane": "Comebacks",
        "position": (1, 1),
        "level": 65,
        "prerequisites": ("sneak-attack",),
    },
    {
        "id": "zephyrstrike",
        "kind": "ability",
        "identifier": "Zephyrstrike",
        "lane": "Comebacks",
        "position": (1, 2),
        "level": 70,
        "owned_if_known": True,
        "prerequisites": ("cruel-reversal",),
    },
    {
        "id": "snake-eyes",
        "kind": "ability",
        "identifier": "SnakeEyes",
        "lane": "Comebacks",
        "position": (1, 3),
        "level": 75,
        "prerequisites": ("zephyrstrike",),
    },
    {
        "id": "cheat-death",
        "kind": "ability",
        "identifier": "CheatDeath",
        "lane": "Comebacks",
        "position": (1, 4),
        "level": 80,
        "owned_if_known": True,
        "prerequisites": ("snake-eyes",),
    },
    {
        "id": "cheat-fate",
        "kind": "talent",
        "identifier": "rogue.cheat-fate",
        "name": "Cheat Fate",
        "description": "Cheat Death gains 10 percentage points of success chance.",
        "lane": "Comebacks",
        "position": (1, 5),
        "level": 85,
        "prerequisites": ("cheat-death",),
    },
    {
        "id": "break-the-jinx",
        "kind": "talent",
        "identifier": "rogue.break-the-jinx",
        "name": "Break the Jinx",
        "description": "A successful Cheat Death applies Jinx for one turn instead of two.",
        "lane": "Comebacks",
        "position": (1, 6),
        "level": 90,
        "prerequisites": ("cheat-fate",),
    },
    {
        "id": "keen-eye",
        "kind": "ability",
        "identifier": "KeenEye",
        "lane": "Cunning",
        "position": (2, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "master-lockpick",
        "kind": "ability",
        "identifier": "MasterLockpick",
        "lane": "Cunning",
        "position": (2, 1),
        "level": 65,
        "owned_if_known": True,
        "prerequisites": ("keen-eye",),
    },
    {
        "id": "disarm-traps",
        "kind": "ability",
        "identifier": "DisarmTraps",
        "lane": "Cunning",
        "position": (2, 2),
        "level": 70,
        "prerequisites": ("master-lockpick",),
    },
    {
        "id": "sure-hands",
        "kind": "talent",
        "identifier": "rogue.sure-hands",
        "name": "Sure Hands",
        "description": "Disarm Traps gains 15 percentage points of success chance.",
        "lane": "Cunning",
        "position": (2, 3),
        "level": 75,
        "prerequisites": ("disarm-traps",),
    },
    {
        "id": "dirty-trick",
        "kind": "ability",
        "identifier": "DirtyTrick",
        "lane": "Cunning",
        "position": (2, 4),
        "level": 80,
        "prerequisites": ("sure-hands",),
    },
    {
        "id": "deep-pockets",
        "kind": "talent",
        "identifier": "rogue.deep-pockets",
        "name": "Deep Pockets",
        "description": "Finders Keepers gains 10 percentage points of ordinary-find chance.",
        "lane": "Cunning",
        "position": (2, 5),
        "level": 85,
        "prerequisites": ("dirty-trick",),
    },
    {
        "id": "impossible-job",
        "kind": "talent",
        "identifier": "rogue.impossible-job",
        "name": "Impossible Job",
        "description": "Disarm Traps can reach 95% success and failed attempts apply half severity.",
        "lane": "Cunning",
        "position": (2, 6),
        "level": 90,
        "cost": 2,
        "prerequisites": ("deep-pockets",),
    },
    {
        "id": "take-it-on-run",
        "kind": "ability",
        "identifier": "TakeItOnTheRun",
        "lane": "Escape",
        "position": (3, 0),
        "available_on_promotion": True,
    },
    {
        "id": "cut-and-run",
        "kind": "ability",
        "identifier": "CutAndRun",
        "lane": "Escape",
        "position": (3, 1),
        "level": 65,
        "owned_if_known": True,
        "prerequisites": ("take-it-on-run",),
    },
    {
        "id": "smoke-screen",
        "kind": "ability",
        "identifier": "SmokeScreen",
        "lane": "Escape",
        "position": (3, 2),
        "level": 70,
        "owned_if_known": True,
        "prerequisites": ("cut-and-run",),
    },
    {
        "id": "slippery-customer",
        "kind": "talent",
        "identifier": "rogue.slippery-customer",
        "name": "Slippery Customer",
        "description": "Cut and Run grants 15 Speed and lasts three turns.",
        "lane": "Escape",
        "position": (3, 3),
        "level": 75,
        "prerequisites": ("smoke-screen",),
    },
    {
        "id": "evasive-guard",
        "kind": "ability",
        "identifier": "EvasiveGuard",
        "lane": "Escape",
        "position": (3, 4),
        "level": 80,
        "owned_if_known": True,
        "prerequisites": ("slippery-customer",),
    },
    {
        "id": "smoke-and-mirrors",
        "kind": "talent",
        "identifier": "rogue.smoke-and-mirrors",
        "name": "Smoke and Mirrors",
        "description": "Smoke Screen has a further 25% chance not to consume its Smoke Bomb.",
        "lane": "Escape",
        "position": (3, 5),
        "level": 85,
        "prerequisites": ("evasive-guard",),
    },
    {
        "id": "gone-before-dawn",
        "kind": "talent",
        "identifier": "rogue.gone-before-dawn",
        "name": "Gone Before Dawn",
        "description": "Take It On the Run steals twice as much gold on a clean escape.",
        "lane": "Escape",
        "position": (3, 6),
        "level": 90,
        "prerequisites": ("smoke-and-mirrors",),
    },
)

INQUISITOR_TREE_NODE_SPECS = (
    {
        "id": "reveal",
        "kind": "ability",
        "identifier": "Reveal",
        "lane": "Case Journal",
        "position": (0, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "inspect",
        "kind": "ability",
        "identifier": "Inspect",
        "lane": "Case Journal",
        "position": (0, 1),
        "level": 35,
        "owned_if_known": True,
        "prerequisites": ("reveal",),
    },
    {
        "id": "take-notes",
        "kind": "ability",
        "identifier": "TakeNotes",
        "name": "Take Notes",
        "lane": "Case Journal",
        "position": (0, 2),
        "level": 40,
        "cost": 2,
        "prerequisites": ("inspect",),
    },
    {
        "id": "exploit-weakness",
        "kind": "ability",
        "identifier": "ExploitWeakness",
        "lane": "Case Journal",
        "position": (0, 3),
        "level": 45,
        "owned_if_known": True,
        "prerequisites": ("take-notes",),
    },
    {
        "id": "analytical-precision",
        "kind": "talent",
        "identifier": "inquisitor.analytical-precision",
        "name": "Analytical Precision",
        "description": "Increase Attack by 10% after learning to exploit recorded weaknesses.",
        "lane": "Case Journal",
        "position": (0, 4),
        "level": 50,
        "prerequisites": ("exploit-weakness",),
        "bonuses": {"rating_percentages": {"Attack": 0.10}},
    },
    {
        "id": "keen-eye",
        "kind": "ability",
        "identifier": "KeenEye",
        "lane": "Case Journal",
        "position": (0, 5),
        "level": 55,
        "owned_if_known": True,
        "prerequisites": ("analytical-precision",),
    },
    {
        "id": "piercing-strike",
        "kind": "ability",
        "identifier": "PiercingStrike",
        "lane": "Judgment",
        "position": (1, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "shield-block",
        "kind": "ability",
        "identifier": "ShieldBlock",
        "lane": "Judgment",
        "position": (1, 1),
        "level": 35,
        "owned_if_known": True,
        "prerequisites": ("piercing-strike",),
    },
    {
        "id": "dispel",
        "kind": "ability",
        "identifier": "Dispel",
        "lane": "Judgment",
        "position": (1, 2),
        "level": 40,
        "owned_if_known": True,
        "prerequisites": ("shield-block",),
    },
    {
        "id": "silence",
        "kind": "ability",
        "identifier": "Silence",
        "lane": "Judgment",
        "position": (1, 3),
        "level": 45,
        "owned_if_known": True,
        "prerequisites": ("dispel",),
    },
    {
        "id": "reflect",
        "kind": "ability",
        "identifier": "Reflect",
        "lane": "Judgment",
        "position": (1, 4),
        "level": 50,
        "owned_if_known": True,
        "prerequisites": ("silence",),
    },
    {
        "id": "true-strike",
        "kind": "ability",
        "identifier": "TrueStrike",
        "lane": "Judgment",
        "position": (1, 5),
        "level": 55,
        "owned_if_known": True,
        "prerequisites": ("reflect",),
    },
    {
        "id": "enfeeble",
        "kind": "ability",
        "identifier": "Enfeeble",
        "lane": "Judgment",
        "position": (2, 3),
        "level": 45,
        "owned_if_known": True,
        "prerequisites": ("dispel",),
    },
    {
        "id": "debilitating-doctrine",
        "kind": "talent",
        "identifier": "inquisitor.debilitating-doctrine",
        "name": "Debilitating Doctrine",
        "description": "Increase Magic by 10% after mastering Enfeeble.",
        "lane": "Judgment",
        "position": (2, 4),
        "level": 50,
        "prerequisites": ("enfeeble",),
        "bonuses": {"rating_percentages": {"Magic": 0.10}},
    },
    {
        "id": "resist-fire",
        "kind": "ability",
        "identifier": "ResistFire",
        "lane": "Elemental Wards",
        "position": (3, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "resist-ice",
        "kind": "ability",
        "identifier": "ResistIce",
        "lane": "Elemental Wards",
        "position": (4, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "warding-studies",
        "kind": "talent",
        "identifier": "inquisitor.warding-studies",
        "name": "Warding Studies",
        "description": "All six elemental Resist spells last two additional turns.",
        "lane": "Elemental Wards",
        "position": (3.5, 1),
        "level": 35,
        "prerequisites": ("resist-fire", "resist-ice"),
    },
    {
        "id": "resist-electric",
        "kind": "ability",
        "identifier": "ResistElectric",
        "lane": "Elemental Wards",
        "position": (3, 2),
        "level": 40,
        "owned_if_known": True,
        "prerequisites": ("warding-studies",),
    },
    {
        "id": "resist-water",
        "kind": "ability",
        "identifier": "ResistWater",
        "lane": "Elemental Wards",
        "position": (4, 2),
        "level": 40,
        "owned_if_known": True,
        "prerequisites": ("warding-studies",),
    },
    {
        "id": "elemental-poise",
        "kind": "talent",
        "identifier": "inquisitor.elemental-poise",
        "name": "Elemental Poise",
        "description": "Increase Magic Defense by 10% through elemental conditioning.",
        "lane": "Elemental Wards",
        "position": (3.5, 3),
        "level": 45,
        "prerequisites": ("resist-electric", "resist-water"),
        "bonuses": {"rating_percentages": {"Magic Defense": 0.10}},
    },
    {
        "id": "resist-earth",
        "kind": "ability",
        "identifier": "ResistEarth",
        "lane": "Elemental Wards",
        "position": (3, 4),
        "level": 50,
        "owned_if_known": True,
        "prerequisites": ("elemental-poise",),
    },
    {
        "id": "resist-wind",
        "kind": "ability",
        "identifier": "ResistWind",
        "lane": "Elemental Wards",
        "position": (4, 4),
        "level": 50,
        "owned_if_known": True,
        "prerequisites": ("elemental-poise",),
    },
    {
        "id": "adaptive-constitution",
        "kind": "talent",
        "identifier": "inquisitor.adaptive-constitution",
        "name": "Adaptive Constitution",
        "description": "Increase maximum HP by 10% after completing elemental ward training.",
        "lane": "Elemental Wards",
        "position": (3.5, 5),
        "level": 55,
        "prerequisites": ("resist-earth", "resist-wind"),
        "bonuses": {"health_percentage": 0.10},
    },
)


SEEKER_TREE_NODE_SPECS = (
    {
        "id": "cartography",
        "kind": "ability",
        "identifier": "Cartography",
        "lane": "Wayfinding",
        "position": (0, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "early-bearings",
        "kind": "talent",
        "identifier": "seeker.early-bearings",
        "name": "Early Bearings",
        "description": "Mapped-floor Wayfinding discounts begin at 35% exploration instead of 50%.",
        "lane": "Wayfinding",
        "position": (0, 1),
        "level": 65,
        "prerequisites": ("cartography",),
    },
    {
        "id": "wayfinding",
        "kind": "ability",
        "identifier": "Wayfinding",
        "lane": "Wayfinding",
        "position": (0, 2),
        "level": 70,
        "owned_if_known": True,
        "prerequisites": ("early-bearings",),
    },
    {
        "id": "surveyors-step",
        "kind": "ability",
        "identifier": "SurveyorsStep",
        "name": "Surveyor's Step",
        "lane": "Wayfinding",
        "position": (0, 3),
        "level": 75,
        "prerequisites": ("wayfinding",),
    },
    {
        "id": "teleport",
        "kind": "ability",
        "identifier": "Teleport",
        "lane": "Wayfinding",
        "position": (0, 4),
        "level": 80,
        "owned_if_known": True,
        "prerequisites": ("surveyors-step",),
    },
    {
        "id": "efficient-passage",
        "kind": "talent",
        "identifier": "seeker.efficient-passage",
        "name": "Efficient Passage",
        "description": "Increase every earned Wayfinding MP discount by five percentage points.",
        "lane": "Wayfinding",
        "position": (0, 5),
        "level": 85,
        "prerequisites": ("teleport",),
    },
    {
        "id": "enter-wall",
        "kind": "ability",
        "identifier": "EnterWall",
        "lane": "Wayfinding",
        "position": (0, 6),
        "level": 90,
        "owned_if_known": True,
        "prerequisites": ("efficient-passage",),
    },
    {
        "id": "volitation",
        "kind": "ability",
        "identifier": "Volitation",
        "lane": "Safe Passage",
        "position": (1, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "light-footed",
        "kind": "talent",
        "identifier": "seeker.light-footed",
        "name": "Light Footed",
        "description": "Surveyor's Step grants five additional Speed.",
        "lane": "Safe Passage",
        "position": (1, 1),
        "level": 65,
        "prerequisites": ("volitation",),
    },
    {
        "id": "safe-passage",
        "kind": "ability",
        "identifier": "SafePassage",
        "name": "Safe Passage",
        "lane": "Safe Passage",
        "position": (1, 2),
        "level": 70,
        "prerequisites": ("light-footed",),
    },
    {
        "id": "sanctuary",
        "kind": "ability",
        "identifier": "Sanctuary",
        "lane": "Safe Passage",
        "position": (1, 3),
        "level": 75,
        "owned_if_known": True,
        "prerequisites": ("safe-passage",),
    },
    {
        "id": "sanctuary-route",
        "kind": "talent",
        "identifier": "seeker.sanctuary-route",
        "name": "Sanctuary Route",
        "description": "Safe Passage lasts one additional turn.",
        "lane": "Safe Passage",
        "position": (1, 4),
        "level": 80,
        "prerequisites": ("sanctuary",),
    },
    {
        "id": "resist-all",
        "kind": "ability",
        "identifier": "ResistAll",
        "lane": "Safe Passage",
        "position": (1, 5),
        "level": 85,
        "owned_if_known": True,
        "prerequisites": ("sanctuary-route",),
    },
    {
        "id": "master-cartographer",
        "kind": "talent",
        "identifier": "seeker.master-cartographer",
        "name": "Master Cartographer",
        "description": "Safe Passage reaches full strength at 35% mapped instead of 50%.",
        "lane": "Safe Passage",
        "position": (1, 6),
        "level": 90,
        "cost": 2,
        "prerequisites": ("resist-all",),
    },
    {
        "id": "inspect",
        "kind": "ability",
        "identifier": "Inspect",
        "lane": "Revelation",
        "position": (2, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "practiced-inspection",
        "kind": "talent",
        "identifier": "seeker.practiced-inspection",
        "name": "Practiced Inspection",
        "description": "Inspect records four Case Journal progress instead of three.",
        "lane": "Revelation",
        "position": (2, 1),
        "level": 65,
        "prerequisites": ("inspect",),
    },
    {
        "id": "deductive-strike",
        "kind": "ability",
        "identifier": "DeductiveStrike",
        "name": "Deductive Strike",
        "lane": "Revelation",
        "position": (2, 2),
        "level": 70,
        "prerequisites": ("practiced-inspection",),
    },
    {
        "id": "patient-deduction",
        "kind": "talent",
        "identifier": "seeker.patient-deduction",
        "name": "Patient Deduction",
        "description": "Deductive Strike reaches full power against Known Tells at 25 Case progress.",
        "lane": "Revelation",
        "position": (2, 3),
        "level": 75,
        "prerequisites": ("deductive-strike",),
    },
    {
        "id": "foregone-conclusion",
        "kind": "ability",
        "identifier": "ForegoneConclusion",
        "name": "Foregone Conclusion",
        "lane": "Revelation",
        "position": (2, 4),
        "level": 80,
        "cost": 2,
        "prerequisites": ("patient-deduction",),
    },
    {
        "id": "proven-case",
        "kind": "talent",
        "identifier": "seeker.proven-case",
        "name": "Proven Case",
        "description": "Foregone Conclusion reduces each rating by eight per Revelation instead of six.",
        "lane": "Revelation",
        "position": (2, 5),
        "level": 85,
        "prerequisites": ("foregone-conclusion",),
    },
    {
        "id": "inevitable-conclusion",
        "kind": "talent",
        "identifier": "seeker.inevitable-conclusion",
        "name": "Inevitable Conclusion",
        "description": "Foregone Conclusion lasts four turns instead of three.",
        "lane": "Revelation",
        "position": (2, 6),
        "level": 90,
        "prerequisites": ("proven-case",),
    },
    {
        "id": "third-eye",
        "kind": "ability",
        "identifier": "ThirdEye",
        "lane": "Judgment",
        "position": (3, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "weaken-mind",
        "kind": "ability",
        "identifier": "WeakenMind",
        "lane": "Judgment",
        "position": (3, 1),
        "level": 65,
        "owned_if_known": True,
        "prerequisites": ("third-eye",),
    },
    {
        "id": "triple-strike",
        "kind": "ability",
        "identifier": "TripleStrike",
        "lane": "Judgment",
        "position": (3, 2),
        "level": 70,
        "owned_if_known": True,
        "upgrade_without_source": True,
        "prerequisites": ("weaken-mind",),
    },
    {
        "id": "precise-revelation",
        "kind": "talent",
        "identifier": "seeker.precise-revelation",
        "name": "Precise Revelation",
        "description": "Committed Revelation grants five accuracy points per stack instead of four.",
        "lane": "Judgment",
        "position": (3, 3),
        "level": 75,
        "prerequisites": ("triple-strike",),
    },
    {
        "id": "true-piercing-strike",
        "kind": "ability",
        "identifier": "TruePiercingStrike",
        "lane": "Judgment",
        "position": (3, 4),
        "level": 80,
        "owned_if_known": True,
        "upgrade_without_source": True,
        "prerequisites": ("precise-revelation",),
    },
    {
        "id": "conserved-insight",
        "kind": "talent",
        "identifier": "seeker.conserved-insight",
        "name": "Conserved Insight",
        "description": "A missed Revelation payoff restores one committed stack.",
        "lane": "Judgment",
        "position": (3, 5),
        "level": 85,
        "prerequisites": ("true-piercing-strike",),
    },
    {
        "id": "exposed-truth",
        "kind": "talent",
        "identifier": "seeker.exposed-truth",
        "name": "Exposed Truth",
        "description": "A successful Revelation payoff reduces Defense by two per stack for three turns.",
        "lane": "Judgment",
        "position": (3, 6),
        "level": 90,
        "prerequisites": ("conserved-insight",),
    },
)

SPELL_STEALER_TREE_NODE_SPECS = (
    {
        "id": "steal-spell",
        "kind": "ability",
        "identifier": "StealSpell",
        "lane": "Spell Theft",
        "position": (0, 0),
        "cost": 1,
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "arcane-ledger",
        "kind": "talent",
        "identifier": "spell-stealer.arcane-ledger",
        "name": "Arcane Ledger",
        "description": "Reduce Steal Spell's MP cost by two.",
        "lane": "Spell Theft",
        "position": (0, 1),
        "level": 35,
        "cost": 2,
        "prerequisites": ("steal-spell",),
    },
    {
        "id": "wind-speed",
        "kind": "ability",
        "identifier": "WindSpeed",
        "lane": "Spell Theft",
        "position": (0, 2),
        "level": 40,
        "cost": 1,
        "owned_if_known": True,
        "prerequisites": ("arcane-ledger",),
    },
    {
        "id": "counterfeit-casting",
        "kind": "talent",
        "identifier": "spell-stealer.counterfeit-casting",
        "name": "Counterfeit Casting",
        "description": (
            "Casting an inscribed stolen-spell scroll gains two Stolen Charge instead of one."
        ),
        "lane": "Spell Theft",
        "position": (0, 3),
        "level": 45,
        "cost": 2,
        "prerequisites": ("wind-speed",),
    },
    {
        "id": "silence",
        "kind": "ability",
        "identifier": "Silence",
        "lane": "Spell Theft",
        "position": (0, 4),
        "level": 50,
        "cost": 1,
        "owned_if_known": True,
        "prerequisites": ("counterfeit-casting",),
    },
    {
        "id": "perfect-forgery",
        "kind": "talent",
        "identifier": "spell-stealer.perfect-forgery",
        "name": "Perfect Forgery",
        "description": (
            "Successful Steal Spell attempts have a 25% chance to preserve the Blank Scroll."
        ),
        "lane": "Spell Theft",
        "position": (0, 5),
        "level": 55,
        "cost": 2,
        "prerequisites": ("silence",),
    },
    {
        "id": "imbue-weapon",
        "kind": "ability",
        "identifier": "ImbueWeapon",
        "lane": "Stolen Charge",
        "position": (1, 0),
        "cost": 1,
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "spellbreakers-cut",
        "kind": "ability",
        "identifier": "SpellbreakersCut",
        "lane": "Stolen Charge",
        "position": (1, 1),
        "level": 35,
        "cost": 1,
        "prerequisites": ("imbue-weapon",),
    },
    {
        "id": "steal-as-well",
        "kind": "ability",
        "identifier": "StealAsWell",
        "lane": "Stolen Charge",
        "position": (1, 2),
        "level": 40,
        "cost": 1,
        "owned_if_known": True,
        "prerequisites": ("spellbreakers-cut",),
    },
    {
        "id": "borrowed-ward",
        "kind": "ability",
        "identifier": "BorrowedWard",
        "lane": "Stolen Charge",
        "position": (1, 3),
        "level": 45,
        "cost": 2,
        "prerequisites": ("steal-as-well",),
    },
    {
        "id": "volatile-script",
        "kind": "talent",
        "identifier": "spell-stealer.volatile-script",
        "name": "Volatile Script",
        "description": (
            "Each committed Stolen Charge adds 25% of the triggering action's "
            "damage instead of 20%."
        ),
        "lane": "Stolen Charge",
        "position": (1, 4),
        "level": 50,
        "cost": 2,
        "prerequisites": ("borrowed-ward",),
    },
    {
        "id": "controlled-discharge",
        "kind": "talent",
        "identifier": "spell-stealer.controlled-discharge",
        "name": "Controlled Discharge",
        "description": (
            "When a charged payoff misses or finds no purchase, retain one Stolen Charge."
        ),
        "lane": "Stolen Charge",
        "position": (1, 5),
        "level": 55,
        "cost": 3,
        "prerequisites": ("volatile-script",),
    },
)


ARCANE_TRICKSTER_TREE_NODE_SPECS = (
    {
        "id": "steal-spell-2",
        "kind": "ability",
        "identifier": "StealSpell2",
        "lane": "Spell Theft",
        "position": (0, 0),
        "cost": 2,
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "master-thief",
        "kind": "talent",
        "identifier": "arcane-trickster.master-thief",
        "name": "Master Thief",
        "description": (
            "Add 15 percentage points to Steal Spell II's learning chance and raise its cap to 90%."
        ),
        "lane": "Spell Theft",
        "position": (0, 1),
        "level": 65,
        "cost": 3,
        "prerequisites": ("steal-spell-2",),
    },
    {
        "id": "arcane-ambush",
        "kind": "ability",
        "identifier": "ArcaneAmbush",
        "lane": "Spell Theft",
        "position": (0, 2),
        "level": 70,
        "cost": 2,
        "prerequisites": ("master-thief",),
    },
    {
        "id": "mnemonic-larceny",
        "kind": "talent",
        "identifier": "arcane-trickster.mnemonic-larceny",
        "name": "Mnemonic Larceny",
        "description": "Permanently learning a spell restores half of Steal Spell II's MP cost.",
        "lane": "Spell Theft",
        "position": (0, 3),
        "level": 75,
        "cost": 3,
        "prerequisites": ("arcane-ambush",),
    },
    {
        "id": "neural-connection",
        "kind": "talent",
        "identifier": "arcane-trickster.neural-connection",
        "name": "Neural Connection",
        "description": (
            "When Weaken Mind has been stolen, it grants equal Magic and Magic "
            "Defense while its target remains weakened."
        ),
        "lane": "Stolen Spell Mastery",
        "position": (2, 5),
        "level": 85,
        "cost": 3,
        "prerequisites": ("steal-spell-2",),
    },
    {
        "id": "third-eye",
        "kind": "ability",
        "identifier": "ThirdEye",
        "lane": "Misdirection",
        "position": (1, 0),
        "cost": 2,
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "vanishing-act",
        "kind": "ability",
        "identifier": "VanishingAct",
        "lane": "Misdirection",
        "position": (1, 1),
        "level": 65,
        "cost": 2,
        "prerequisites": ("third-eye",),
    },
    {
        "id": "escape-artist",
        "kind": "talent",
        "identifier": "arcane-trickster.escape-artist",
        "name": "Escape Artist",
        "description": (
            "Vanishing Act grants 12 Speed and Defense for four turns instead of 8 for three."
        ),
        "lane": "Misdirection",
        "position": (1, 2),
        "level": 70,
        "cost": 3,
        "prerequisites": ("vanishing-act",),
    },
    {
        "id": "false-opening",
        "kind": "ability",
        "identifier": "FalseOpening",
        "lane": "Misdirection",
        "position": (1, 3),
        "level": 75,
        "cost": 2,
        "prerequisites": ("escape-artist",),
    },
    {
        "id": "misdirection",
        "kind": "talent",
        "identifier": "arcane-trickster.misdirection",
        "name": "Misdirection",
        "description": (
            "A successful Stolen Charge payoff also lowers the target's Attack "
            "and Magic for two turns."
        ),
        "lane": "Misdirection",
        "position": (1, 4),
        "level": 80,
        "cost": 3,
        "prerequisites": ("false-opening",),
    },
    {
        "id": "grand-larceny",
        "kind": "talent",
        "identifier": "arcane-trickster.grand-larceny",
        "name": "Grand Larceny",
        "description": "Increase maximum Stolen Charge by one.",
        "lane": "Misdirection",
        "position": (1, 5),
        "level": 85,
        "cost": 3,
        "prerequisites": ("misdirection",),
        "kit_effect": ("meter_cap", "stolen_charge", 1),
    },
)


def _assassin_lane_specs(lane, column, entries):
    """Build one authored Assassin lane while preserving deliberate blank rows."""
    specs = []
    previous = None
    for row, identifier, level in entries:
        suffix = identifier.replace("!", "").replace(" ", "-").lower()
        spec = {
            "id": suffix,
            "kind": "ability",
            "identifier": identifier.replace(" ", ""),
            "lane": lane,
            "position": (column, row),
        }
        if previous is not None:
            spec["prerequisites"] = (previous,)
        if level is not None:
            spec["level"] = level
        else:
            spec["available_on_promotion"] = True
        specs.append(spec)
        previous = suffix
    return tuple(specs)


ASSASSIN_TREE_NODE_SPECS = (
    *_assassin_lane_specs(
        "Utility",
        0,
        (
            (0, "Steal", None),
            (1, "Lockpick", 35),
            (3, "Disruption", 45),
            (4, "ForGoodMeasure", 50),
            (5, "Distract", 55),
        ),
    ),
    *_assassin_lane_specs(
        "Combat",
        1,
        (
            (0, "TwistTheKnife", None),
            (1, "OffHandExcellence", 35),
            (3, "SneakAttack", 45),
            (4, "Maim", 50),
            (5, "TripleStrike", 55),
        ),
    ),
    *_assassin_lane_specs(
        "Status / Death",
        2,
        (
            (0, "DeathMark", None),
            (1, "ApplyToxin", 35),
            (2, "ResistDeath", 40),
            (3, "Disembowel", 45),
            (4, "MakeToxin", 50),
            (5, "Cutthroat", 55),
        ),
    ),
    *_assassin_lane_specs(
        "Stealth",
        3,
        (
            (0, "AvoidTraps", None),
            (1, "SmokeScreen", 35),
            (2, "HiddenBlade", 40),
            (4, "Surprise", 50),
            (5, "Invisibility", 55),
        ),
    ),
    *_assassin_lane_specs(
        "Counter",
        4,
        (
            (0, "Parry", None),
            (2, "MainGauche", 40),
            (3, "LiveAndLearn", 45),
            (5, "Riposte", 55),
        ),
    ),
)


def _ninja_lane_specs(lane, column, entries):
    """Build an authored Ninja discipline with intentional gaps and costs."""
    specs = []
    previous = None
    for row, identifier, level, cost in entries:
        suffix = identifier.replace(" ", "-").lower()
        spec = {
            "id": suffix,
            "kind": "ability",
            "identifier": identifier.replace(" ", ""),
            "lane": lane,
            "position": (column, row),
            "cost": cost,
        }
        if identifier == "Momentum":
            spec["description"] = (
                "Death Mark setup: attack with both weapons and turn a clean "
                "sequence into a combined finisher."
            )
        if previous is not None:
            spec["prerequisites"] = (previous,)
        if level == 60:
            spec["available_on_promotion"] = True
        else:
            spec["level"] = level
        specs.append(spec)
        previous = suffix
    return tuple(specs)


NINJA_TREE_NODE_SPECS = (
    *_ninja_lane_specs(
        "Utility",
        0,
        (
            (0, "SmokeScreen", 60, 1),
            (1, "Mug", 65, 1),
            (2, "FindTraps", 70, 1),
            (4, "SmashAndGrab", 80, 2),
        ),
    ),
    *_ninja_lane_specs(
        "Combat",
        1,
        (
            (0, "TripleStrike", 60, 1),
            (1, "Momentum", 65, 1),
            (2, "MarkedShuriken", 70, 1),
            (3, "FlurryBlades", 75, 1),
            (4, "ExecutionRhythm", 80, 1),
            (5, "ThousandCuts", 85, 2),
        ),
    ),
    *_ninja_lane_specs(
        "Toxin / Death",
        2,
        (
            (0, "ToxicPrecision", 60, 1),
            (1, "LingeringVenom", 65, 1),
            (2, "DeathSentence", 70, 1),
            (3, "CoatingConservation", 75, 1),
            (4, "Potentiation", 80, 1),
            (5, "BlackLotusMastery", 85, 2),
        ),
    ),
    *_ninja_lane_specs(
        "Stealth",
        3,
        (
            (0, "Haste", 60, 1),
            (1, "Invisibility", 65, 1),
            (2, "SilentWalking", 70, 1),
            (3, "Alacrity", 75, 1),
            (4, "ShadowEvasion", 80, 1),
            (5, "GhostStep", 85, 2),
        ),
    ),
    *_ninja_lane_specs(
        "Defense",
        4,
        (
            (0, "Parry", 60, 1),
            (1, "Riposte", 65, 1),
            (2, "Quickstep", 70, 1),
            (3, "EvasiveGuard", 75, 1),
            (4, "ShadowCounter", 80, 1),
            (5, "Untouchable", 85, 2),
        ),
    ),
)
