"""Healer-line ability-tree declarations."""

from __future__ import annotations

BARD_TREE_NODE_SPECS = (
    {
        "id": "songvalor",
        "kind": "ability",
        "identifier": "SongValor",
        "lane": "Performance",
        "position": (0, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "sustained-performance",
        "kind": "talent",
        "identifier": "bard.sustained-performance",
        "name": "Sustained Performance",
        "description": "Combat songs last one additional turn.",
        "lane": "Performance",
        "position": (0, 1),
        "level": 35,
        "prerequisites": ("songvalor",),
    },
    {
        "id": "driving-rhythm",
        "kind": "talent",
        "identifier": "bard.driving-rhythm",
        "name": "Driving Rhythm",
        "description": "Song of Valor grants a further 5% weapon and magic damage.",
        "lane": "Performance",
        "position": (0, 2),
        "level": 40,
        "prerequisites": ("sustained-performance",),
    },
    {
        "id": "rising-cadence",
        "kind": "talent",
        "identifier": "bard.rising-cadence",
        "name": "Rising Cadence",
        "description": "The first maintained turn of a song gains one additional Crescendo.",
        "lane": "Performance",
        "position": (0, 3),
        "level": 45,
        "prerequisites": ("driving-rhythm",),
    },
    {
        "id": "coda-craft",
        "kind": "talent",
        "identifier": "bard.coda-craft",
        "name": "Coda Craft",
        "description": "Combat codas resolve as though one additional Crescendo were spent.",
        "lane": "Performance",
        "position": (0, 4),
        "level": 50,
        "prerequisites": ("rising-cadence",),
    },
    {
        "id": "resonant-hall",
        "kind": "talent",
        "identifier": "bard.resonant-hall",
        "name": "Resonant Hall",
        "description": "Increase the strength of every active song by 10%.",
        "lane": "Performance",
        "position": (0, 5),
        "level": 55,
        "prerequisites": ("coda-craft",),
    },
    {
        "id": "rhythmic-strike",
        "kind": "ability",
        "identifier": "RhythmicStrike",
        "lane": "Performance",
        "position": (2, 0),
        "available_on_promotion": True,
    },
    {
        "id": "curtain-guard",
        "kind": "ability",
        "identifier": "CurtainGuard",
        "lane": "Performance",
        "position": (2, 1),
        "level": 35,
        "prerequisites": ("rhythmic-strike",),
    },
    {
        "id": "songshelter",
        "kind": "ability",
        "identifier": "SongShelter",
        "lane": "Performance",
        "position": (1, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "sheltering-refrain",
        "kind": "talent",
        "identifier": "bard.sheltering-refrain",
        "name": "Sheltering Refrain",
        "description": "Song of Shelter reduces incoming damage by a further 5%.",
        "lane": "Performance",
        "position": (1, 1),
        "level": 35,
        "prerequisites": ("songshelter",),
    },
    {
        "id": "songrenewal",
        "kind": "ability",
        "identifier": "SongRenewal",
        "lane": "Performance",
        "position": (1, 2),
        "level": 40,
        "available_on_promotion": True,
        "owned_if_known": True,
        "prerequisites": ("sheltering-refrain",),
    },
    {
        "id": "restorative-harmony",
        "kind": "talent",
        "identifier": "bard.restorative-harmony",
        "name": "Restorative Harmony",
        "description": "Song of Renewal restores an additional 2% maximum HP and MP per pulse.",
        "lane": "Performance",
        "position": (1, 3),
        "level": 45,
        "prerequisites": ("songrenewal",),
    },
    {
        "id": "seamless-transition",
        "kind": "talent",
        "identifier": "bard.seamless-transition",
        "name": "Seamless Transition",
        "description": "Replacing a combat song retains one Crescendo instead of clearing it all.",
        "lane": "Performance",
        "position": (1, 4),
        "level": 50,
        "prerequisites": ("restorative-harmony", "inspiring-verse"),
        "prerequisite_mode": "any",
    },
    {
        "id": "crescendo-reserve",
        "kind": "talent",
        "identifier": "bard.crescendo-reserve",
        "name": "Crescendo Reserve",
        "description": "Increase maximum Crescendo by one.",
        "lane": "Performance",
        "position": (1, 5),
        "level": 55,
        "prerequisites": ("seamless-transition",),
        "kit_effect": ("meter_cap", "crescendo", 1),
    },
    {
        "id": "inspiring-verse",
        "kind": "ability",
        "identifier": "InspiringVerse",
        "lane": "Performance",
        "position": (2, 2),
        "level": 40,
        "prerequisites": ("curtain-guard",),
    },
    {
        "id": "battle-arrangement",
        "kind": "talent",
        "identifier": "bard.battle-arrangement",
        "name": "Battle Arrangement",
        "description": "Battle Hymn and Ode to the Ramparts last one additional turn.",
        "lane": "Composition",
        "position": (3, 0),
        "available_on_promotion": True,
    },
    {
        "id": "pointed-satire",
        "kind": "talent",
        "identifier": "bard.pointed-satire",
        "name": "Pointed Satire",
        "description": "Exploration songs that hinder enemy stats apply 5 percentage points more pressure.",
        "lane": "Composition",
        "position": (3, 1),
        "level": 35,
        "prerequisites": ("battle-arrangement",),
    },
    {
        "id": "road-song",
        "kind": "talent",
        "identifier": "bard.road-song",
        "name": "Road Song",
        "description": "Exploration performances carry for 20 additional steps.",
        "lane": "Composition",
        "position": (3, 2),
        "level": 40,
        "prerequisites": ("pointed-satire",),
    },
    {
        "id": "gilded-verse",
        "kind": "talent",
        "identifier": "bard.gilded-verse",
        "name": "Gilded Verse",
        "description": "Gold Trigger improves active and lingering loot multipliers.",
        "lane": "Composition",
        "position": (3, 3),
        "level": 45,
        "prerequisites": ("road-song",),
    },
    {
        "id": "dissonant-chord",
        "kind": "ability",
        "identifier": "DissonantChord",
        "lane": "Composition",
        "position": (3, 4),
        "level": 50,
        "prerequisites": ("gilded-verse",),
    },
    {
        "id": "copyist",
        "kind": "talent",
        "identifier": "bard.copyist",
        "name": "Copyist",
        "description": "Composing has a 25% chance to produce a second sheet of the chosen song.",
        "lane": "Composition",
        "position": (3, 5),
        "level": 55,
        "prerequisites": ("dissonant-chord",),
    },
    {
        "id": "kaleidoscope",
        "kind": "ability",
        "identifier": "Kaleidoscope",
        "lane": "Composition",
        "position": (4, 0),
        "available_on_promotion": True,
    },
    {
        "id": "vivid-palette",
        "kind": "talent",
        "identifier": "bard.vivid-palette",
        "name": "Vivid Palette",
        "description": "Increase Kaleidoscope potency by 15%; Emerald also restores MP.",
        "lane": "Composition",
        "position": (4, 1),
        "level": 35,
        "prerequisites": ("kaleidoscope",),
    },
    {
        "id": "elemental-cadence",
        "kind": "talent",
        "identifier": "bard.elemental-cadence",
        "name": "Elemental Cadence",
        "description": "Kaleidoscope gains one Crescendo while a combat song is active.",
        "lane": "Composition",
        "position": (4, 2),
        "level": 40,
        "prerequisites": ("vivid-palette",),
    },
    {
        "id": "prismatic-ray",
        "kind": "ability",
        "identifier": "PrismaticRay",
        "lane": "Composition",
        "position": (4, 3),
        "level": 45,
        "prerequisites": ("elemental-cadence",),
    },
    {
        "id": "prismatic-flourish",
        "kind": "talent",
        "identifier": "bard.prismatic-flourish",
        "name": "Prismatic Flourish",
        "description": "Azure and Violet Kaleidoscope riders last one additional turn.",
        "lane": "Composition",
        "position": (4, 5),
        "level": 55,
        "prerequisites": ("prismatic-ray",),
    },
)


TROUBADOUR_TREE_NODE_SPECS = (
    {
        "id": "grand-finale",
        "kind": "ability",
        "identifier": "GrandFinale",
        "lane": "Finale",
        "position": (0, 0),
        "available_on_promotion": True,
    },
    {
        "id": "masterful-finale",
        "kind": "talent",
        "identifier": "troubadour.masterful-finale",
        "name": "Masterful Finale",
        "description": "Every combat coda resolves as though one additional Crescendo were spent.",
        "lane": "Finale",
        "position": (0, 1),
        "level": 65,
        "prerequisites": ("grand-finale",),
    },
    {
        "id": "decisive-ending",
        "kind": "talent",
        "identifier": "troubadour.decisive-ending",
        "name": "Decisive Ending",
        "description": "Reduce Grand Finale's MP cost from 8 to 6.",
        "lane": "Finale",
        "position": (0, 2),
        "level": 70,
        "prerequisites": ("masterful-finale",),
    },
    {
        "id": "crescendo-reserve",
        "kind": "talent",
        "identifier": "troubadour.crescendo-reserve",
        "name": "Crescendo Reserve",
        "description": "Increase maximum Crescendo by two.",
        "lane": "Finale",
        "position": (0, 3),
        "level": 75,
        "prerequisites": ("decisive-ending",),
        "kit_effect": ("meter_cap", "crescendo", 2),
    },
    {
        "id": "rolling-crescendo",
        "kind": "talent",
        "identifier": "troubadour.rolling-crescendo",
        "name": "Rolling Crescendo",
        "description": "Each maintained song turn gains one additional Crescendo.",
        "lane": "Finale",
        "position": (0, 4),
        "level": 80,
        "prerequisites": ("crescendo-reserve",),
    },
    {
        "id": "commanding-stage",
        "kind": "talent",
        "identifier": "troubadour.commanding-stage",
        "name": "Commanding Stage",
        "description": "Increase the strength of every active song by 10%.",
        "lane": "Finale",
        "position": (0, 5),
        "level": 85,
        "prerequisites": ("rolling-crescendo",),
    },
    {
        "id": "syncopated-strike",
        "kind": "ability",
        "identifier": "SyncopatedStrike",
        "lane": "Finale",
        "position": (0, 6),
        "level": 85,
        "prerequisites": ("commanding-stage",),
    },
    {
        "id": "heroic-finale",
        "kind": "talent",
        "identifier": "troubadour.heroic-finale",
        "name": "Heroic Finale",
        "description": "Valor codas resolve as though one additional Crescendo were spent.",
        "lane": "Finale",
        "position": (1, 0),
        "available_on_promotion": True,
    },
    {
        "id": "guardian-finale",
        "kind": "talent",
        "identifier": "troubadour.guardian-finale",
        "name": "Guardian Finale",
        "description": "Shelter codas resolve as though one additional Crescendo were spent.",
        "lane": "Finale",
        "position": (1, 1),
        "level": 65,
        "prerequisites": ("heroic-finale",),
    },
    {
        "id": "reviving-finale",
        "kind": "talent",
        "identifier": "troubadour.reviving-finale",
        "name": "Reviving Finale",
        "description": "Renewal codas gain one effective Crescendo and cleanse poison at two spent.",
        "lane": "Finale",
        "position": (1, 2),
        "level": 70,
        "prerequisites": ("guardian-finale",),
    },
    {
        "id": "riotous-finale",
        "kind": "talent",
        "identifier": "troubadour.riotous-finale",
        "name": "Riotous Finale",
        "description": "Battle Hymn's coda extends its controlled Berserk beat by one turn.",
        "lane": "Finale",
        "position": (1, 3),
        "level": 75,
        "prerequisites": ("reviving-finale",),
    },
    {
        "id": "rallying-chorus",
        "kind": "ability",
        "identifier": "RallyingChorus",
        "lane": "Finale",
        "position": (1, 4),
        "level": 80,
        "prerequisites": ("riotous-finale",),
    },
    {
        "id": "cutting-encore",
        "kind": "talent",
        "identifier": "troubadour.cutting-encore",
        "name": "Cutting Refrain",
        "description": "Enemy-stat exploration songs apply 5 percentage points more pressure.",
        "lane": "Finale",
        "position": (1, 5),
        "level": 85,
        "prerequisites": ("rallying-chorus",),
    },
    {
        "id": "resonant-wave",
        "kind": "ability",
        "identifier": "ResonantWave",
        "lane": "Finale",
        "position": (1, 6),
        "level": 85,
        "prerequisites": ("cutting-encore",),
    },
    {
        "id": "composers-memory",
        "kind": "talent",
        "identifier": "troubadour.composers-memory",
        "name": "Composer's Memory",
        "description": "Composition grants two practice XP instead of one.",
        "lane": "Mastery",
        "position": (2, 0),
        "available_on_promotion": True,
    },
    {
        "id": "practiced-ear",
        "kind": "talent",
        "identifier": "troubadour.practiced-ear",
        "name": "Practiced Ear",
        "description": "Maintained advanced-song turns grant one additional practice XP.",
        "lane": "Mastery",
        "position": (2, 1),
        "level": 65,
        "prerequisites": ("composers-memory",),
    },
    {
        "id": "flawless-form",
        "kind": "talent",
        "identifier": "troubadour.flawless-form",
        "name": "Flawless Form",
        "description": "Natural advanced-song completion grants five practice XP instead of three.",
        "lane": "Mastery",
        "position": (2, 2),
        "level": 70,
        "prerequisites": ("practiced-ear",),
    },
    {
        "id": "efficient-repertoire",
        "kind": "talent",
        "identifier": "troubadour.efficient-repertoire",
        "name": "Efficient Repertoire",
        "description": "Reduce mastered repertoire song MP costs by two.",
        "lane": "Mastery",
        "position": (2, 3),
        "level": 75,
        "prerequisites": ("flawless-form",),
    },
    {
        "id": "repertoire-authority",
        "kind": "talent",
        "identifier": "troubadour.repertoire-authority",
        "name": "Repertoire Authority",
        "description": "Increase the strength of every active song by a further 10%.",
        "lane": "Mastery",
        "position": (2, 4),
        "level": 80,
        "prerequisites": ("efficient-repertoire",),
    },
    {
        "id": "learned-encore",
        "kind": "talent",
        "identifier": "troubadour.learned-encore",
        "name": "Learned Encore",
        "description": "A naturally completed song leaves a 35%-strength final beat without requiring a ring.",
        "lane": "Mastery",
        "position": (2, 5),
        "level": 85,
        "prerequisites": ("repertoire-authority",),
    },
    {
        "id": "long-form",
        "kind": "talent",
        "identifier": "troubadour.long-form",
        "name": "Long Form",
        "description": "Combat songs last one additional turn.",
        "lane": "Mastery",
        "position": (3, 0),
        "available_on_promotion": True,
    },
    {
        "id": "road-tested",
        "kind": "talent",
        "identifier": "troubadour.road-tested",
        "name": "Road Tested",
        "description": "Exploration songs gain practice XP every 16 carried steps instead of every 20.",
        "lane": "Mastery",
        "position": (3, 1),
        "level": 65,
        "prerequisites": ("long-form",),
    },
    {
        "id": "endless-refrain",
        "kind": "talent",
        "identifier": "troubadour.endless-refrain",
        "name": "Endless Refrain",
        "description": "Exploration performances carry for 20 additional steps.",
        "lane": "Mastery",
        "position": (3, 2),
        "level": 70,
        "prerequisites": ("road-tested",),
    },
    {
        "id": "lasting-impression",
        "kind": "talent",
        "identifier": "troubadour.lasting-impression",
        "name": "Lasting Impression",
        "description": "Bones, Thugs, and Harmony's reduced route coda lasts 30 steps.",
        "lane": "Mastery",
        "position": (3, 3),
        "level": 75,
        "prerequisites": ("endless-refrain",),
    },
    {
        "id": "prismatic-finale",
        "kind": "ability",
        "identifier": "PrismaticFinale",
        "lane": "Mastery",
        "position": (3, 4),
        "level": 80,
        "prerequisites": ("lasting-impression",),
    },
    {
        "id": "virtuoso-repertoire",
        "kind": "talent",
        "identifier": "troubadour.virtuoso-repertoire",
        "name": "Virtuoso Repertoire",
        "description": "Starting a mastered advanced song immediately gains one Crescendo.",
        "lane": "Mastery",
        "position": (3, 5),
        "level": 85,
        "prerequisites": ("prismatic-finale",),
    },
    {
        "id": "countermelody",
        "kind": "ability",
        "identifier": "Countermelody",
        "lane": "Mastery",
        "position": (3, 6),
        "level": 85,
        "prerequisites": ("virtuoso-repertoire",),
    },
)

MONK_TREE_NODE_SPECS = (
    {
        "id": "unarmed-proficiency",
        "kind": "ability",
        "identifier": "UnarmedProficiency",
        "name": "Unarmed Proficiency",
        "lane": "Ki Assault",
        "position": (0, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "flowing-palm",
        "kind": "ability",
        "identifier": "FlowingPalm",
        "lane": "Ki Assault",
        "position": (0, 1),
        "level": 35,
        "prerequisites": ("unarmed-proficiency",),
    },
    {
        "id": "rhythmic-breathing",
        "kind": "talent",
        "identifier": "monk.rhythmic-breathing",
        "name": "Rhythmic Breathing",
        "description": "A qualifying martial hit at zero Ki gains two Ki instead of one.",
        "lane": "Ki Assault",
        "position": (0, 2),
        "level": 40,
        "prerequisites": ("flowing-palm",),
    },
    {
        "id": "disciplined-attack",
        "kind": "rating",
        "identifier": "Attack",
        "lane": "Ki Assault",
        "position": (0, 3),
        "level": 45,
        "level_band_gate": True,
        "prerequisites": ("rhythmic-breathing",),
    },
    {
        "id": "headbutt",
        "kind": "ability",
        "identifier": "Headbutt",
        "lane": "Ki Assault",
        "position": (0, 4),
        "level": 50,
        "owned_if_known": True,
        "prerequisites": ("disciplined-attack",),
    },
    {
        "id": "uppercut",
        "kind": "ability",
        "identifier": "Uppercut",
        "lane": "Ki Assault",
        "position": (0, 5),
        "level": 55,
        "owned_if_known": True,
        "prerequisites": ("headbutt",),
    },
    {
        "id": "chi-heal",
        "kind": "ability",
        "identifier": "ChiHeal",
        "lane": "Ki Discipline",
        "position": (1, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "disciplined-vitality",
        "kind": "health",
        "identifier": "Health",
        "lane": "Ki Discipline",
        "position": (1, 1),
        "level": 35,
        "level_band_gate": True,
        "prerequisites": ("chi-heal",),
    },
    {
        "id": "mirror-breath",
        "kind": "ability",
        "identifier": "MirrorBreath",
        "lane": "Ki Discipline",
        "position": (1, 2),
        "level": 40,
        "owned_if_known": True,
        "prerequisites": ("disciplined-vitality",),
    },
    {
        "id": "deep-restoration",
        "kind": "talent",
        "identifier": "monk.deep-restoration",
        "name": "Deep Restoration",
        "description": "Focused Chi Heal restores 30% additional healing instead of 20%.",
        "lane": "Ki Discipline",
        "position": (1, 3),
        "level": 45,
        "prerequisites": ("mirror-breath",),
    },
    {
        "id": "purging-kata",
        "kind": "ability",
        "identifier": "PurgingKata",
        "lane": "Ki Discipline",
        "position": (1, 4),
        "level": 50,
        "owned_if_known": True,
        "prerequisites": ("deep-restoration",),
    },
    {
        "id": "mirror-stillness",
        "kind": "talent",
        "identifier": "monk.mirror-stillness",
        "name": "Mirror Stillness",
        "description": "Mirror Breath lasts three turns instead of two.",
        "lane": "Ki Discipline",
        "position": (1, 5),
        "level": 55,
        "prerequisites": ("purging-kata",),
    },
    {
        "id": "purity-body",
        "kind": "ability",
        "identifier": "PurityBody",
        "lane": "Centering",
        "position": (2, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "centered-guard",
        "kind": "ability",
        "identifier": "CenteredGuard",
        "lane": "Centering",
        "position": (2, 1),
        "level": 35,
        "owned_if_known": True,
        "prerequisites": ("purity-body",),
    },
    {
        "id": "centered-defense",
        "kind": "rating",
        "identifier": "Defense",
        "lane": "Centering",
        "position": (2, 2),
        "level": 40,
        "level_band_gate": True,
        "prerequisites": ("centered-guard",),
    },
    {
        "id": "steadfast-center",
        "kind": "talent",
        "identifier": "monk.steadfast-center",
        "name": "Steadfast Center",
        "description": "Centered Guard lasts three turns instead of two.",
        "lane": "Centering",
        "position": (2, 3),
        "level": 45,
        "prerequisites": ("centered-defense",),
    },
    {
        "id": "reactive-center",
        "kind": "talent",
        "identifier": "monk.reactive-center",
        "name": "Reactive Center",
        "description": "A successful dodge or parry gains two Ki instead of one.",
        "lane": "Centering",
        "position": (2, 4),
        "level": 50,
        "prerequisites": ("steadfast-center",),
    },
    {
        "id": "guarded-purity",
        "kind": "talent",
        "identifier": "monk.guarded-purity",
        "name": "Guarded Purity",
        "description": "Centered Guard also grants two turns of hostile-status immunity.",
        "lane": "Centering",
        "position": (2, 5),
        "level": 55,
        "prerequisites": ("reactive-center",),
    },
    {
        "id": "leg-sweep",
        "kind": "ability",
        "identifier": "LegSweep",
        "lane": "Open Hand",
        "position": (3, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "double-strike",
        "kind": "ability",
        "identifier": "DoubleStrike",
        "lane": "Open Hand",
        "position": (3, 1),
        "level": 35,
        "owned_if_known": True,
        "prerequisites": ("leg-sweep",),
    },
    {
        "id": "parry",
        "kind": "ability",
        "identifier": "Parry",
        "lane": "Open Hand",
        "position": (3, 2),
        "level": 40,
        "owned_if_known": True,
        "prerequisites": ("double-strike",),
    },
    {
        "id": "drunken-brawler",
        "kind": "ability",
        "identifier": "DrunkenBrawler",
        "lane": "Open Hand",
        "position": (3, 3),
        "level": 45,
        "owned_if_known": True,
        "prerequisites": ("parry",),
    },
    {
        "id": "true-strike",
        "kind": "ability",
        "identifier": "TrueStrike",
        "lane": "Open Hand",
        "position": (3, 4),
        "level": 50,
        "owned_if_known": True,
        "prerequisites": ("drunken-brawler",),
    },
)


MASTER_MONK_TREE_NODE_SPECS = (
    {
        "id": "hyakuretsukyaku",
        "kind": "ability",
        "identifier": "Hyakuretsukyaku",
        "lane": "Perfected Flurry",
        "position": (0, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "hundredfold-precision",
        "kind": "talent",
        "identifier": "master-monk.hundredfold-precision",
        "name": "Hundredfold Precision",
        "description": "A Ki-empowered Hyakuretsukyaku gains 15 accuracy points per hit instead of 10.",
        "lane": "Perfected Flurry",
        "position": (0, 1),
        "level": 65,
        "prerequisites": ("hyakuretsukyaku",),
    },
    {
        "id": "triple-strike",
        "kind": "ability",
        "identifier": "TripleStrike",
        "lane": "Perfected Flurry",
        "position": (0, 2),
        "level": 70,
        "owned_if_known": True,
        "upgrade_without_source": True,
        "prerequisites": ("hundredfold-precision",),
    },
    {
        "id": "perfect-control",
        "kind": "talent",
        "identifier": "master-monk.perfect-control",
        "name": "Perfect Control",
        "description": "Ki control riders gain 25 percentage points of reliability instead of 15.",
        "lane": "Perfected Flurry",
        "position": (0, 3),
        "level": 75,
        "prerequisites": ("triple-strike",),
    },
    {
        "id": "spinning-back-elbow",
        "kind": "ability",
        "identifier": "SpinningBackElbow",
        "lane": "Perfected Flurry",
        "position": (0, 4),
        "level": 80,
        "owned_if_known": True,
        "prerequisites": ("perfect-control",),
    },
    {
        "id": "perfected-restoration",
        "kind": "talent",
        "identifier": "master-monk.perfected-restoration",
        "name": "Perfected Restoration",
        "description": "Focused Chi Heal restores a further 15% additional healing.",
        "lane": "Perfected Flurry",
        "position": (0, 5),
        "level": 85,
        "prerequisites": ("spinning-back-elbow",),
    },
    {
        "id": "purity-without-end",
        "kind": "talent",
        "identifier": "master-monk.purity-without-end",
        "name": "Purity Without End",
        "description": "Focused Chi Heal extends hostile-status immunity by one turn.",
        "lane": "Perfected Flurry",
        "position": (0, 6),
        "level": 90,
        "prerequisites": ("perfected-restoration",),
    },
    {
        "id": "hadouken",
        "kind": "ability",
        "identifier": "Hadouken",
        "lane": "Final Art",
        "position": (1, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "suplex",
        "kind": "ability",
        "identifier": "Suplex",
        "lane": "Final Art",
        "position": (1, 1),
        "level": 70,
        "owned_if_known": True,
        "prerequisites": ("hadouken",),
    },
    {
        "id": "evasion",
        "kind": "ability",
        "identifier": "Evasion",
        "lane": "Diamond Body",
        "position": (2, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "empty-fortress",
        "kind": "talent",
        "identifier": "master-monk.empty-fortress",
        "name": "Empty Fortress",
        "description": "Reduce incoming damage by 10% while unarmed and unarmored.",
        "lane": "Diamond Body",
        "position": (2, 1),
        "level": 65,
        "prerequisites": ("evasion",),
    },
    {
        "id": "purity-body-2",
        "kind": "ability",
        "identifier": "PurityBody2",
        "name": "Purity Body II",
        "lane": "Diamond Body",
        "position": (2, 2),
        "level": 70,
        "owned_if_known": True,
        "upgrade_without_source": True,
        "prerequisites": ("empty-fortress",),
    },
    {
        "id": "reflecting-soul",
        "kind": "talent",
        "identifier": "master-monk.reflecting-soul",
        "name": "Reflecting Soul",
        "description": "Inherited Mirror Breath lasts one additional turn.",
        "lane": "Diamond Body",
        "position": (2, 3),
        "level": 75,
        "prerequisites": ("purity-body-2",),
    },
    {
        "id": "rooted-recovery",
        "kind": "talent",
        "identifier": "master-monk.rooted-recovery",
        "name": "Rooted Recovery",
        "description": "Successful dodge and parry reactions gain one additional Ki.",
        "lane": "Diamond Body",
        "position": (2, 4),
        "level": 80,
        "prerequisites": ("reflecting-soul",),
    },
    {
        "id": "martial-mastery",
        "kind": "ability",
        "identifier": "MartialMastery",
        "lane": "Rope-a-Dope",
        "position": (3, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "rope-a-dope",
        "kind": "ability",
        "identifier": "RopeADope",
        "name": "Rope-a-Dope",
        "lane": "Rope-a-Dope",
        "position": (3, 1),
        "level": 65,
        "cost": 2,
        "prerequisites": ("martial-mastery",),
    },
    {
        "id": "goading-smile",
        "kind": "talent",
        "identifier": "master-monk.goading-smile",
        "name": "Goading Smile",
        "description": "Rope-a-Dope's Berserk challenge chance rises from 50% to 75%.",
        "lane": "Rope-a-Dope",
        "position": (3, 2),
        "level": 70,
        "prerequisites": ("rope-a-dope",),
    },
    {
        "id": "slip-the-rope",
        "kind": "talent",
        "identifier": "master-monk.slip-the-rope",
        "name": "Slip the Rope",
        "description": "Rope-a-Dope begins with 15 dodge points instead of 10.",
        "lane": "Rope-a-Dope",
        "position": (3, 3),
        "level": 75,
        "prerequisites": ("goading-smile",),
    },
    {
        "id": "rolling-shoulders",
        "kind": "talent",
        "identifier": "master-monk.rolling-shoulders",
        "name": "Rolling Shoulders",
        "description": "Each consecutive Rope-a-Dope dodge adds seven dodge points instead of five.",
        "lane": "Rope-a-Dope",
        "position": (3, 4),
        "level": 80,
        "prerequisites": ("slip-the-rope",),
    },
    {
        "id": "championship-round",
        "kind": "talent",
        "identifier": "master-monk.championship-round",
        "name": "Championship Round",
        "description": "Increase each hit of the Rope-a-Dope combination by 10% weapon damage.",
        "lane": "Rope-a-Dope",
        "position": (3, 5),
        "level": 85,
        "prerequisites": ("rolling-shoulders",),
    },
    {
        "id": "second-wind",
        "kind": "talent",
        "identifier": "master-monk.second-wind",
        "name": "Second Wind",
        "description": "Completing the Rope-a-Dope combination restores 10% maximum HP.",
        "lane": "Rope-a-Dope",
        "position": (3, 6),
        "level": 90,
        "prerequisites": ("championship-round",),
    },
    {
        "id": "decisive-pressure",
        "kind": "talent",
        "identifier": "master-monk.decisive-pressure",
        "name": "Decisive Pressure",
        "description": "Dim Mak gains 15% damage per spent Ki instead of 12%.",
        "lane": "Dim Mak Mastery",
        "position": (4, 0),
        "level": 65,
        "prerequisites": ("hadouken",),
    },
    {
        "id": "death-point-focus",
        "kind": "talent",
        "identifier": "master-monk.death-point-focus",
        "name": "Death-Point Focus",
        "description": "Dim Mak gains 10 additional accuracy points.",
        "lane": "Dim Mak Mastery",
        "position": (4, 1),
        "level": 75,
        "prerequisites": ("suplex",),
    },
    {
        "id": "flexible-form",
        "kind": "talent",
        "identifier": "master-monk.flexible-form",
        "name": "Flexible Form",
        "description": "An ordinary staff retains 90% of Dim Mak's power instead of 80%.",
        "lane": "Dim Mak Mastery",
        "position": (4, 2),
        "level": 85,
        "prerequisites": ("suplex",),
    },
    {
        "id": "essence-mastery",
        "kind": "talent",
        "identifier": "master-monk.essence-mastery",
        "name": "Essence Mastery",
        "description": "A lethal Dim Mak restores 125% of the target's maximum HP and MP, still capped by your maxima.",
        "lane": "Dim Mak Mastery",
        "position": (4, 3),
        "level": 90,
        "prerequisites": ("suplex",),
    },
    {
        "id": "inner-reserve",
        "kind": "talent",
        "identifier": "master-monk.inner-reserve",
        "name": "Inner Reserve",
        "description": "A damaging Dim Mak can trigger its once-per-combat Ki refund without an awakened ring.",
        "lane": "Dim Mak Mastery",
        "position": (4, 4),
        "level": 85,
        "prerequisites": ("rooted-recovery",),
    },
    {
        "id": "perfect-recovery",
        "kind": "talent",
        "identifier": "master-monk.perfect-recovery",
        "name": "Perfect Recovery",
        "description": "When Martial Master or Inner Reserve enables Dim Mak's once-per-combat Ki refund, it restores two Ki instead of one.",
        "lane": "Dim Mak Mastery",
        "position": (4, 5),
        "level": 90,
        "prerequisites": ("rooted-recovery",),
    },
)


PRIEST_TREE_NODE_SPECS = (
    {
        "id": "supplication",
        "kind": "ability",
        "identifier": "Supplication",
        "lane": "Prayer",
        "position": (0, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "deliberate-prayer",
        "kind": "talent",
        "identifier": "priest.deliberate-prayer",
        "name": "Deliberate Prayer",
        "description": "A qualifying direct support action gains two Prayer instead of one.",
        "lane": "Prayer",
        "position": (0, 1),
        "level": 35,
        "prerequisites": ("supplication",),
    },
    {
        "id": "holy-2",
        "kind": "ability",
        "identifier": "Holy2",
        "name": "Holy II",
        "lane": "Prayer",
        "position": (0, 2),
        "level": 40,
        "owned_if_known": True,
        "upgrade_without_source": True,
        "prerequisites": ("deliberate-prayer",),
    },
    {
        "id": "dazed-or-confused",
        "kind": "ability",
        "identifier": "DazedOrConfused",
        "name": "Dazed or Confused",
        "lane": "Prayer",
        "position": (0, 3),
        "level": 45,
        "prerequisites": ("holy-2",),
    },
    {
        "id": "prayer-potency",
        "kind": "rating",
        "identifier": "Magic",
        "lane": "Prayer",
        "position": (0, 4),
        "level": 50,
        "level_band_gate": True,
        "prerequisites": ("dazed-or-confused",),
    },
    {
        "id": "holy-disorientation",
        "kind": "talent",
        "identifier": "priest.holy-disorientation",
        "name": "Holy Disorientation",
        "description": "Dazed or Confused's Stun chance rises from 25% to 35%.",
        "lane": "Prayer",
        "position": (0, 5),
        "level": 55,
        "prerequisites": ("prayer-potency",),
    },
    {
        "id": "dispel",
        "kind": "ability",
        "identifier": "Dispel",
        "lane": "Exorcism",
        "position": (1, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "expel-curse",
        "kind": "ability",
        "identifier": "ExpelCurse",
        "name": "Expel Curse",
        "lane": "Exorcism",
        "position": (1, 1),
        "level": 35,
        "owned_if_known": True,
        "prerequisites": ("dispel",),
    },
    {
        "id": "exorcists-ward",
        "kind": "rating",
        "identifier": "Magic Defense",
        "lane": "Exorcism",
        "position": (1, 2),
        "level": 40,
        "level_band_gate": True,
        "prerequisites": ("expel-curse",),
    },
    {
        "id": "berserk",
        "kind": "ability",
        "identifier": "Berserk",
        "lane": "Exorcism",
        "position": (1, 3),
        "level": 45,
        "owned_if_known": True,
        "prerequisites": ("exorcists-ward",),
    },
    {
        "id": "fervent-supplication",
        "kind": "talent",
        "identifier": "priest.fervent-supplication",
        "name": "Fervent Supplication",
        "description": "Supplication's healing increases by 15%.",
        "lane": "Exorcism",
        "position": (1, 5),
        "level": 55,
        "prerequisites": ("berserk",),
    },
    {
        "id": "defensive-regen",
        "kind": "ability",
        "identifier": "DefensiveRegen",
        "lane": "Grace",
        "position": (2, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "regen-2",
        "kind": "ability",
        "identifier": "Regen2",
        "name": "Regen II",
        "lane": "Grace",
        "position": (2, 1),
        "level": 35,
        "owned_if_known": True,
        "upgrade_without_source": True,
        "prerequisites": ("defensive-regen",),
    },
    {
        "id": "magical-invigoration",
        "kind": "ability",
        "identifier": "MagicalInvigoration",
        "name": "Magical Invigoration",
        "lane": "Grace",
        "position": (2, 2),
        "level": 40,
        "prerequisites": ("regen-2",),
    },
    {
        "id": "long-regeneration",
        "kind": "talent",
        "identifier": "priest.long-regeneration",
        "name": "Long Regeneration",
        "description": "Magical Invigoration stacks last one additional turn.",
        "lane": "Grace",
        "position": (2, 3),
        "level": 45,
        "prerequisites": ("magical-invigoration",),
    },
    {
        "id": "arcane-renewal",
        "kind": "talent",
        "identifier": "priest.arcane-renewal",
        "name": "Arcane Renewal",
        "description": "Each Magical Invigoration stack grants six Magic instead of four.",
        "lane": "Grace",
        "position": (2, 5),
        "level": 55,
        "prerequisites": ("long-regeneration",),
    },
    {
        "id": "mana-shield",
        "kind": "ability",
        "identifier": "ManaShield",
        "lane": "Protection",
        "position": (3, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "shell",
        "kind": "ability",
        "identifier": "Shell",
        "lane": "Protection",
        "position": (3, 1),
        "level": 35,
        "owned_if_known": True,
        "prerequisites": ("mana-shield",),
    },
    {
        "id": "cleanse",
        "kind": "ability",
        "identifier": "Cleanse",
        "lane": "Protection",
        "position": (3, 2),
        "level": 40,
        "owned_if_known": True,
        "prerequisites": ("shell",),
    },
    {
        "id": "bless",
        "kind": "ability",
        "identifier": "Bless",
        "lane": "Protection",
        "position": (3, 3),
        "level": 45,
        "owned_if_known": True,
        "prerequisites": ("cleanse",),
    },
    {
        "id": "sheltering-prayer",
        "kind": "talent",
        "identifier": "priest.sheltering-prayer",
        "name": "Sheltering Prayer",
        "description": "Supplication's ward lasts one additional turn.",
        "lane": "Protection",
        "position": (3, 4),
        "level": 50,
        "prerequisites": ("bless",),
    },
    {
        "id": "merciful-prayer",
        "kind": "talent",
        "identifier": "priest.merciful-prayer",
        "name": "Merciful Prayer",
        "description": "Supplication gains 15 percentage points of cleanse chance.",
        "lane": "Protection",
        "position": (3, 5),
        "level": 55,
        "prerequisites": ("sheltering-prayer",),
    },
)


ARCHBISHOP_TREE_NODE_SPECS = (
    {
        "id": "great-benediction",
        "kind": "ability",
        "identifier": "GreatBenediction",
        "lane": "Benediction",
        "position": (0, 0),
        "cost": 2,
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "ready-benediction",
        "kind": "talent",
        "identifier": "archbishop.ready-benediction",
        "name": "Ready Benediction",
        "description": "Great Benediction can be cast with two Prayer instead of three.",
        "lane": "Benediction",
        "position": (0, 1),
        "level": 65,
        "prerequisites": ("great-benediction",),
    },
    {
        "id": "greater-benediction",
        "kind": "talent",
        "identifier": "archbishop.greater-benediction",
        "name": "Greater Benediction",
        "description": "Great Benediction's Prayer scaling increases by 15%.",
        "lane": "Benediction",
        "position": (0, 2),
        "level": 70,
        "prerequisites": ("ready-benediction",),
    },
    {
        "id": "lasting-benediction",
        "kind": "talent",
        "identifier": "archbishop.lasting-benediction",
        "name": "Lasting Benediction",
        "description": "Great Benediction lasts one additional turn.",
        "lane": "Benediction",
        "position": (0, 3),
        "level": 75,
        "prerequisites": ("greater-benediction",),
    },
    {
        "id": "benediction-aegis",
        "kind": "talent",
        "identifier": "archbishop.benediction-aegis",
        "name": "Benediction Aegis",
        "description": "Great Benediction grants five Magic Defense per Prayer instead of four.",
        "lane": "Benediction",
        "position": (0, 4),
        "level": 80,
        "prerequisites": ("lasting-benediction",),
    },
    {
        "id": "healing-liturgy",
        "kind": "talent",
        "identifier": "archbishop.healing-liturgy",
        "name": "Healing Liturgy",
        "description": "Great Benediction gains one percentage point more healing per Prayer.",
        "lane": "Benediction",
        "position": (0, 5),
        "level": 85,
        "prerequisites": ("benediction-aegis",),
    },
    {
        "id": "mana-liturgy",
        "kind": "talent",
        "identifier": "archbishop.mana-liturgy",
        "name": "Mana Liturgy",
        "description": "Great Benediction restores one MP per two Prayer instead of per three.",
        "lane": "Benediction",
        "position": (0, 6),
        "level": 90,
        "prerequisites": ("healing-liturgy",),
    },
    {
        "id": "doublecast",
        "kind": "ability",
        "identifier": "Doublecast",
        "lane": "Great Gospel",
        "position": (1, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "holy-3",
        "kind": "ability",
        "identifier": "Holy3",
        "name": "Holy III",
        "lane": "Great Gospel",
        "position": (1, 1),
        "level": 65,
        "owned_if_known": True,
        "upgrade_without_source": True,
        "prerequisites": ("doublecast",),
    },
    {
        "id": "silence",
        "kind": "ability",
        "identifier": "Silence",
        "lane": "Great Gospel",
        "position": (1, 2),
        "level": 70,
        "owned_if_known": True,
        "prerequisites": ("holy-3",),
    },
    {
        "id": "mana-shield-2",
        "kind": "ability",
        "identifier": "ManaShield2",
        "name": "Mana Shield II",
        "lane": "Great Gospel",
        "position": (1, 3),
        "level": 75,
        "owned_if_known": True,
        "upgrade_without_source": True,
        "prerequisites": ("silence",),
    },
    {
        "id": "first-words",
        "kind": "talent",
        "identifier": "archbishop.first-words",
        "name": "First Words",
        "description": "The first qualifying Prayer source from zero grants one additional Prayer.",
        "lane": "Great Gospel",
        "position": (1, 4),
        "level": 80,
        "prerequisites": ("mana-shield-2",),
    },
    {
        "id": "opening-gospel",
        "kind": "talent",
        "identifier": "archbishop.opening-gospel",
        "name": "Opening Gospel",
        "description": "Great Gospel raises Prayer to at least 75% of capacity instead of half.",
        "lane": "Great Gospel",
        "position": (1, 6),
        "level": 90,
        "prerequisites": ("first-words",),
    },
    {
        "id": "heal-3",
        "kind": "ability",
        "identifier": "Heal3",
        "name": "Heal III",
        "lane": "Intervention",
        "position": (2, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
        "upgrade_without_source": True,
    },
    {
        "id": "resurrection",
        "kind": "ability",
        "identifier": "Resurrection",
        "lane": "Intervention",
        "position": (2, 1),
        "level": 65,
        "cost": 2,
        "owned_if_known": True,
        "prerequisites": ("heal-3",),
    },
    {
        "id": "expel-curse",
        "kind": "ability",
        "identifier": "ExpelCurse",
        "name": "Expel Curse",
        "lane": "Intervention",
        "position": (2, 2),
        "level": 70,
        "owned_if_known": True,
        "prerequisites": ("resurrection",),
    },
    {
        "id": "swift-exorcism",
        "kind": "talent",
        "identifier": "archbishop.swift-exorcism",
        "name": "Swift Exorcism",
        "description": "Reduce Expel Curse's MP cost by six.",
        "lane": "Intervention",
        "position": (2, 6),
        "level": 90,
        "prerequisites": ("expel-curse",),
    },
    {
        "id": "regen-3",
        "kind": "ability",
        "identifier": "Regen3",
        "name": "Regen III",
        "lane": "Sustaining Grace",
        "position": (3, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
        "upgrade_without_source": True,
    },
    {
        "id": "enduring-invigoration",
        "kind": "talent",
        "identifier": "archbishop.enduring-invigoration",
        "name": "Enduring Invigoration",
        "description": "Magical Invigoration stacks last one additional turn.",
        "lane": "Sustaining Grace",
        "position": (3, 1),
        "level": 65,
        "prerequisites": ("regen-3",),
    },
    {
        "id": "radiant-renewal",
        "kind": "talent",
        "identifier": "archbishop.radiant-renewal",
        "name": "Radiant Renewal",
        "description": "Magical Invigoration stacks grant two additional Magic.",
        "lane": "Sustaining Grace",
        "position": (3, 2),
        "level": 70,
        "prerequisites": ("enduring-invigoration",),
    },
    {
        "id": "unshaken-congregation",
        "kind": "talent",
        "identifier": "archbishop.unshaken-congregation",
        "name": "Unshaken Congregation",
        "description": "Great Benediction gains two percentage points more status resistance per Prayer.",
        "lane": "Sustaining Grace",
        "position": (3, 3),
        "level": 75,
        "prerequisites": ("radiant-renewal",),
    },
    {
        "id": "protective-liturgy",
        "kind": "talent",
        "identifier": "archbishop.protective-liturgy",
        "name": "Protective Liturgy",
        "description": "Great Benediction prevents an additional half percentage point of damage per Prayer.",
        "lane": "Sustaining Grace",
        "position": (3, 5),
        "level": 85,
        "prerequisites": ("unshaken-congregation",),
    },
    {
        "id": "abundant-mercy",
        "kind": "talent",
        "identifier": "archbishop.abundant-mercy",
        "name": "Abundant Mercy",
        "description": "Supplication's healing scaling increases by 20%.",
        "lane": "Perfect Supplication",
        "position": (4, 0),
        "available_on_promotion": True,
    },
    {
        "id": "sheltering-word",
        "kind": "talent",
        "identifier": "archbishop.sheltering-word",
        "name": "Sheltering Word",
        "description": "Supplication grants eight ward points per Prayer instead of six.",
        "lane": "Perfect Supplication",
        "position": (4, 1),
        "level": 65,
        "prerequisites": ("abundant-mercy",),
    },
    {
        "id": "purifying-word",
        "kind": "talent",
        "identifier": "archbishop.purifying-word",
        "name": "Purifying Word",
        "description": "Supplication gains 20 percentage points of cleanse chance.",
        "lane": "Perfect Supplication",
        "position": (4, 2),
        "level": 70,
        "prerequisites": ("sheltering-word",),
    },
    {
        "id": "endless-supplication",
        "kind": "talent",
        "identifier": "archbishop.endless-supplication",
        "name": "Endless Supplication",
        "description": "Supplication restores one Prayer after resolving.",
        "lane": "Perfect Supplication",
        "position": (4, 3),
        "level": 75,
        "prerequisites": ("purifying-word",),
    },
    {
        "id": "overwhelming-light",
        "kind": "talent",
        "identifier": "archbishop.overwhelming-light",
        "name": "Overwhelming Light",
        "description": "Dazed or Confused's secondary confusion chance rises to 40%.",
        "lane": "Perfect Supplication",
        "position": (4, 5),
        "level": 85,
        "prerequisites": ("endless-supplication",),
    },
    {
        "id": "assured-intervention",
        "kind": "talent",
        "identifier": "archbishop.assured-intervention",
        "name": "Assured Intervention",
        "description": "Awakened Divine Intervention's rescue chance rises from 35% to 50%.",
        "lane": "Divine Intervention",
        "position": (5, 3),
        "level": 75,
        "prerequisites": ("expel-curse",),
    },
    {
        "id": "miraculous-recovery",
        "kind": "talent",
        "identifier": "archbishop.miraculous-recovery",
        "name": "Miraculous Recovery",
        "description": "Successful awakened Divine Intervention restores 35% maximum HP instead of 25%.",
        "lane": "Divine Intervention",
        "position": (5, 4),
        "level": 80,
        "prerequisites": ("expel-curse",),
    },
)

CLERIC_TREE_NODE_SPECS = (
    {
        "id": "sanctuary-ward",
        "kind": "ability",
        "identifier": "SanctuaryWard",
        "lane": "Devotion",
        "position": (0, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "held-faith",
        "kind": "talent",
        "identifier": "cleric.held-faith",
        "name": "Held Faith",
        "description": "Each held Devotion reduces incoming damage by 4% instead of 3%.",
        "lane": "Devotion",
        "position": (0, 1),
        "level": 35,
        "prerequisites": ("sanctuary-ward",),
    },
    {
        "id": "bless",
        "kind": "ability",
        "identifier": "Bless",
        "lane": "Devotion",
        "position": (0, 2),
        "level": 40,
        "owned_if_known": True,
        "prerequisites": ("held-faith",),
    },
    {
        "id": "devotional-attack",
        "kind": "rating",
        "identifier": "Attack",
        "lane": "Devotion",
        "position": (0, 3),
        "level": 45,
        "level_band_gate": True,
        "prerequisites": ("bless",),
    },
    {
        "id": "lasting-sanctuary",
        "kind": "talent",
        "identifier": "cleric.lasting-sanctuary",
        "name": "Lasting Sanctuary",
        "description": "Sanctuary Ward lasts one additional turn.",
        "lane": "Devotion",
        "position": (0, 4),
        "level": 50,
        "prerequisites": ("devotional-attack",),
    },
    {
        "id": "pious-bounty",
        "kind": "ability",
        "identifier": "PiousBounty",
        "lane": "Devotion",
        "position": (0, 5),
        "level": 55,
        "owned_if_known": True,
        "prerequisites": ("lasting-sanctuary",),
    },
    {
        "id": "smite",
        "kind": "ability",
        "identifier": "Smite",
        "lane": "Sacred Office",
        "position": (1, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "smite-2",
        "kind": "ability",
        "identifier": "Smite2",
        "name": "Smite II",
        "lane": "Sacred Office",
        "position": (1, 1),
        "level": 35,
        "owned_if_known": True,
        "prerequisites": ("smite",),
        "upgrade_without_source": True,
    },
    {
        "id": "turn-undead-2",
        "kind": "ability",
        "identifier": "TurnUndead2",
        "name": "Turn Undead II",
        "lane": "Sacred Office",
        "position": (1, 2),
        "level": 40,
        "owned_if_known": True,
        "prerequisites": ("smite-2",),
        "upgrade_without_source": True,
    },
    {
        "id": "cleanse",
        "kind": "ability",
        "identifier": "Cleanse",
        "lane": "Sacred Office",
        "position": (1, 3),
        "level": 45,
        "owned_if_known": True,
        "prerequisites": ("turn-undead-2",),
    },
    {
        "id": "overflowing-grace",
        "kind": "talent",
        "identifier": "cleric.overflowing-grace",
        "name": "Overflowing Grace",
        "description": "Increase maximum Devotion by one.",
        "lane": "Sacred Office",
        "position": (1, 5),
        "level": 55,
        "prerequisites": ("cleanse",),
        "kit_effect": ("meter_cap", "devotion", 1),
    },
    {
        "id": "shield-slam",
        "kind": "ability",
        "identifier": "ShieldSlam",
        "lane": "Bulwark",
        "position": (2, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "shield-block",
        "kind": "ability",
        "identifier": "ShieldBlock",
        "lane": "Bulwark",
        "position": (2, 1),
        "level": 35,
        "owned_if_known": True,
        "prerequisites": ("shield-slam",),
    },
    {
        "id": "bastion-prayer",
        "kind": "ability",
        "identifier": "BastionPrayer",
        "lane": "Bulwark",
        "position": (2, 2),
        "level": 40,
        "prerequisites": ("shield-block",),
    },
    {
        "id": "bulwark-defense",
        "kind": "rating",
        "identifier": "Defense",
        "lane": "Bulwark",
        "position": (2, 3),
        "level": 45,
        "level_band_gate": True,
        "prerequisites": ("bastion-prayer",),
    },
    {
        "id": "shield-litany",
        "kind": "talent",
        "identifier": "cleric.shield-litany",
        "name": "Shield Litany",
        "description": "A successful shield block grants two Devotion instead of one.",
        "lane": "Bulwark",
        "position": (2, 4),
        "level": 50,
        "prerequisites": ("bulwark-defense",),
    },
    {
        "id": "bastion-practice",
        "kind": "talent",
        "identifier": "cleric.bastion-practice",
        "name": "Bastion Practice",
        "description": "Bastion Prayer raises both defenses by 10 instead of 7.",
        "lane": "Bulwark",
        "position": (2, 5),
        "level": 55,
        "prerequisites": ("shield-litany",),
    },
    {
        "id": "true-strike",
        "kind": "ability",
        "identifier": "TrueStrike",
        "lane": "Judgment",
        "position": (3, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "devotional-rebuke",
        "kind": "ability",
        "identifier": "DevotionalRebuke",
        "lane": "Judgment",
        "position": (3, 1),
        "level": 35,
        "prerequisites": ("true-strike",),
    },
    {
        "id": "measured-judgment",
        "kind": "talent",
        "identifier": "cleric.measured-judgment",
        "name": "Measured Judgment",
        "description": "Devotional Rebuke deals 25% more Holy damage.",
        "lane": "Judgment",
        "position": (3, 2),
        "level": 40,
        "prerequisites": ("devotional-rebuke",),
    },
    {
        "id": "silence",
        "kind": "ability",
        "identifier": "Silence",
        "lane": "Judgment",
        "position": (3, 3),
        "level": 45,
        "owned_if_known": True,
        "prerequisites": ("measured-judgment",),
    },
    {
        "id": "consecrated-blows",
        "kind": "talent",
        "identifier": "cleric.consecrated-blows",
        "name": "Consecrated Blows",
        "description": "Successful Holy pressure grants one additional Devotion once per action.",
        "lane": "Judgment",
        "position": (3, 5),
        "level": 55,
        "prerequisites": ("silence",),
    },
    {
        "id": "sacred-mending",
        "kind": "ability",
        "identifier": "SacredMending",
        "lane": "Shared Ministry",
        "position": (4, 0),
        "available_on_promotion": True,
    },
    {
        "id": "open-ministry",
        "kind": "talent",
        "identifier": "cleric.open-ministry",
        "name": "Open Ministry",
        "description": "Sacred Mending restores 25% more health.",
        "lane": "Shared Ministry",
        "position": (4, 1),
        "level": 35,
        "prerequisites": ("sacred-mending",),
    },
    {
        "id": "hallowed-readiness",
        "kind": "ability",
        "identifier": "HallowedReadiness",
        "lane": "Shared Ministry",
        "position": (4, 3),
        "level": 45,
        "prerequisites": ("open-ministry",),
    },
    {
        "id": "common-purpose",
        "kind": "talent",
        "identifier": "cleric.common-purpose",
        "name": "Common Purpose",
        "description": "Hallowed Readiness raises both defenses by 12 instead of 8 and lasts an additional turn.",
        "lane": "Shared Ministry",
        "position": (4, 5),
        "level": 55,
        "prerequisites": ("hallowed-readiness",),
    },
)


TEMPLAR_TREE_NODE_SPECS = (
    {
        "id": "relic-aegis",
        "kind": "ability",
        "identifier": "RelicAegis",
        "lane": "Relic Discipline",
        "position": (0, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "reinforced-relic",
        "kind": "talent",
        "identifier": "templar.reinforced-relic",
        "name": "Reinforced Relic",
        "description": "Increase Relic Aegis shielding and Holy counter damage by 25%.",
        "lane": "Relic Discipline",
        "position": (0, 1),
        "level": 65,
        "cost": 2,
        "prerequisites": ("relic-aegis",),
    },
    {
        "id": "shield-block",
        "kind": "ability",
        "identifier": "ShieldBlock",
        "lane": "Relic Discipline",
        "position": (0, 2),
        "level": 70,
        "owned_if_known": True,
        "prerequisites": ("reinforced-relic",),
    },
    {
        "id": "enduring-aegis",
        "kind": "talent",
        "identifier": "templar.enduring-aegis",
        "name": "Enduring Aegis",
        "description": "Relic Aegis and its Holy counter last one additional turn.",
        "lane": "Relic Discipline",
        "position": (0, 3),
        "level": 75,
        "prerequisites": ("shield-block",),
    },
    {
        "id": "last-stand",
        "kind": "ability",
        "identifier": "LastStand",
        "lane": "Relic Discipline",
        "position": (0, 4),
        "level": 80,
        "owned_if_known": True,
        "prerequisites": ("enduring-aegis",),
    },
    {
        "id": "last-line",
        "kind": "talent",
        "identifier": "templar.last-line",
        "name": "Last Line",
        "description": "Entering Last Stand grants one Devotion.",
        "lane": "Relic Discipline",
        "position": (0, 5),
        "level": 85,
        "prerequisites": ("last-stand",),
    },
    {
        "id": "unbroken-reliquary",
        "kind": "talent",
        "identifier": "templar.unbroken-reliquary",
        "name": "Unbroken Reliquary",
        "description": "Below half health, Relic Aegis is 25% stronger.",
        "lane": "Relic Discipline",
        "position": (0, 6),
        "level": 90,
        "prerequisites": ("last-line",),
    },
    {
        "id": "charge",
        "kind": "ability",
        "identifier": "Charge",
        "lane": "Vanguard",
        "position": (1, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "goad",
        "kind": "ability",
        "identifier": "Goad",
        "lane": "Vanguard",
        "position": (1, 1),
        "level": 65,
        "owned_if_known": True,
        "prerequisites": ("charge",),
    },
    {
        "id": "shield-slam",
        "kind": "ability",
        "identifier": "ShieldSlam",
        "lane": "Vanguard",
        "position": (1, 2),
        "level": 70,
        "owned_if_known": True,
        "prerequisites": ("goad",),
    },
    {
        "id": "parry",
        "kind": "ability",
        "identifier": "Parry",
        "lane": "Vanguard",
        "position": (1, 3),
        "level": 75,
        "owned_if_known": True,
        "prerequisites": ("shield-slam",),
    },
    {
        "id": "piercing-strike",
        "kind": "ability",
        "identifier": "PiercingStrike",
        "lane": "Vanguard",
        "position": (1, 4),
        "level": 80,
        "owned_if_known": True,
        "prerequisites": ("parry",),
    },
    {
        "id": "double-strike",
        "kind": "ability",
        "identifier": "DoubleStrike",
        "lane": "Vanguard",
        "position": (1, 5),
        "level": 85,
        "owned_if_known": True,
        "prerequisites": ("piercing-strike",),
    },
    {
        "id": "true-piercing-strike",
        "kind": "ability",
        "identifier": "TruePiercingStrike",
        "lane": "Vanguard",
        "position": (1, 6),
        "level": 90,
        "owned_if_known": True,
        "prerequisites": ("double-strike",),
    },
    {
        "id": "smite-3",
        "kind": "ability",
        "identifier": "Smite3",
        "name": "Smite III",
        "lane": "Sacred Rites",
        "position": (2, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
        "upgrade_without_source": True,
    },
    {
        "id": "regen-2",
        "kind": "ability",
        "identifier": "Regen2",
        "name": "Regen II",
        "lane": "Sacred Rites",
        "position": (2, 2),
        "level": 70,
        "owned_if_known": True,
        "prerequisites": ("smite-3",),
    },
    {
        "id": "bless",
        "kind": "ability",
        "identifier": "Bless",
        "lane": "Sacred Rites",
        "position": (2, 3),
        "level": 75,
        "owned_if_known": True,
        "prerequisites": ("regen-2",),
    },
    {
        "id": "dispel",
        "kind": "ability",
        "identifier": "Dispel",
        "lane": "Sacred Rites",
        "position": (2, 4),
        "level": 80,
        "owned_if_known": True,
        "prerequisites": ("bless",),
    },
    {
        "id": "devotional-rebuke",
        "kind": "ability",
        "identifier": "DevotionalRebuke",
        "lane": "Judgment",
        "position": (3, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "exacting-judgment",
        "kind": "talent",
        "identifier": "templar.exacting-judgment",
        "name": "Exacting Judgment",
        "description": "Devotional Rebuke deals 25% more Holy damage.",
        "lane": "Judgment",
        "position": (3, 1),
        "level": 65,
        "prerequisites": ("devotional-rebuke",),
    },
    {
        "id": "true-strike",
        "kind": "ability",
        "identifier": "TrueStrike",
        "lane": "Judgment",
        "position": (3, 2),
        "level": 70,
        "owned_if_known": True,
        "prerequisites": ("exacting-judgment",),
    },
    {
        "id": "holy-2",
        "kind": "ability",
        "identifier": "Holy2",
        "name": "Holy II",
        "lane": "Judgment",
        "position": (3, 3),
        "level": 75,
        "owned_if_known": True,
        "prerequisites": ("true-strike",),
    },
    {
        "id": "turn-undead-2",
        "kind": "ability",
        "identifier": "TurnUndead2",
        "name": "Turn Undead II",
        "lane": "Judgment",
        "position": (3, 4),
        "level": 80,
        "owned_if_known": True,
        "prerequisites": ("holy-2",),
    },
    {
        "id": "cleanse",
        "kind": "ability",
        "identifier": "Cleanse",
        "lane": "Judgment",
        "position": (3, 5),
        "level": 85,
        "owned_if_known": True,
        "prerequisites": ("turn-undead-2",),
    },
    {
        "id": "bastion-prayer",
        "kind": "ability",
        "identifier": "BastionPrayer",
        "lane": "Judgment",
        "position": (3, 6),
        "level": 90,
        "owned_if_known": True,
        "prerequisites": ("cleanse",),
    },
    {
        "id": "ordered-purpose",
        "kind": "talent",
        "identifier": "templar.ordered-purpose",
        "name": "Ordered Purpose",
        "description": "Awakened Ordered Blessings are 25% stronger and last one additional turn.",
        "lane": "Ordered Blessings",
        "position": (4, 1),
        "level": 65,
        "cost": 2,
        "prerequisites": ("smite-3",),
    },
    {
        "id": "liturgical-renewal",
        "kind": "talent",
        "identifier": "templar.liturgical-renewal",
        "name": "Liturgical Renewal",
        "description": "An awakened Ordered Blessing restores one MP per Devotion spent.",
        "lane": "Ordered Blessings",
        "position": (4, 5),
        "level": 85,
        "prerequisites": ("dispel",),
    },
    {
        "id": "perfect-order",
        "kind": "talent",
        "identifier": "templar.perfect-order",
        "name": "Perfect Order",
        "description": "Awakened Ordered Blessings also raise Magic Defense while active.",
        "lane": "Ordered Blessings",
        "position": (4, 6),
        "level": 90,
        "prerequisites": ("dispel",),
    },
)


HIEROPHANT_TREE_NODE_SPECS = (
    {
        "id": "staff-conduit",
        "kind": "ability",
        "identifier": "StaffConduit",
        "lane": "Consecrated Conduit",
        "position": (0, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "conduit-strike",
        "kind": "ability",
        "identifier": "ConduitStrike",
        "lane": "Consecrated Conduit",
        "position": (0, 1),
        "level": 65,
        "prerequisites": ("staff-conduit",),
    },
    {
        "id": "consecrated-conduit",
        "kind": "ability",
        "identifier": "ConsecratedConduit",
        "lane": "Consecrated Conduit",
        "position": (0, 2),
        "level": 70,
        "owned_if_known": True,
        "prerequisites": ("conduit-strike",),
    },
    {
        "id": "deep-conduit",
        "kind": "talent",
        "identifier": "hierophant.deep-conduit",
        "name": "Deep Conduit",
        "description": "Consecrated Conduit adds a further 8% Holy damage.",
        "lane": "Consecrated Conduit",
        "position": (0, 3),
        "level": 75,
        "cost": 2,
        "prerequisites": ("consecrated-conduit",),
    },
    {
        "id": "holy-2",
        "kind": "ability",
        "identifier": "Holy2",
        "name": "Holy II",
        "lane": "Consecrated Conduit",
        "position": (0, 4),
        "level": 80,
        "owned_if_known": True,
        "prerequisites": ("deep-conduit",),
    },
    {
        "id": "staff-ward",
        "kind": "talent",
        "identifier": "hierophant.staff-ward",
        "name": "Staff Ward",
        "description": "Consecrated Conduit's ward gains 50% more strength.",
        "lane": "Consecrated Conduit",
        "position": (0, 5),
        "level": 85,
        "prerequisites": ("holy-2",),
    },
    {
        "id": "radiant-return",
        "kind": "talent",
        "identifier": "hierophant.radiant-return",
        "name": "Radiant Return",
        "description": "Consecrated Conduit restores one MP per spent Devotion.",
        "lane": "Consecrated Conduit",
        "position": (0, 6),
        "level": 90,
        "prerequisites": ("staff-ward",),
    },
    {
        "id": "regen-2",
        "kind": "ability",
        "identifier": "Regen2",
        "name": "Regen II",
        "lane": "Devotional Grace",
        "position": (1, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "gentle-grace",
        "kind": "talent",
        "identifier": "hierophant.gentle-grace",
        "name": "Gentle Grace",
        "description": "Meaningful healing grants one additional Devotion once per action.",
        "lane": "Devotional Grace",
        "position": (1, 1),
        "level": 65,
        "cost": 2,
        "prerequisites": ("regen-2",),
    },
    {
        "id": "graceful-intercession",
        "kind": "ability",
        "identifier": "GracefulIntercession",
        "lane": "Devotional Grace",
        "position": (1, 2),
        "level": 70,
        "prerequisites": ("gentle-grace",),
    },
    {
        "id": "greater-intercession",
        "kind": "talent",
        "identifier": "hierophant.greater-intercession",
        "name": "Greater Intercession",
        "description": "Graceful Intercession is 35% stronger and its ward lasts one extra turn.",
        "lane": "Devotional Grace",
        "position": (1, 3),
        "level": 75,
        "prerequisites": ("graceful-intercession",),
    },
    {
        "id": "dispel",
        "kind": "ability",
        "identifier": "Dispel",
        "lane": "Devotional Grace",
        "position": (1, 4),
        "level": 80,
        "owned_if_known": True,
        "prerequisites": ("greater-intercession",),
    },
    {
        "id": "warded-faith",
        "kind": "talent",
        "identifier": "hierophant.warded-faith",
        "name": "Warded Faith",
        "description": "Each held Devotion reduces incoming damage by one additional percentage point.",
        "lane": "Devotional Grace",
        "position": (1, 5),
        "level": 85,
        "prerequisites": ("dispel",),
    },
    {
        "id": "abundant-grace",
        "kind": "talent",
        "identifier": "hierophant.abundant-grace",
        "name": "Abundant Grace",
        "description": "Increase maximum Devotion by one.",
        "lane": "Devotional Grace",
        "position": (1, 6),
        "level": 90,
        "prerequisites": ("warded-faith",),
        "kit_effect": ("meter_cap", "devotion", 1),
    },
    {
        "id": "smite-3",
        "kind": "ability",
        "identifier": "Smite3",
        "name": "Smite III",
        "lane": "Radiant Office",
        "position": (2, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
        "upgrade_without_source": True,
    },
    {
        "id": "luminous-doctrine",
        "kind": "talent",
        "identifier": "hierophant.luminous-doctrine",
        "name": "Luminous Doctrine",
        "description": "Successful Holy pressure grants one additional Devotion once per action.",
        "lane": "Radiant Office",
        "position": (2, 1),
        "level": 65,
        "prerequisites": ("smite-3",),
    },
    {
        "id": "resist-shadow",
        "kind": "ability",
        "identifier": "ResistShadow",
        "name": "Resist Shadow",
        "lane": "Radiant Office",
        "position": (2, 2),
        "level": 70,
        "owned_if_known": True,
        "prerequisites": ("luminous-doctrine",),
    },
    {
        "id": "devotional-rebuke",
        "kind": "ability",
        "identifier": "DevotionalRebuke",
        "lane": "Radiant Office",
        "position": (2, 3),
        "level": 75,
        "owned_if_known": True,
        "prerequisites": ("resist-shadow",),
    },
    {
        "id": "turn-undead-2",
        "kind": "ability",
        "identifier": "TurnUndead2",
        "name": "Turn Undead II",
        "lane": "Radiant Office",
        "position": (2, 4),
        "level": 80,
        "owned_if_known": True,
        "prerequisites": ("devotional-rebuke",),
    },
    {
        "id": "cleanse",
        "kind": "ability",
        "identifier": "Cleanse",
        "lane": "Radiant Office",
        "position": (2, 5),
        "level": 85,
        "owned_if_known": True,
        "prerequisites": ("turn-undead-2",),
    },
    {
        "id": "silence",
        "kind": "ability",
        "identifier": "Silence",
        "lane": "Radiant Office",
        "position": (2, 6),
        "level": 90,
        "owned_if_known": True,
        "prerequisites": ("cleanse",),
    },
    {
        "id": "heal-2",
        "kind": "ability",
        "identifier": "Heal2",
        "name": "Heal II",
        "lane": "Pastoral Office",
        "position": (3, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
        "upgrade_without_source": True,
    },
    {
        "id": "bless",
        "kind": "ability",
        "identifier": "Bless",
        "lane": "Pastoral Office",
        "position": (3, 1),
        "level": 65,
        "owned_if_known": True,
        "prerequisites": ("heal-2",),
    },
    {
        "id": "sanctuary-ward",
        "kind": "ability",
        "identifier": "SanctuaryWard",
        "lane": "Pastoral Office",
        "position": (3, 2),
        "level": 70,
        "owned_if_known": True,
        "prerequisites": ("bless",),
    },
    {
        "id": "shell",
        "kind": "ability",
        "identifier": "Shell",
        "lane": "Pastoral Office",
        "position": (3, 3),
        "level": 75,
        "owned_if_known": True,
        "prerequisites": ("sanctuary-ward",),
    },
    {
        "id": "reflect",
        "kind": "ability",
        "identifier": "Reflect",
        "lane": "Pastoral Office",
        "position": (3, 4),
        "level": 80,
        "owned_if_known": True,
        "prerequisites": ("shell",),
    },
    {
        "id": "merciful-ward",
        "kind": "talent",
        "identifier": "hierophant.merciful-ward",
        "name": "Merciful Ward",
        "description": "Meaningful direct healing raises a two-turn ward on its recipient.",
        "lane": "Pastoral Office",
        "position": (3, 5),
        "level": 85,
        "prerequisites": ("reflect",),
    },
    {
        "id": "bastion-prayer",
        "kind": "ability",
        "identifier": "BastionPrayer",
        "lane": "Pastoral Office",
        "position": (3, 6),
        "level": 90,
        "owned_if_known": True,
        "prerequisites": ("merciful-ward",),
    },
)
