"""Mage-line ability-tree declarations."""

from __future__ import annotations

# Mage is the second fully authored base tree. This is a pre-release content
# rebaseline: node IDs are stable within this graph, but retired experiments do
# not require save aliases or migrations.
MAGE_TREE_NODE_SPECS = (
    {
        "id": "mage.ability.firebolt",
        "kind": "ability",
        "identifier": "Firebolt",
        "lane": "Elementalism",
        "position": (0, 0),
    },
    {
        "id": "mage.ability.icelance",
        "kind": "ability",
        "identifier": "IceLance",
        "lane": "Elementalism",
        "position": (0, 1),
    },
    {
        "id": "mage.ability.shock",
        "kind": "ability",
        "identifier": "Shock",
        "lane": "Elementalism",
        "position": (0, 2),
    },
    {
        "id": "mage.ability.gust",
        "kind": "ability",
        "identifier": "Gust",
        "lane": "Elementalism",
        "position": (0, 3),
    },
    {
        "id": "mage.ability.waterjet",
        "kind": "ability",
        "identifier": "WaterJet",
        "lane": "Elementalism",
        "position": (0, 4),
    },
    {
        "id": "mage.ability.tremor",
        "kind": "ability",
        "identifier": "Tremor",
        "lane": "Elementalism",
        "position": (0, 5),
    },
    {
        "id": "mage.ability.fire-inside",
        "kind": "ability",
        "identifier": "FireInside",
        "lane": "Elementalism",
        "position": (1, 0),
        "level": 20,
        "prerequisites": ("mage.ability.firebolt",),
    },
    {
        "id": "mage.ability.frozen-armor",
        "kind": "ability",
        "identifier": "FrozenArmor",
        "lane": "Elementalism",
        "position": (1, 1),
        "level": 20,
        "prerequisites": ("mage.ability.icelance",),
    },
    {
        "id": "mage.ability.electrified",
        "kind": "ability",
        "identifier": "Electrified",
        "lane": "Elementalism",
        "position": (1, 2),
        "level": 20,
        "prerequisites": ("mage.ability.shock",),
    },
    {
        "id": "mage.ability.wind-currents",
        "kind": "ability",
        "identifier": "WindCurrents",
        "lane": "Elementalism",
        "position": (1, 3),
        "level": 20,
        "prerequisites": ("mage.ability.gust",),
    },
    {
        "id": "mage.ability.refreshment",
        "kind": "ability",
        "identifier": "Refreshment",
        "lane": "Elementalism",
        "position": (1, 4),
        "level": 20,
        "prerequisites": ("mage.ability.waterjet",),
    },
    {
        "id": "mage.ability.terra-firma",
        "kind": "ability",
        "identifier": "TerraFirma",
        "lane": "Elementalism",
        "position": (1, 5),
        "level": 20,
        "prerequisites": ("mage.ability.tremor",),
    },
    {
        "id": "mage.ability.magicmissile",
        "kind": "ability",
        "identifier": "MagicMissile",
        "lane": "Arcana",
        "position": (2, 0),
    },
    {
        "id": "mage.talent.arcane-fundamentals",
        "kind": "talent",
        "identifier": "mage.arcane-fundamentals",
        "name": "Guidance Upgrade",
        "lane": "Arcana",
        "position": (2, 1),
        "level": 5,
        "prerequisites": ("mage.ability.magicmissile",),
        "description": ("Increase Magic Missile projectile critical-strike damage by 20%."),
        "bonuses": {"magic_missile_critical_damage": 0.20},
    },
    {
        "id": "mage.ability.mana-rupture",
        "kind": "ability",
        "identifier": "ManaRupture",
        "lane": "Arcana",
        "position": (2, 2),
        "prerequisites": ("mage.talent.arcane-fundamentals",),
    },
    {
        "id": "mage.ability.polymorph",
        "kind": "ability",
        "identifier": "Polymorph",
        "lane": "Arcana",
        "position": (2, 3),
        "level": 15,
        "prerequisites": ("mage.ability.mana-rupture",),
    },
    {
        "id": "mage.ability.manashield",
        "kind": "ability",
        "identifier": "ManaShield",
        "lane": "Arcana",
        "position": (2, 4),
        "level": 20,
        "prerequisites": ("mage.ability.polymorph",),
    },
    {
        "id": "mage.ability.imbue-weapon",
        "kind": "ability",
        "identifier": "ImbueWeapon",
        "lane": "Arcana",
        "position": (2, 5),
        "level": 25,
        "prerequisites": ("mage.ability.manashield",),
    },
    {
        "id": "mage.ability.enfeeble",
        "kind": "ability",
        "identifier": "Enfeeble",
        "lane": "Occultism",
        "position": (3, 0),
    },
    {
        "id": "mage.ability.blinding-fog",
        "kind": "ability",
        "identifier": "BlindingFog",
        "lane": "Occultism",
        "position": (3, 1),
        "level": 5,
        "prerequisites": ("mage.ability.enfeeble",),
    },
    {
        "id": "mage.ability.shadow-bolt",
        "kind": "ability",
        "identifier": "ShadowBolt",
        "lane": "Occultism",
        "position": (3, 2),
        "level": 10,
        "prerequisites": ("mage.ability.blinding-fog",),
    },
    {
        "id": "mage.ability.inflate-health",
        "kind": "ability",
        "identifier": "InflateHealth",
        "lane": "Occultism",
        "position": (3, 3),
        "level": 15,
        "prerequisites": ("mage.ability.shadow-bolt",),
    },
    {
        "id": "mage.ability.enliven-dead",
        "kind": "ability",
        "identifier": "EnlivenDead",
        "lane": "Occultism",
        "position": (3, 4),
        "level": 20,
        "prerequisites": ("mage.ability.inflate-health",),
    },
    {
        "id": "mage.talent.forbidden-studies",
        "kind": "talent",
        "identifier": "mage.forbidden-studies",
        "name": "Forbidden Studies",
        "lane": "Occultism",
        "position": (3, 5),
        "level": 25,
        "prerequisites": ("mage.ability.enliven-dead",),
        "description": (
            "Shadow Bolt spells deal 20% more damage, and raised undead "
            "companions remain for 50% longer."
        ),
        "bonuses": {
            "shadow_bolt_damage": 0.20,
            "raised_companion_duration": 0.50,
        },
    },
    {
        "id": "mage.ability.conjure-blade",
        "kind": "ability",
        "identifier": "ConjureBlade",
        "lane": "Conjuration",
        "position": (4, 0),
    },
    {
        "id": "mage.mana.conjuration-reserve",
        "kind": "mana",
        "identifier": "Mana",
        "lane": "Conjuration",
        "position": (4, 1),
        "prerequisites": ("mage.ability.conjure-blade",),
    },
    {
        "id": "mage.ability.conjure-animal",
        "kind": "ability",
        "identifier": "ConjureAnimal",
        "lane": "Conjuration",
        "position": (4, 2),
        "level": 10,
        "prerequisites": ("mage.mana.conjuration-reserve",),
    },
    {
        "id": "mage.talent.binding-circle",
        "kind": "talent",
        "identifier": "mage.binding-circle",
        "name": "Binding Circle",
        "lane": "Conjuration",
        "position": (4, 3),
        "level": 15,
        "prerequisites": ("mage.ability.conjure-animal",),
        "description": (
            "Increase Defense by 10%; conjured and summoned allies gain 10% health and damage."
        ),
        "bonuses": {
            "rating_percentages": {"Defense": 0.10},
            "conjured_ally_health": 0.10,
            "conjured_ally_damage": 0.10,
        },
    },
    {
        "id": "mage.ability.conjure-shackles",
        "kind": "ability",
        "identifier": "ConjureShackles",
        "lane": "Conjuration",
        "position": (4, 4),
        "level": 20,
        "prerequisites": ("mage.talent.binding-circle",),
    },
    {
        "id": "mage.ability.conjure-potion",
        "kind": "ability",
        "identifier": "ConjurePotion",
        "lane": "Conjuration",
        "position": (4, 5),
        "level": 25,
        "prerequisites": ("mage.ability.conjure-shackles",),
    },
    {
        "id": "mage.ability.reflect",
        "kind": "ability",
        "identifier": "Reflect",
        "lane": "Universal",
        "position": (5, 1),
        "level": 10,
    },
    {
        "id": "mage.ability.sleep",
        "kind": "ability",
        "identifier": "Sleep",
        "lane": "Universal",
        "position": (5, 2),
        "level": 15,
    },
    {
        "id": "mage.ability.boost",
        "kind": "ability",
        "identifier": "Boost",
        "lane": "Universal",
        "position": (5, 3),
        "level": 20,
    },
    {
        "id": "mage.ability.mirror-image",
        "kind": "ability",
        "identifier": "MirrorImage",
        "lane": "Universal",
        "position": (5, 4),
        "level": 25,
    },
    {
        "id": "mage.ability.classical-force",
        "kind": "ability",
        "identifier": "ClassicalForce",
        "lane": "Elementalism",
        "position": (0.5, 6),
        "level": 25,
        "prerequisites": (
            "mage.ability.fire-inside",
            "mage.ability.frozen-armor",
            "mage.ability.electrified",
            "mage.ability.wind-currents",
            "mage.ability.refreshment",
            "mage.ability.terra-firma",
        ),
        "prerequisite_mode": "any",
        "exclusive_group": "mage.sorcerer-specialization",
        "connector_enter_from_top": True,
        "connector_channel_columns": {
            "mage.ability.fire-inside": 0.5,
            "mage.ability.frozen-armor": 0.5,
            "mage.ability.electrified": 0.5,
            "mage.ability.wind-currents": 0.5,
            "mage.ability.refreshment": 0.5,
            "mage.ability.terra-firma": 0.5,
        },
    },
    {
        "id": "mage.ability.arcane-tradition",
        "kind": "ability",
        "identifier": "ArcaneTradition",
        "lane": "Arcana",
        "position": (1.5, 6),
        "level": 25,
        "prerequisites": ("mage.ability.mana-rupture",),
        "exclusive_group": "mage.sorcerer-specialization",
        "connector_enter_from_top": True,
        "connector_channel_columns": {
            "mage.talent.arcane-fundamentals": 1.5,
        },
    },
)

MAGE_PROMOTION_SPECS = (
    (
        "Sorcerer",
        "Elementalism",
        (
            "mage.ability.classical-force",
            "mage.ability.arcane-tradition",
        ),
        (1, 7),
        "any",
    ),
    ("Spellblade", "Arcana", ("mage.ability.imbue-weapon",), (2, 7), "all"),
    ("Warlock", "Occultism", ("mage.talent.forbidden-studies",), (3, 7), "all"),
    ("Conjurer", "Conjuration", ("mage.ability.conjure-potion",), (4, 7), "all"),
)

MAGE_CARRIED_NODE_IDS = frozenset(
    {
        "mage.talent.arcane-fundamentals",
        "mage.ability.firebolt",
        "mage.ability.shock",
        "mage.ability.tremor",
        "mage.ability.waterjet",
        "mage.ability.icelance",
        "mage.ability.gust",
    }
)

MAGE_CARRIED_NODE_POSITIONS = {
    "mage.ability.magicmissile": (2, 0),
    "mage.talent.arcane-fundamentals": (3, 0),
    "mage.ability.firebolt": (2, 1),
    "mage.ability.shock": (2, 2),
    "mage.ability.tremor": (3, 1),
    "mage.ability.waterjet": (3, 2),
    "mage.ability.icelance": (4, 1),
    "mage.ability.gust": (4, 2),
}


SORCERER_TREE_NODE_SPECS = (
    {
        "id": "fireball",
        "kind": "ability",
        "identifier": "Fireball",
        "lane": "Elemental Spells",
        "position": (0, 0),
        "school_affinity": ("Fire", 30),
        "available_on_promotion": True,
        "upgrade_without_source": True,
    },
    {
        "id": "icicle",
        "kind": "ability",
        "identifier": "Icicle",
        "lane": "Elemental Spells",
        "position": (0, 1),
        "school_affinity": ("Ice", 30),
        "available_on_promotion": True,
        "upgrade_without_source": True,
    },
    {
        "id": "lightning",
        "kind": "ability",
        "identifier": "Lightning",
        "lane": "Elemental Spells",
        "position": (0, 2),
        "school_affinity": ("Electric", 30),
        "available_on_promotion": True,
        "upgrade_without_source": True,
    },
    {
        "id": "hurricane",
        "kind": "ability",
        "identifier": "Hurricane",
        "lane": "Elemental Spells",
        "position": (0, 3),
        "school_affinity": ("Wind", 30),
        "available_on_promotion": True,
        "upgrade_without_source": True,
    },
    {
        "id": "aqualung",
        "kind": "ability",
        "identifier": "Aqualung",
        "lane": "Elemental Spells",
        "position": (0, 4),
        "school_affinity": ("Water", 30),
        "available_on_promotion": True,
        "upgrade_without_source": True,
    },
    {
        "id": "mudslide",
        "kind": "ability",
        "identifier": "Mudslide",
        "lane": "Elemental Spells",
        "position": (0, 5),
        "school_affinity": ("Earth", 30),
        "available_on_promotion": True,
        "upgrade_without_source": True,
    },
    {
        "id": "classical-enrichment",
        "kind": "ability",
        "identifier": "ClassicalEnrichment",
        "lane": "Elemental Spells",
        "position": (0.5, 6),
        "level": 55,
        "prerequisites": (
            "combustion",
            "snowpiercer",
            "paralyzer",
            "ejection-gale",
            "aspirate",
            "unsteady-ground",
        ),
        "prerequisite_mode": "any",
        "connector_enter_from_top": True,
        "connector_channel_columns": {
            "combustion": 0.5,
            "snowpiercer": 0.5,
            "paralyzer": 0.5,
            "ejection-gale": 0.5,
            "aspirate": 0.5,
            "unsteady-ground": 0.5,
        },
    },
    {
        "id": "combustion",
        "kind": "ability",
        "identifier": "Combustion",
        "lane": "Spell Modifiers",
        "position": (1, 0),
        "level": 35,
        "prerequisites": ("fireball",),
    },
    {
        "id": "snowpiercer",
        "kind": "ability",
        "identifier": "Snowpiercer",
        "lane": "Spell Modifiers",
        "position": (1, 1),
        "level": 35,
        "prerequisites": ("icicle",),
    },
    {
        "id": "paralyzer",
        "kind": "ability",
        "identifier": "Paralyzer",
        "lane": "Spell Modifiers",
        "position": (1, 2),
        "level": 35,
        "prerequisites": ("lightning",),
    },
    {
        "id": "ejection-gale",
        "kind": "ability",
        "identifier": "EjectionGale",
        "lane": "Spell Modifiers",
        "position": (1, 3),
        "level": 35,
        "prerequisites": ("hurricane",),
    },
    {
        "id": "aspirate",
        "kind": "ability",
        "identifier": "Aspirate",
        "lane": "Spell Modifiers",
        "position": (1, 4),
        "level": 35,
        "prerequisites": ("aqualung",),
    },
    {
        "id": "unsteady-ground",
        "kind": "ability",
        "identifier": "UnsteadyGround",
        "lane": "Spell Modifiers",
        "position": (1, 5),
        "level": 35,
        "prerequisites": ("mudslide",),
    },
    {
        "id": "magic-missile-2",
        "kind": "ability",
        "identifier": "MagicMissile2",
        "lane": "Arcana",
        "position": (2, 0),
        "name": "Magic Missile II",
        "school_affinity": ("Arcane", 30),
        "available_on_promotion": True,
        "upgrade_without_source": True,
    },
    {
        "id": "force-multiplier",
        "kind": "ability",
        "identifier": "ForceMultiplier",
        "lane": "Arcana",
        "position": (2, 1),
        "level": 35,
        "prerequisites": ("magic-missile-2",),
    },
    {
        "id": "kinetic-explosion",
        "kind": "ability",
        "identifier": "KineticExplosion",
        "lane": "Arcana",
        "position": (2, 4),
        "level": 50,
        "prerequisites": ("mana-leak",),
    },
    {
        "id": "arcane-empowerment",
        "kind": "ability",
        "identifier": "ArcaneEmpowerment",
        "lane": "Arcana",
        "position": (2, 5),
        "level": 50,
        "prerequisites": ("kinetic-explosion",),
    },
    {
        "id": "mana-rupture",
        "kind": "ability",
        "identifier": "ManaRupture",
        "lane": "Arcana",
        "position": (2, 2),
        "level": 40,
        "available_on_promotion": True,
        "owned_if_known": True,
        "prerequisites": ("force-multiplier",),
    },
    {
        "id": "mana-leak",
        "kind": "ability",
        "identifier": "ManaLeak",
        "lane": "Arcana",
        "position": (2, 3),
        "level": 45,
        "prerequisites": ("mana-rupture",),
    },
    {
        "id": "arcane-ritual",
        "kind": "ability",
        "identifier": "ArcaneRitual",
        "lane": "Arcana",
        "position": (1.5, 6),
        "level": 55,
        "prerequisites": ("arcane-empowerment",),
        "connector_enter_from_top": True,
        "connector_channel_columns": {
            "arcane-empowerment": 1.5,
        },
    },
    {
        "id": "boost",
        "kind": "ability",
        "identifier": "Boost",
        "lane": "Spell Enhancements",
        "position": (3, 0),
        "available_on_promotion": True,
    },
    {
        "id": "dispel",
        "kind": "ability",
        "identifier": "Dispel",
        "lane": "Spell Enhancements",
        "position": (3, 1),
        "level": 35,
        "prerequisites": ("boost",),
    },
    {
        "id": "magic",
        "kind": "rating",
        "identifier": "Magic",
        "lane": "Spell Enhancements",
        "position": (3, 2),
        "prerequisites": ("dispel",),
    },
    {
        "id": "refueling",
        "kind": "ability",
        "identifier": "Refueling",
        "lane": "Spell Enhancements",
        "position": (3, 3),
        "level": 45,
        "prerequisites": ("magic",),
    },
    {
        "id": "doublecast",
        "kind": "ability",
        "identifier": "Doublecast",
        "lane": "Spell Enhancements",
        "position": (3, 4),
        "level": 50,
        "prerequisites": ("refueling",),
    },
    {
        "id": "mirror-image",
        "kind": "ability",
        "identifier": "MirrorImage",
        "lane": "Illusion",
        "position": (4, 0),
        "available_on_promotion": True,
    },
    {
        "id": "slow",
        "kind": "ability",
        "identifier": "Slow",
        "lane": "Illusion",
        "position": (4, 1),
        "level": 35,
        "prerequisites": ("mirror-image",),
    },
    {
        "id": "ice-block",
        "kind": "ability",
        "identifier": "IceBlock",
        "lane": "Illusion",
        "position": (4, 2),
        "level": 40,
        "prerequisites": ("slow",),
    },
    {
        "id": "illusory-link",
        "kind": "ability",
        "identifier": "IllusoryLink",
        "lane": "Illusion",
        "position": (4, 3),
        "level": 45,
        "prerequisites": ("ice-block",),
    },
)

WARLOCK_TREE_NODE_SPECS = (
    {
        "id": "sleep",
        "kind": "ability",
        "identifier": "Sleep",
        "lane": "Shadow Control",
        "position": (0, 1),
        "available_on_promotion": True,
    },
    {
        "id": "dispel",
        "kind": "ability",
        "identifier": "Dispel",
        "lane": "Shadow Control",
        "position": (0, 2),
        "level": 35,
        "prerequisites": ("sleep",),
    },
    {
        "id": "terrify",
        "kind": "ability",
        "identifier": "Terrify",
        "lane": "Shadow Control",
        "position": (0, 4),
        "level": 45,
        "prerequisites": ("dispel",),
    },
    {
        "id": "doom",
        "kind": "ability",
        "identifier": "Doom",
        "lane": "Shadow Control",
        "position": (0, 5),
        "level": 50,
        "prerequisites": ("terrify",),
    },
    {
        "id": "health-drain",
        "kind": "ability",
        "identifier": "HealthDrain",
        "lane": "Draining",
        "position": (1, 1),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "magic-defense",
        "kind": "rating",
        "identifier": "Magic Defense",
        "lane": "Draining",
        "position": (1, 2),
        "prerequisites": ("health-drain",),
    },
    {
        "id": "resist-holy",
        "kind": "ability",
        "identifier": "ResistHoly",
        "lane": "Draining",
        "position": (1, 3),
        "level": 40,
        "prerequisites": ("magic-defense",),
    },
    {
        "id": "vim-and-rigor",
        "kind": "ability",
        "identifier": "VimAndRigor",
        "lane": "Draining",
        "position": (1, 4),
        "level": 45,
        "prerequisites": ("resist-holy",),
    },
    {
        "id": "mana-drain",
        "kind": "ability",
        "identifier": "ManaDrain",
        "lane": "Draining",
        "position": (1, 6),
        "level": 55,
        "prerequisites": ("vim-and-rigor",),
    },
    {
        "id": "shadow-bolt",
        "kind": "ability",
        "identifier": "ShadowBolt",
        "lane": "Umbral Offense",
        "position": (2, 1),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "magic",
        "kind": "rating",
        "identifier": "Magic",
        "lane": "Umbral Offense",
        "position": (2, 2),
        "prerequisites": ("shadow-bolt",),
    },
    {
        "id": "impending-demise",
        "kind": "ability",
        "identifier": "ImpendingDemise",
        "lane": "Umbral Offense",
        "position": (2, 4),
        "level": 45,
        "prerequisites": ("magic",),
    },
    {
        "id": "eclipse",
        "kind": "ability",
        "identifier": "Eclipse",
        "lane": "Umbral Offense",
        "position": (2, 5),
        "level": 50,
        "prerequisites": ("impending-demise",),
    },
    {
        "id": "shadow-bolt-2",
        "kind": "ability",
        "identifier": "ShadowBolt2",
        "name": "Shadow Bolt II",
        "lane": "Umbral Offense",
        "position": (2, 6),
        "level": 55,
        "prerequisites": ("eclipse",),
        "upgrade_without_source": True,
    },
    {
        "id": "curse-umbra",
        "kind": "ability",
        "identifier": "CurseUmbra",
        "lane": "Curses",
        "position": (3, 1),
        "available_on_promotion": True,
    },
    {
        "id": "curse-frailty",
        "kind": "ability",
        "identifier": "CurseFrailty",
        "lane": "Curses",
        "position": (3, 2),
        "level": 35,
        "prerequisites": ("curse-umbra",),
    },
    {
        "id": "hemorrhaging-curse",
        "kind": "ability",
        "identifier": "HemorrhagingCurse",
        "lane": "Curses",
        "position": (3, 3),
        "level": 40,
        "prerequisites": ("curse-frailty",),
    },
    {
        "id": "curse-swarms",
        "kind": "ability",
        "identifier": "CurseSwarms",
        "lane": "Curses",
        "position": (3, 5),
        "level": 50,
        "prerequisites": ("hemorrhaging-curse",),
    },
    {
        "id": "corruption",
        "kind": "ability",
        "identifier": "Corruption",
        "lane": "Corruption",
        "position": (4, 1),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "mana",
        "kind": "mana",
        "identifier": "Mana",
        "lane": "Corruption",
        "position": (4, 2),
        "prerequisites": ("corruption",),
    },
    {
        "id": "hex",
        "kind": "ability",
        "identifier": "Hex",
        "lane": "Corruption",
        "position": (4, 3),
        "level": 40,
        "prerequisites": ("mana",),
    },
    {
        "id": "festering-anguish",
        "kind": "ability",
        "identifier": "FesteringAnguish",
        "lane": "Corruption",
        "position": (4, 4),
        "level": 45,
        "prerequisites": ("hex",),
    },
    {
        "id": "life-tap",
        "kind": "ability",
        "identifier": "LifeTap",
        "lane": "Corruption",
        "position": (4, 6),
        "level": 55,
        "prerequisites": ("festering-anguish",),
    },
    {
        "id": "familiar-bond",
        "kind": "ability",
        "identifier": "FamiliarBond",
        "lane": "Familiar",
        "position": (5, 1),
        "level": 35,
    },
    {
        "id": "thorn-by-my-side",
        "kind": "ability",
        "identifier": "ThornByMySide",
        "lane": "Familiar",
        "position": (5, 2),
        "level": 45,
    },
    {
        "id": "restorative-barrier",
        "kind": "ability",
        "identifier": "RestorativeBarrier",
        "lane": "Familiar",
        "position": (5, 3),
        "level": 45,
    },
    {
        "id": "insult-to-injury",
        "kind": "ability",
        "identifier": "InsultToInjury",
        "lane": "Familiar",
        "position": (5, 4),
        "level": 45,
    },
    {
        "id": "master-locator",
        "kind": "ability",
        "identifier": "MasterLocator",
        "lane": "Familiar",
        "position": (5, 5),
        "level": 45,
    },
    {
        "id": "familiar-bond-2",
        "kind": "ability",
        "identifier": "FamiliarBond2",
        "name": "Familiar Bond II",
        "lane": "Familiar",
        "position": (5, 6),
        "level": 55,
        "prerequisites": ("familiar-bond",),
        "connector_channel_columns": {"familiar-bond": 5.5},
    },
)


SHADOWCASTER_TREE_NODE_SPECS = (
    {
        "id": "mana-tap",
        "kind": "ability",
        "identifier": "ManaTap",
        "lane": "Umbral Debt",
        "position": (0, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "soul-binding",
        "kind": "ability",
        "identifier": "SoulBinding",
        "lane": "Umbral Debt",
        "position": (0, 1),
        "level": 65,
        "prerequisites": ("mana-tap",),
    },
    {
        "id": "health-mana-drain",
        "kind": "ability",
        "identifier": "HealthManaDrain",
        "lane": "Umbral Debt",
        "position": (0, 2),
        "level": 70,
        "prerequisites": ("soul-binding",),
        "upgrade_without_source": True,
    },
    {
        "id": "resource-abuse",
        "kind": "ability",
        "identifier": "ResourceAbuse",
        "lane": "Umbral Debt",
        "position": (0, 3),
        "level": 75,
        "prerequisites": ("health-mana-drain",),
    },
    {
        "id": "mortal-shackles",
        "kind": "ability",
        "identifier": "MortalShackles",
        "lane": "Umbral Debt",
        "position": (0, 4),
        "level": 80,
        "prerequisites": ("resource-abuse",),
    },
    {
        "id": "top-off",
        "kind": "ability",
        "identifier": "TopOff",
        "lane": "Umbral Debt",
        "position": (0, 5),
        "level": 85,
        "prerequisites": ("mortal-shackles",),
        "cost": 2,
    },
    {
        "id": "shadow-bolt-3",
        "kind": "ability",
        "identifier": "ShadowBolt3",
        "name": "Shadow Bolt III",
        "lane": "Deep Shadow",
        "position": (1, 0),
        "available_on_promotion": True,
        "upgrade_without_source": True,
    },
    {
        "id": "penny-dreadful",
        "kind": "ability",
        "identifier": "PennyDreadful",
        "lane": "Deep Shadow",
        "position": (1, 2),
        "level": 70,
        "prerequisites": ("shadow-bolt-3",),
    },
    {
        "id": "piercing-bolt",
        "kind": "ability",
        "identifier": "PiercingBolt",
        "lane": "Deep Shadow",
        "position": (1, 3),
        "level": 75,
        "prerequisites": ("penny-dreadful",),
    },
    {
        "id": "invisibility",
        "kind": "ability",
        "identifier": "Invisibility",
        "lane": "Veilcraft",
        "position": (2, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "shadow-curtain",
        "kind": "ability",
        "identifier": "ShadowCurtain",
        "lane": "Veilcraft",
        "position": (2, 1),
        "level": 65,
        "prerequisites": ("invisibility",),
    },
    {
        "id": "alacrity",
        "kind": "ability",
        "identifier": "Alacrity",
        "lane": "Veilcraft",
        "position": (2, 2),
        "level": 70,
        "prerequisites": ("shadow-curtain",),
    },
    {
        "id": "sciophobia",
        "kind": "ability",
        "identifier": "Sciophobia",
        "lane": "Veilcraft",
        "position": (2, 3),
        "level": 75,
        "prerequisites": ("alacrity",),
    },
    {
        "id": "nightmare",
        "kind": "ability",
        "identifier": "Nightmare",
        "lane": "Nightmares",
        "position": (3, 0),
        "available_on_promotion": True,
    },
    {
        "id": "night-terror",
        "kind": "ability",
        "identifier": "NightTerror",
        "lane": "Nightmares",
        "position": (3, 3),
        "level": 75,
        "prerequisites": ("nightmare",),
    },
    {
        "id": "desoul",
        "kind": "ability",
        "identifier": "Desoul",
        "lane": "Nightmares",
        "position": (3, 4),
        "level": 80,
        "prerequisites": ("night-terror",),
    },
    {
        "id": "death-becomes-us",
        "kind": "ability",
        "identifier": "DeathBecomesUs",
        "lane": "Nightmares",
        "position": (3, 5),
        "level": 85,
        "prerequisites": ("desoul",),
        "cost": 2,
    },
    {
        "id": "indiscriminate-provocation",
        "kind": "ability",
        "identifier": "IndiscriminateProvocation",
        "lane": "Familiar Mastery",
        "position": (4, 1),
        "level": 75,
        "cost": 2,
    },
    {
        "id": "uno-reverse-card",
        "kind": "ability",
        "identifier": "UnoReverseCard",
        "lane": "Familiar Mastery",
        "position": (4, 2),
        "level": 75,
        "cost": 2,
    },
    {
        "id": "night-moves",
        "kind": "ability",
        "identifier": "NightMoves",
        "lane": "Familiar Mastery",
        "position": (4, 3),
        "level": 75,
        "cost": 2,
    },
    {
        "id": "bullionaire",
        "kind": "ability",
        "identifier": "Bullionaire",
        "lane": "Familiar Mastery",
        "position": (4, 4),
        "level": 75,
        "cost": 2,
    },
)


DEMONOLOGIST_TREE_NODE_SPECS = (
    {
        "id": "mystical-vitality",
        "kind": "ability",
        "identifier": "MysticalVitality",
        "lane": "Contagion",
        "position": (0, 0),
        "available_on_promotion": True,
    },
    {
        "id": "contagious-blaze",
        "kind": "ability",
        "identifier": "ContagiousBlaze",
        "lane": "Contagion",
        "position": (0, 1),
        "level": 65,
        "prerequisites": ("mystical-vitality",),
    },
    {
        "id": "corruption-2",
        "kind": "ability",
        "identifier": "Corruption2",
        "lane": "Contagion",
        "position": (0, 2),
        "level": 70,
        "prerequisites": ("contagious-blaze",),
        "upgrade_without_source": True,
    },
    {
        "id": "magic",
        "kind": "rating",
        "identifier": "Magic",
        "lane": "Contagion",
        "position": (0, 3),
        "prerequisites": ("corruption-2",),
    },
    {
        "id": "persistent-corruption",
        "kind": "ability",
        "identifier": "PersistentCorruption",
        "lane": "Contagion",
        "position": (0, 4),
        "level": 80,
        "prerequisites": ("magic",),
    },
    {
        "id": "fine-print",
        "kind": "ability",
        "identifier": "FinePrint",
        "lane": "Contract Mastery",
        "position": (1, 0),
        "available_on_promotion": True,
    },
    {
        "id": "controlled-corruption",
        "kind": "ability",
        "identifier": "ControlledCorruption",
        "lane": "Contract Mastery",
        "position": (1, 2),
        "level": 70,
        "prerequisites": ("fine-print",),
    },
    {
        "id": "patronage",
        "kind": "ability",
        "identifier": "Patronage",
        "lane": "Contract Mastery",
        "position": (1, 3),
        "level": 75,
        "prerequisites": ("controlled-corruption",),
    },
    {
        "id": "abyssal-authority",
        "kind": "ability",
        "identifier": "AbyssalAuthority",
        "lane": "Contract Mastery",
        "position": (1, 4),
        "level": 80,
        "prerequisites": ("patronage",),
    },
    {
        "id": "firebolt",
        "kind": "ability",
        "identifier": "Firebolt",
        "lane": "Hellfire",
        "position": (2, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "grease-missile",
        "kind": "ability",
        "identifier": "GreaseMissile",
        "lane": "Hellfire",
        "position": (2, 1),
        "level": 65,
        "prerequisites": ("firebolt",),
    },
    {
        "id": "netherchar",
        "kind": "ability",
        "identifier": "Netherchar",
        "lane": "Hellfire",
        "position": (2, 2),
        "level": 70,
        "prerequisites": ("grease-missile",),
    },
    {
        "id": "napalm",
        "kind": "ability",
        "identifier": "Napalm",
        "lane": "Hellfire",
        "position": (2, 3),
        "level": 75,
        "prerequisites": ("netherchar",),
    },
    {
        "id": "soul-siphon",
        "kind": "ability",
        "identifier": "SoulSiphon",
        "lane": "Soul Harvest",
        "position": (3, 0),
        "available_on_promotion": True,
    },
    {
        "id": "dance-of-the-dead",
        "kind": "ability",
        "identifier": "DanceOfTheDead",
        "lane": "Soul Harvest",
        "position": (3, 1),
        "level": 65,
        "prerequisites": ("soul-siphon",),
    },
    {
        "id": "soul-vessel",
        "kind": "ability",
        "identifier": "SoulVessel",
        "lane": "Soul Harvest",
        "position": (3, 3),
        "level": 75,
        "prerequisites": ("dance-of-the-dead",),
    },
    {
        "id": "desoul",
        "kind": "ability",
        "identifier": "Desoul",
        "lane": "Soul Harvest",
        "position": (3, 4),
        "level": 80,
        "prerequisites": ("soul-vessel",),
    },
    {
        "id": "soul-asylum",
        "kind": "ability",
        "identifier": "SoulAsylum",
        "lane": "Soul Harvest",
        "position": (3, 5),
        "level": 85,
        "prerequisites": ("desoul",),
        "cost": 2,
    },
    {
        "id": "contract-killer",
        "kind": "ability",
        "identifier": "ContractKiller",
        "lane": "Contract Mastery",
        "position": (1, 5),
        "level": 85,
        "prerequisites": ("abyssal-authority",),
        "cost": 2,
    },
    {
        "id": "flammable-affliction",
        "kind": "ability",
        "identifier": "FlammableAffliction",
        "lane": "Demonic Curses",
        "position": (4, 0),
        "available_on_promotion": True,
    },
    {
        "id": "curse-elijah",
        "kind": "ability",
        "identifier": "CurseElijah",
        "lane": "Demonic Curses",
        "position": (4, 1),
        "level": 65,
        "prerequisites": ("flammable-affliction",),
    },
    {
        "id": "curse-dysarthria",
        "kind": "ability",
        "identifier": "CurseDysarthria",
        "lane": "Demonic Curses",
        "position": (4, 2),
        "level": 70,
        "prerequisites": ("curse-elijah",),
    },
    {
        "id": "monkeys-paw",
        "kind": "ability",
        "identifier": "MonkeysPaw",
        "lane": "Demonic Curses",
        "position": (4, 3),
        "level": 75,
        "prerequisites": ("curse-dysarthria",),
    },
    {
        "id": "demon-eyes",
        "kind": "ability",
        "identifier": "DemonEyes",
        "lane": "Demonic Curses",
        "position": (4, 4),
        "level": 80,
        "prerequisites": ("monkeys-paw",),
        "cost": 2,
    },
)


SPELLBLADE_TREE_NODE_SPECS = (
    {
        "id": "counter-charge",
        "kind": "ability",
        "identifier": "CounterCharge",
        "lane": "Weapon Enhancements",
        "position": (0, 1),
        "available_on_promotion": True,
    },
    {
        "id": "attack",
        "kind": "rating",
        "identifier": "Attack",
        "lane": "Weapon Enhancements",
        "position": (0, 2),
        "level": 35,
        "level_band_gate": True,
        "prerequisites": ("counter-charge",),
    },
    {
        "id": "breakdown",
        "kind": "ability",
        "identifier": "Breakdown",
        "lane": "Weapon Enhancements",
        "position": (0, 3),
        "level": 40,
        "prerequisites": ("attack",),
    },
    {
        "id": "mana-slice",
        "kind": "ability",
        "identifier": "ManaSlice",
        "lane": "Weapon Enhancements",
        "position": (0, 4),
        "level": 45,
        "prerequisites": ("breakdown",),
    },
    {
        "id": "enhance-blade",
        "kind": "ability",
        "identifier": "EnhanceBlade",
        "lane": "Weapon Enhancements",
        "position": (0, 5),
        "level": 50,
        "prerequisites": ("mana-slice",),
    },
    {
        "id": "reflect",
        "kind": "ability",
        "identifier": "Reflect",
        "lane": "Armor Enhancements",
        "position": (1, 1),
        "owned_if_known": True,
    },
    {
        "id": "magic-defense",
        "kind": "rating",
        "identifier": "Magic Defense",
        "lane": "Armor Enhancements",
        "position": (1, 2),
        "level": 35,
        "level_band_gate": True,
        "prerequisites": ("reflect",),
    },
    {
        "id": "novel-shielding",
        "kind": "ability",
        "identifier": "NovelShielding",
        "lane": "Armor Enhancements",
        "position": (1, 3),
        "level": 40,
        "prerequisites": ("magic-defense",),
    },
    {
        "id": "defense",
        "kind": "rating",
        "identifier": "Defense",
        "lane": "Armor Enhancements",
        "position": (1, 4),
        "level": 45,
        "level_band_gate": True,
        "prerequisites": ("novel-shielding",),
    },
    {
        "id": "enhance-armor",
        "kind": "ability",
        "identifier": "EnhanceArmor",
        "lane": "Armor Enhancements",
        "position": (1, 6),
        "level": 55,
        "prerequisites": ("defense",),
    },
    {
        "id": "boost",
        "kind": "ability",
        "identifier": "Boost",
        "lane": "Spell Enhancements",
        "position": (2, 1),
        "owned_if_known": True,
    },
    {
        "id": "kinetic-explosion",
        "kind": "ability",
        "identifier": "KineticExplosion",
        "lane": "Spell Enhancements",
        "position": (2, 2),
        "level": 35,
        "prerequisites": ("boost",),
    },
    {
        "id": "magic",
        "kind": "rating",
        "identifier": "Magic",
        "lane": "Spell Enhancements",
        "position": (2, 3),
        "level": 40,
        "level_band_gate": True,
        "prerequisites": ("kinetic-explosion",),
    },
    {
        "id": "mana-tap",
        "kind": "ability",
        "identifier": "ManaTap",
        "lane": "Spell Enhancements",
        "position": (2, 4),
        "level": 45,
        "prerequisites": ("magic",),
    },
    {
        "id": "amplify-arcane",
        "kind": "ability",
        "identifier": "AmplifyArcane",
        "lane": "Spell Enhancements",
        "position": (1.5, 5),
        "level": 50,
        "prerequisites": ("mana-tap",),
    },
    {
        "id": "amplify-elemental",
        "kind": "ability",
        "identifier": "AmplifyElemental",
        "lane": "Spell Enhancements",
        "position": (2.5, 5),
        "level": 50,
        "prerequisites": ("mana-tap",),
    },
    {
        "id": "storage-capacity",
        "kind": "ability",
        "identifier": "StorageCapacity",
        "lane": "Spell Enhancements",
        "position": (2, 6),
        "level": 55,
        "prerequisites": ("amplify-arcane", "amplify-elemental"),
        "prerequisite_mode": "any",
    },
    {
        "id": "true-strike",
        "kind": "ability",
        "identifier": "TrueStrike",
        "lane": "Universal / Extra Abilities",
        "position": (3, 2),
        "level": 35,
        "owned_if_known": True,
    },
    {
        "id": "parry",
        "kind": "ability",
        "identifier": "Parry",
        "lane": "Universal / Extra Abilities",
        "position": (3, 3),
        "level": 40,
        "owned_if_known": True,
    },
    {
        "id": "double-strike",
        "kind": "ability",
        "identifier": "DoubleStrike",
        "lane": "Universal / Extra Abilities",
        "position": (3, 4),
        "level": 45,
        "owned_if_known": True,
    },
)


WIZARD_TREE_NODE_SPECS = (
    {
        "id": "firestorm",
        "kind": "ability",
        "identifier": "Firestorm",
        "lane": "Master Elemental Spells",
        "position": (0, 0),
        "school_affinity": ("Fire", 80),
        "available_on_promotion": True,
        "upgrade_without_source": True,
    },
    {
        "id": "blizzard",
        "kind": "ability",
        "identifier": "IceBlizzard",
        "lane": "Master Elemental Spells",
        "position": (0, 1),
        "school_affinity": ("Ice", 80),
        "available_on_promotion": True,
        "upgrade_without_source": True,
    },
    {
        "id": "electrocution",
        "kind": "ability",
        "identifier": "Electrocution",
        "lane": "Master Elemental Spells",
        "position": (0, 2),
        "school_affinity": ("Electric", 80),
        "available_on_promotion": True,
        "upgrade_without_source": True,
    },
    {
        "id": "tornado",
        "kind": "ability",
        "identifier": "Tornado",
        "lane": "Master Elemental Spells",
        "position": (0, 3),
        "school_affinity": ("Wind", 80),
        "available_on_promotion": True,
        "upgrade_without_source": True,
    },
    {
        "id": "tsunami",
        "kind": "ability",
        "identifier": "Tsunami",
        "lane": "Master Elemental Spells",
        "position": (0, 4),
        "school_affinity": ("Water", 80),
        "available_on_promotion": True,
        "upgrade_without_source": True,
    },
    {
        "id": "earthquake",
        "kind": "ability",
        "identifier": "Earthquake",
        "lane": "Master Elemental Spells",
        "position": (0, 5),
        "school_affinity": ("Earth", 80),
        "available_on_promotion": True,
        "upgrade_without_source": True,
    },
    {
        "id": "inferno",
        "kind": "ability",
        "identifier": "Inferno",
        "lane": "Master Modifiers",
        "position": (1, 0),
        "level": 65,
        "prerequisites": ("firestorm",),
    },
    {
        "id": "subzero",
        "kind": "ability",
        "identifier": "Subzero",
        "lane": "Master Modifiers",
        "position": (1, 1),
        "level": 65,
        "prerequisites": ("blizzard",),
    },
    {
        "id": "electrical-burns",
        "kind": "ability",
        "identifier": "ElectricalBurns",
        "lane": "Master Modifiers",
        "position": (1, 2),
        "level": 65,
        "prerequisites": ("electrocution",),
    },
    {
        "id": "divine-wind",
        "kind": "ability",
        "identifier": "DivineWind",
        "lane": "Master Modifiers",
        "position": (1, 3),
        "level": 65,
        "prerequisites": ("tornado",),
    },
    {
        "id": "unrelenting-waves",
        "kind": "ability",
        "identifier": "UnrelentingWaves",
        "lane": "Master Modifiers",
        "position": (1, 4),
        "level": 65,
        "prerequisites": ("tsunami",),
    },
    {
        "id": "aftershock",
        "kind": "ability",
        "identifier": "Aftershock",
        "lane": "Master Modifiers",
        "position": (1, 5),
        "level": 65,
        "prerequisites": ("earthquake",),
    },
    {
        "id": "magic-missile-3",
        "kind": "ability",
        "identifier": "MagicMissile3",
        "name": "Magic Missile III",
        "lane": "Grand Arcana",
        "position": (2, 0),
        "school_affinity": ("Arcane", 80),
        "available_on_promotion": True,
        "upgrade_without_source": True,
    },
    {
        "id": "fragmentation",
        "kind": "ability",
        "identifier": "Fragmentation",
        "lane": "Grand Arcana",
        "position": (2, 1),
        "level": 65,
        "prerequisites": ("magic-missile-3",),
    },
    {
        "id": "mana-splinters",
        "kind": "ability",
        "identifier": "ManaSplinters",
        "lane": "Grand Arcana",
        "position": (2, 2),
        "level": 70,
        "prerequisites": ("fragmentation",),
    },
    {
        "id": "detonation-cascade",
        "kind": "ability",
        "identifier": "DetonationCascade",
        "lane": "Grand Arcana",
        "position": (2, 3),
        "level": 75,
        "prerequisites": ("mana-splinters",),
    },
    {
        "id": "photon-sphere",
        "kind": "ability",
        "identifier": "PhotonSphere",
        "lane": "Grand Arcana",
        "name": "Unknown",
        "revealed_name": "Photon Sphere",
        "position": (2, 6),
        "owned_if_known": True,
        "quest_unlock": "The Light Beyond Domingo",
        "icon_key": "unknown",
    },
    {
        "id": "prismatic-cataclysm",
        "kind": "ability",
        "identifier": "PrismaticCataclysm",
        "lane": "Master Modifiers",
        "name": "Unknown",
        "revealed_name": "Prismatic Cataclysm",
        "position": (0.5, 6),
        "owned_if_known": True,
        "quest_unlock": "The Sixfold Calamity",
        "icon_key": "unknown",
    },
    {
        "id": "elemental-convergence",
        "kind": "ability",
        "identifier": "ElementalConvergence",
        "lane": "Master Modifiers",
        "position": (0.5, 7),
        "prerequisites": ("prismatic-cataclysm",),
        "hidden_until_known": "Prismatic Cataclysm",
        "available_on_promotion": True,
    },
    {
        "id": "spaghettification",
        "kind": "ability",
        "identifier": "Spaghettification",
        "lane": "Grand Arcana",
        "position": (2, 7),
        "prerequisites": ("photon-sphere",),
        "hidden_until_known": "Photon Sphere",
        "available_on_promotion": True,
    },
    {
        "id": "counterspell",
        "kind": "ability",
        "identifier": "Counterspell",
        "lane": "Master Control",
        "position": (3, 0),
        "available_on_promotion": True,
    },
    {
        "id": "gravitational-pull",
        "kind": "ability",
        "identifier": "GravitationalPull",
        "lane": "Master Control",
        "position": (3, 1),
        "level": 65,
        "prerequisites": ("counterspell",),
    },
    {
        "id": "petrify",
        "kind": "ability",
        "identifier": "Petrify",
        "lane": "Master Control",
        "position": (3, 4),
        "level": 80,
        "prerequisites": ("gravitational-pull",),
    },
    {
        "id": "volitation",
        "kind": "ability",
        "identifier": "Volitation",
        "lane": "Spatial Illusion",
        "position": (4, 0),
        "available_on_promotion": True,
    },
    {
        "id": "mirror-image-2",
        "kind": "ability",
        "identifier": "MirrorImage2",
        "name": "Mirror Image II",
        "lane": "Spatial Illusion",
        "position": (4, 1),
        "level": 65,
        "upgrade_without_source": True,
        "prerequisites": ("volitation",),
    },
    {
        "id": "multiplicity",
        "kind": "ability",
        "identifier": "Multiplicity",
        "lane": "Spatial Illusion",
        "position": (4, 2),
        "level": 70,
        "prerequisites": ("mirror-image-2",),
    },
    {
        "id": "teleport",
        "kind": "ability",
        "identifier": "Teleport",
        "lane": "Spatial Illusion",
        "position": (4, 3),
        "level": 75,
        "prerequisites": ("multiplicity",),
    },
    {
        "id": "triplecast",
        "kind": "ability",
        "identifier": "Triplecast",
        "lane": "Spatial Illusion",
        "position": (4, 6),
        "level": 90,
        "prerequisites": ("teleport",),
    },
)


KNIGHT_ENCHANTER_TREE_NODE_SPECS = (
    {
        "id": "fireball",
        "kind": "ability",
        "identifier": "Fireball",
        "lane": "Advanced Spells",
        "position": (0, 0),
        "level": 70,
        "upgrade_without_source": True,
    },
    {
        "id": "icicle",
        "kind": "ability",
        "identifier": "Icicle",
        "lane": "Advanced Spells",
        "position": (0, 1),
        "level": 70,
        "upgrade_without_source": True,
    },
    {
        "id": "lightning",
        "kind": "ability",
        "identifier": "Lightning",
        "lane": "Advanced Spells",
        "position": (0, 2),
        "level": 70,
        "upgrade_without_source": True,
    },
    {
        "id": "hurricane",
        "kind": "ability",
        "identifier": "Hurricane",
        "lane": "Advanced Spells",
        "position": (0, 3),
        "level": 70,
        "upgrade_without_source": True,
    },
    {
        "id": "aqualung",
        "kind": "ability",
        "identifier": "Aqualung",
        "lane": "Advanced Spells",
        "position": (0, 4),
        "level": 70,
        "upgrade_without_source": True,
    },
    {
        "id": "mudslide",
        "kind": "ability",
        "identifier": "Mudslide",
        "lane": "Advanced Spells",
        "position": (0, 5),
        "level": 70,
        "upgrade_without_source": True,
    },
    {
        "id": "magic-missile-2",
        "kind": "ability",
        "identifier": "MagicMissile2",
        "lane": "Advanced Spells",
        "position": (0, 6),
        "level": 70,
        "name": "Magic Missile II",
        "upgrade_without_source": True,
    },
    {
        "id": "double-strike",
        "kind": "ability",
        "identifier": "DoubleStrike",
        "lane": "Assault Release",
        "position": (1, 0),
        "owned_if_known": True,
    },
    {
        "id": "cleaving-edge",
        "kind": "ability",
        "identifier": "CleavingEdge",
        "lane": "Assault Release",
        "position": (1, 1),
        "level": 65,
        "prerequisites": ("double-strike",),
    },
    {
        "id": "re-debuff",
        "kind": "ability",
        "identifier": "ReDebuff",
        "lane": "Assault Release",
        "position": (1, 2),
        "level": 70,
        "prerequisites": ("cleaving-edge",),
    },
    {
        "id": "resonant-strike",
        "kind": "ability",
        "identifier": "ResonantStrike",
        "lane": "Assault Release",
        "position": (1, 3),
        "level": 75,
        "prerequisites": ("re-debuff",),
    },
    {
        "id": "mana-slice-2",
        "kind": "ability",
        "identifier": "ManaSlice2",
        "lane": "Assault Release",
        "position": (1, 5),
        "level": 85,
        "prerequisites": ("resonant-strike",),
    },
    {
        "id": "quick-recharge",
        "kind": "ability",
        "identifier": "QuickRecharge",
        "lane": "Assault Release",
        "position": (1, 6),
        "level": 90,
        "cost": 2,
        "prerequisites": ("mana-slice-2",),
    },
    {
        "id": "enhance-armor",
        "kind": "ability",
        "identifier": "EnhanceArmor",
        "lane": "Aegis Release",
        "position": (2, 0),
        "owned_if_known": True,
    },
    {
        "id": "defensive-release",
        "kind": "ability",
        "identifier": "DefensiveRelease",
        "lane": "Aegis Release",
        "position": (2, 1),
        "level": 65,
        "prerequisites": ("enhance-armor",),
    },
    {
        "id": "third-eye",
        "kind": "ability",
        "identifier": "ThirdEye",
        "lane": "Aegis Release",
        "position": (2, 2),
        "level": 70,
        "cost": 2,
        "prerequisites": ("defensive-release",),
    },
    {
        "id": "aegis-weave",
        "kind": "ability",
        "identifier": "AegisWeave",
        "lane": "Aegis Release",
        "position": (2, 3),
        "level": 75,
        "prerequisites": ("third-eye",),
    },
    {
        "id": "weave-reservoir",
        "kind": "ability",
        "identifier": "WeaveReservoir",
        "lane": "Aegis Release",
        "position": (2, 4),
        "level": 80,
        "prerequisites": ("aegis-weave",),
    },
    {
        "id": "arcane-riposte",
        "kind": "ability",
        "identifier": "ArcaneRiposte",
        "lane": "Aegis Release",
        "position": (2, 5),
        "level": 85,
        "prerequisites": ("weave-reservoir",),
    },
    {
        "id": "mana-tap",
        "kind": "ability",
        "identifier": "ManaTap",
        "lane": "Spellbind Release",
        "position": (3, 0),
        "owned_if_known": True,
    },
    {
        "id": "dispel-slash",
        "kind": "ability",
        "identifier": "DispelSlash",
        "lane": "Spellbind Release",
        "position": (3, 1),
        "level": 65,
        "prerequisites": ("mana-tap",),
    },
    {
        "id": "storage-capacity-2",
        "kind": "ability",
        "identifier": "StorageCapacity2",
        "lane": "Spellbind Release",
        "position": (3, 3),
        "level": 75,
        "cost": 2,
        "prerequisites": ("dispel-slash",),
    },
    {
        "id": "spellbind",
        "kind": "ability",
        "identifier": "Spellbind",
        "lane": "Spellbind Release",
        "position": (3, 4),
        "level": 80,
        "prerequisites": ("storage-capacity-2",),
    },
    {
        "id": "echoing-blade",
        "kind": "ability",
        "identifier": "EchoingBlade",
        "lane": "Spellbind Release",
        "position": (3, 5),
        "level": 85,
        "prerequisites": ("spellbind",),
    },
    {
        "id": "parry",
        "kind": "ability",
        "identifier": "Parry",
        "lane": "Universal / Extra Abilities",
        "position": (4, 0),
        "owned_if_known": True,
    },
    {
        "id": "riposte",
        "kind": "ability",
        "identifier": "Riposte",
        "lane": "Universal / Extra Abilities",
        "position": (4, 1),
        "level": 65,
        "prerequisites": ("parry",),
    },
    {
        "id": "true-piercing-strike",
        "kind": "ability",
        "identifier": "TruePiercingStrike",
        "lane": "Universal / Extra Abilities",
        "position": (4, 3),
        "level": 75,
    },
    {
        "id": "triple-strike",
        "kind": "ability",
        "identifier": "TripleStrike",
        "lane": "Universal / Extra Abilities",
        "position": (4, 5),
        "level": 85,
    },
)


CONJURER_TREE_NODE_SPECS = (
    {
        "id": "floating-crystal",
        "kind": "ability",
        "identifier": "FloatingCrystal",
        "lane": "Constructs",
        "position": (3, 1),
        "available_on_promotion": True,
    },
    {
        "id": "torchlight",
        "kind": "ability",
        "identifier": "Torchlight",
        "lane": "Constructs",
        "position": (3, 2),
        "level": 35,
        "prerequisites": ("floating-crystal",),
    },
    {
        "id": "magic-1",
        "kind": "rating",
        "identifier": "Magic",
        "lane": "Constructs",
        "position": (3, 3),
        "prerequisites": ("torchlight",),
    },
    {
        "id": "conjure-elixir",
        "kind": "ability",
        "identifier": "ConjureElixir",
        "lane": "Constructs",
        "position": (3, 4),
        "level": 45,
        "prerequisites": ("magic-1",),
    },
    {
        "id": "barrier-wall",
        "kind": "ability",
        "identifier": "BarrierWall",
        "lane": "Constructs",
        "position": (3, 6),
        "level": 55,
        "prerequisites": ("conjure-elixir",),
    },
    {
        "id": "sleep",
        "kind": "ability",
        "identifier": "Sleep",
        "lane": "Binding",
        "position": (1, 1),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "silence",
        "kind": "ability",
        "identifier": "Silence",
        "lane": "Binding",
        "position": (1, 2),
        "level": 35,
        "prerequisites": ("sleep",),
    },
    {
        "id": "banish",
        "kind": "ability",
        "identifier": "Banish",
        "lane": "Binding",
        "position": (1, 3),
        "level": 40,
        "prerequisites": ("silence",),
    },
    {
        "id": "weaken-mind",
        "kind": "ability",
        "identifier": "WeakenMind",
        "lane": "Binding",
        "position": (1, 4),
        "level": 45,
        "prerequisites": ("banish",),
    },
    {
        "id": "mana-barbs",
        "kind": "ability",
        "identifier": "ManaBarbs",
        "lane": "Binding",
        "position": (1, 6),
        "level": 55,
        "prerequisites": ("weaken-mind",),
    },
    {
        "id": "mirror-image",
        "kind": "ability",
        "identifier": "MirrorImage",
        "lane": "Illusion / Movement",
        "position": (2, 1),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "nightmare-fuel",
        "kind": "ability",
        "identifier": "NightmareFuel",
        "lane": "Illusion / Movement",
        "position": (2, 2),
        "level": 35,
        "prerequisites": ("mirror-image",),
    },
    {
        "id": "volitation",
        "kind": "ability",
        "identifier": "Volitation",
        "lane": "Illusion / Movement",
        "position": (2, 4),
        "level": 45,
        "prerequisites": ("nightmare-fuel",),
    },
    {
        "id": "teleport",
        "kind": "ability",
        "identifier": "Teleport",
        "lane": "Illusion / Movement",
        "position": (2, 5),
        "level": 50,
        "prerequisites": ("volitation",),
    },
    {
        "id": "explosive-decoy",
        "kind": "ability",
        "identifier": "ExplosiveDecoy",
        "lane": "Illusion / Movement",
        "position": (2, 6),
        "level": 55,
        "prerequisites": ("teleport",),
    },
    {
        "id": "conjure-humanoid",
        "kind": "ability",
        "identifier": "ConjureHumanoid",
        "lane": "Calling",
        "position": (0, 1),
        "available_on_promotion": True,
    },
    {
        "id": "conjure-monster",
        "kind": "ability",
        "identifier": "ConjureMonster",
        "lane": "Calling",
        "position": (0, 2),
        "level": 35,
        "prerequisites": ("conjure-humanoid",),
    },
    {
        "id": "conjure-spirit",
        "kind": "ability",
        "identifier": "ConjureSpirit",
        "lane": "Calling",
        "position": (0, 3),
        "level": 40,
        "prerequisites": ("conjure-monster",),
    },
    {
        "id": "conjure-fiend",
        "kind": "ability",
        "identifier": "ConjureFiend",
        "lane": "Calling",
        "position": (0, 4),
        "level": 45,
        "prerequisites": ("conjure-spirit",),
    },
    {
        "id": "conjure-celestial",
        "kind": "ability",
        "identifier": "ConjureCelestial",
        "lane": "Calling",
        "position": (0, 5),
        "level": 50,
        "prerequisites": ("conjure-fiend",),
    },
    {
        "id": "conjure-dragon",
        "kind": "ability",
        "identifier": "ConjureDragon",
        "lane": "Calling",
        "position": (0, 6),
        "level": 55,
        "prerequisites": ("conjure-celestial",),
    },
)

CONJURER_CARRIED_NODE_IDS = frozenset(
    {
        "conjurer.ability.conjure-humanoid",
        "conjurer.ability.conjure-monster",
        "conjurer.ability.conjure-spirit",
        "conjurer.ability.conjure-fiend",
        "conjurer.ability.conjure-celestial",
        "conjurer.ability.conjure-dragon",
    }
)

CONJURER_CARRIED_NODE_POSITIONS = {
    node_id: (2, row)
    for row, node_id in enumerate(
        (
            "conjurer.ability.conjure-humanoid",
            "conjurer.ability.conjure-monster",
            "conjurer.ability.conjure-spirit",
            "conjurer.ability.conjure-fiend",
            "conjurer.ability.conjure-celestial",
            "conjurer.ability.conjure-dragon",
        )
    )
}
