"""Pathfinder-line ability-tree declarations."""

from __future__ import annotations

SHAMAN_TREE_NODE_SPECS = (
    {
        "id": "hydration",
        "kind": "ability",
        "identifier": "Hydration",
        "lane": "Totems",
        "position": (0, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "resonant-ward",
        "kind": "ability",
        "identifier": "ResonantWard",
        "lane": "Totems",
        "position": (0, 1),
        "level": 35,
        "prerequisites": ("hydration",),
    },
    {
        "id": "spirit-mend",
        "kind": "ability",
        "identifier": "SpiritMend",
        "lane": "Totems",
        "position": (0, 2),
        "level": 40,
        "prerequisites": ("resonant-ward",),
    },
    {
        "id": "totem-surge",
        "kind": "ability",
        "identifier": "TotemSurge",
        "lane": "Totems",
        "position": (0, 5),
        "level": 55,
        "owned_if_known": True,
        "prerequisites": ("spirit-mend",),
    },
    {
        "id": "elemental-strike",
        "kind": "ability",
        "identifier": "ElementalStrike",
        "lane": "Elements",
        "position": (1, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "resist-fire",
        "kind": "ability",
        "identifier": "ResistFire",
        "lane": "Elements",
        "position": (1, 1),
        "level": 35,
        "prerequisites": ("elemental-strike",),
    },
    {
        "id": "resist-water",
        "kind": "ability",
        "identifier": "ResistWater",
        "lane": "Elements",
        "position": (1, 2),
        "level": 40,
        "prerequisites": ("resist-fire",),
    },
    {
        "id": "resist-earth",
        "kind": "ability",
        "identifier": "ResistEarth",
        "lane": "Elements",
        "position": (1, 3),
        "level": 45,
        "prerequisites": ("resist-water",),
    },
    {
        "id": "resist-wind",
        "kind": "ability",
        "identifier": "ResistWind",
        "lane": "Elements",
        "position": (1, 4),
        "level": 50,
        "prerequisites": ("resist-earth",),
    },
    {
        "id": "astral-shift",
        "kind": "ability",
        "identifier": "AstralShift",
        "lane": "Elements",
        "position": (1, 5),
        "level": 55,
        "owned_if_known": True,
        "prerequisites": ("resist-wind",),
    },
    {
        "id": "spirit-animal",
        "kind": "ability",
        "identifier": "SpiritAnimal",
        "lane": "Spirit Warrior",
        "position": (2, 0),
        "cost": 2,
        "available_on_promotion": True,
    },
    {
        "id": "piercing-strike",
        "kind": "ability",
        "identifier": "PiercingStrike",
        "lane": "Spirit Warrior",
        "position": (2, 1),
        "level": 35,
        "owned_if_known": True,
        "prerequisites": ("spirit-animal",),
    },
    {
        "id": "maelstrom-weapon",
        "kind": "ability",
        "identifier": "MaelstromWeapon",
        "lane": "Spirit Warrior",
        "position": (2, 2),
        "level": 40,
        "owned_if_known": True,
        "prerequisites": ("piercing-strike",),
    },
    {
        "id": "true-strike",
        "kind": "ability",
        "identifier": "TrueStrike",
        "lane": "Spirit Warrior",
        "position": (2, 3),
        "level": 45,
        "owned_if_known": True,
        "prerequisites": ("maelstrom-weapon",),
    },
    {
        "id": "double-strike",
        "kind": "ability",
        "identifier": "DoubleStrike",
        "lane": "Spirit Warrior",
        "position": (2, 5),
        "level": 55,
        "owned_if_known": True,
        "prerequisites": ("true-strike",),
    },
    {
        "id": "hex",
        "kind": "ability",
        "identifier": "Hex",
        "lane": "Bad Omens",
        "position": (3, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "hexcraft",
        "kind": "talent",
        "identifier": "shaman.hexcraft",
        "name": "Hexcraft",
        "description": "Increase Magic by 10% while cultivating hostile omens.",
        "lane": "Bad Omens",
        "position": (3, 2),
        "level": 40,
        "prerequisites": ("hex",),
        "bonuses": {"rating_percentages": {"Magic": 0.10}},
    },
    {
        "id": "omen-ward",
        "kind": "talent",
        "identifier": "shaman.omen-ward",
        "name": "Omen Ward",
        "description": "Increase Magic Defense by 10% before mastering Bad Omens.",
        "lane": "Bad Omens",
        "position": (3, 4),
        "level": 50,
        "prerequisites": ("hexcraft",),
        "bonuses": {"rating_percentages": {"Magic Defense": 0.10}},
    },
    {
        "id": "bad-omens",
        "kind": "talent",
        "identifier": "shaman.bad-omens",
        "name": "Bad Omens",
        "description": "Enemy misses and your critical hits add dread; three stacks Stun for two turns.",
        "lane": "Bad Omens",
        "position": (3, 5),
        "level": 55,
        "cost": 2,
        "prerequisites": ("omen-ward",),
    },
)


SOULCATCHER_TREE_NODE_SPECS = (
    {
        "id": "soul-drain",
        "kind": "ability",
        "identifier": "SoulDrain",
        "lane": "Soul Dominion",
        "position": (0, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "gentle-reaping",
        "kind": "talent",
        "identifier": "soulcatcher.gentle-reaping",
        "name": "Gentle Reaping",
        "description": "Soul Drain restores health equal to 25% of its nonlethal damage.",
        "lane": "Soul Dominion",
        "position": (0, 1),
        "level": 65,
        "prerequisites": ("soul-drain",),
    },
    {
        "id": "soul-rend",
        "kind": "ability",
        "identifier": "SoulRend",
        "lane": "Soul Dominion",
        "position": (0, 2),
        "level": 70,
        "prerequisites": ("gentle-reaping",),
    },
    {
        "id": "soul-amplifier",
        "kind": "talent",
        "identifier": "soulcatcher.soul-amplifier",
        "name": "Soul Amplifier",
        "description": "Soul Totem pulses gain 10 percentage points of potency.",
        "lane": "Soul Dominion",
        "position": (0, 3),
        "level": 75,
        "prerequisites": ("soul-rend",),
    },
    {
        "id": "desoul",
        "kind": "ability",
        "identifier": "Desoul",
        "lane": "Soul Dominion",
        "position": (0, 4),
        "level": 80,
        "owned_if_known": True,
        "prerequisites": ("soul-amplifier",),
    },
    {
        "id": "death-ward",
        "kind": "talent",
        "identifier": "soulcatcher.death-ward",
        "name": "Death Ward",
        "description": "Gain 15 Magic Defense while the Soul Totem is active.",
        "lane": "Soul Dominion",
        "position": (0, 5),
        "level": 85,
        "prerequisites": ("desoul",),
    },
    {
        "id": "soulstorm",
        "kind": "ability",
        "identifier": "Soulstorm",
        "lane": "Soul Dominion",
        "position": (0, 6),
        "level": 90,
        "cost": 2,
        "prerequisites": ("death-ward",),
    },
    {
        "id": "absorb-essence",
        "kind": "ability",
        "identifier": "AbsorbEssence",
        "lane": "Essence",
        "position": (1, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "discerning-vessel",
        "kind": "talent",
        "identifier": "soulcatcher.discerning-vessel",
        "name": "Discerning Vessel",
        "description": "Increase Absorb Essence's successful harvest chance by 5 percentage points.",
        "lane": "Essence",
        "position": (1, 1),
        "level": 65,
        "prerequisites": ("absorb-essence",),
    },
    {
        "id": "vulcanize",
        "kind": "ability",
        "identifier": "Vulcanize",
        "lane": "Essence",
        "position": (1, 2),
        "level": 70,
        "owned_if_known": True,
        "prerequisites": ("discerning-vessel",),
    },
    {
        "id": "varied-harvest",
        "kind": "talent",
        "identifier": "soulcatcher.varied-harvest",
        "name": "Varied Harvest",
        "description": "Three distinct harvested essence types grant 10 Magic.",
        "lane": "Essence",
        "position": (1, 3),
        "level": 75,
        "prerequisites": ("vulcanize",),
    },
    {
        "id": "essence-shell",
        "kind": "talent",
        "identifier": "soulcatcher.essence-shell",
        "name": "Essence Shell",
        "description": "Five distinct harvested essence types grant 10 Armor.",
        "lane": "Essence",
        "position": (1, 4),
        "level": 80,
        "prerequisites": ("varied-harvest",),
    },
    {
        "id": "perfect-vessel",
        "kind": "talent",
        "identifier": "soulcatcher.perfect-vessel",
        "name": "Perfect Vessel",
        "description": "Seven distinct harvested essence types grant 10 weapon power and Magic Defense.",
        "lane": "Essence",
        "position": (1, 5),
        "level": 85,
        "prerequisites": ("essence-shell",),
    },
    {
        "id": "eternal-harvest",
        "kind": "talent",
        "identifier": "soulcatcher.eternal-harvest",
        "name": "Eternal Harvest",
        "description": "Successful essence absorption also restores 5% maximum MP.",
        "lane": "Essence",
        "position": (1, 6),
        "level": 90,
        "prerequisites": ("perfect-vessel",),
    },
    {
        "id": "totem-surge",
        "kind": "ability",
        "identifier": "TotemSurge",
        "lane": "Ancestral Totem",
        "position": (2, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "deep-resonance",
        "kind": "talent",
        "identifier": "soulcatcher.deep-resonance",
        "name": "Deep Resonance",
        "description": "Increase maximum Totem Resonance by one.",
        "lane": "Ancestral Totem",
        "position": (2, 1),
        "level": 65,
        "prerequisites": ("totem-surge",),
        "kit_effect": ("meter_cap", "totem_resonance", 1),
    },
    {
        "id": "ancestral-aegis",
        "kind": "ability",
        "identifier": "AncestralAegis",
        "lane": "Ancestral Totem",
        "position": (2, 2),
        "level": 70,
        "prerequisites": ("deep-resonance",),
    },
    {
        "id": "resonant-return",
        "kind": "talent",
        "identifier": "soulcatcher.resonant-return",
        "name": "Resonant Return",
        "description": "Totem Surge has a 25% chance to preserve one Resonance.",
        "lane": "Ancestral Totem",
        "position": (2, 3),
        "level": 75,
        "prerequisites": ("ancestral-aegis",),
    },
    {
        "id": "deep-water",
        "kind": "talent",
        "identifier": "shaman.deep-water",
        "name": "Deep Water",
        "description": "Water Totem absorbs 35% rather than 25% spell damage.",
        "lane": "Ancestral Totem",
        "position": (2, 4),
        "level": 80,
        "prerequisites": ("resonant-return",),
    },
    {
        "id": "ancestral-current",
        "kind": "talent",
        "identifier": "soulcatcher.ancestral-current",
        "name": "Ancestral Current",
        "description": "Matching casts gain a 25% chance to add a second Resonance.",
        "lane": "Ancestral Totem",
        "position": (2, 5),
        "level": 85,
        "prerequisites": ("deep-water",),
    },
    {
        "id": "perfect-surge",
        "kind": "talent",
        "identifier": "soulcatcher.perfect-surge",
        "name": "Perfect Surge",
        "description": "Totem Surge resolves at 60% rather than 50% pulse potency.",
        "lane": "Ancestral Totem",
        "position": (2, 6),
        "level": 90,
        "cost": 2,
        "prerequisites": ("ancestral-current",),
    },
    {
        "id": "parry",
        "kind": "ability",
        "identifier": "Parry",
        "lane": "Spirit Warrior",
        "position": (3, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "spirit-claw",
        "kind": "ability",
        "identifier": "SpiritClaw",
        "lane": "Spirit Warrior",
        "position": (3, 1),
        "level": 65,
        "upgrade_without_source": True,
        "prerequisites": ("parry",),
    },
    {
        "id": "triple-strike",
        "kind": "ability",
        "identifier": "TripleStrike",
        "lane": "Spirit Warrior",
        "position": (3, 2),
        "level": 70,
        "owned_if_known": True,
        "upgrade_without_source": True,
        "prerequisites": ("spirit-claw",),
    },
    {
        "id": "haunting-blows",
        "kind": "talent",
        "identifier": "soulcatcher.haunting-blows",
        "name": "Haunting Blows",
        "description": "Weapon critical hits add one Bad Omens dread when that talent is known.",
        "lane": "Spirit Warrior",
        "position": (3, 3),
        "level": 75,
        "prerequisites": ("triple-strike",),
    },
    {
        "id": "dispel",
        "kind": "ability",
        "identifier": "Dispel",
        "lane": "Spirit Warrior",
        "position": (3, 4),
        "level": 80,
        "owned_if_known": True,
        "prerequisites": ("haunting-blows",),
    },
    {
        "id": "true-piercing-strike",
        "kind": "ability",
        "identifier": "TruePiercingStrike",
        "lane": "Spirit Warrior",
        "position": (3, 5),
        "level": 85,
        "owned_if_known": True,
        "upgrade_without_source": True,
        "prerequisites": ("dispel",),
    },
    {
        "id": "spirit-warrior",
        "kind": "talent",
        "identifier": "soulcatcher.spirit-warrior",
        "name": "Spirit Warrior",
        "description": "Gain 10 weapon power while any Totem is active.",
        "lane": "Spirit Warrior",
        "position": (3, 6),
        "level": 90,
        "prerequisites": ("true-piercing-strike",),
    },
)

BEAST_MASTER_TREE_NODE_SPECS = (
    {
        "id": "packstrike",
        "kind": "ability",
        "identifier": "PackStrike",
        "lane": "Pack Tactics",
        "position": (0, 0),
        "available_on_promotion": True,
    },
    {
        "id": "heavy-hunter",
        "kind": "talent",
        "identifier": "beast-master.heavy-hunter",
        "name": "Heavy Hunter",
        "description": "Deal 15% more damage to your quarry with a two-handed main-hand weapon.",
        "lane": "Pack Tactics",
        "position": (0, 1),
        "level": 65,
        "prerequisites": ("packstrike",),
    },
    {
        "id": "coordinated-assault",
        "kind": "talent",
        "identifier": "beast-master.coordinated-assault",
        "name": "Coordinated Assault",
        "description": "Deal 10% more weapon damage to your quarry while your companion is fighting.",
        "lane": "Pack Tactics",
        "position": (0, 2),
        "level": 70,
        "prerequisites": ("heavy-hunter",),
    },
    {
        "id": "alpha-instinct",
        "kind": "talent",
        "identifier": "beast-master.alpha-instinct",
        "name": "Alpha Instinct",
        "description": "Increase the damage, protection, and pressure of companion species traits by 25%.",
        "lane": "Pack Tactics",
        "position": (0, 3),
        "level": 75,
        "prerequisites": ("coordinated-assault",),
    },
    {
        "id": "unleash-instinct",
        "kind": "ability",
        "identifier": "UnleashInstinct",
        "lane": "Pack Tactics",
        "position": (0, 4),
        "level": 80,
        "prerequisites": ("alpha-instinct",),
    },
    {
        "id": "apex-pack",
        "kind": "talent",
        "identifier": "beast-master.apex-pack",
        "name": "Apex Pack",
        "description": "Increase automatic companion action chance by 10 percentage points and its damage by 10%.",
        "lane": "Pack Tactics",
        "position": (0, 5),
        "level": 85,
        "prerequisites": ("unleash-instinct",),
    },
    {
        "id": "zephyrstrike",
        "kind": "ability",
        "identifier": "Zephyrstrike",
        "lane": "Pack Tactics",
        "position": (1, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "harryprey",
        "kind": "ability",
        "identifier": "HarryPrey",
        "lane": "Pack Tactics",
        "position": (1, 1),
        "level": 65,
        "prerequisites": ("zephyrstrike",),
    },
    {
        "id": "trail-guard",
        "kind": "talent",
        "identifier": "beast-master.trail-guard",
        "name": "Trail Guard",
        "description": "Take 10% less damage from your favored enemy type.",
        "lane": "Pack Tactics",
        "position": (1, 2),
        "level": 70,
        "prerequisites": ("harryprey",),
    },
    {
        "id": "crippling-harrier",
        "kind": "talent",
        "identifier": "beast-master.crippling-harrier",
        "name": "Crippling Harrier",
        "description": "Harry Prey also reduces the target's Attack.",
        "lane": "Pack Tactics",
        "position": (1, 3),
        "level": 75,
        "prerequisites": ("trail-guard",),
    },
    {
        "id": "cornered-prey",
        "kind": "talent",
        "identifier": "beast-master.cornered-prey",
        "name": "Cornered Prey",
        "description": "Your companion deals 25% more damage to a wounded favored enemy.",
        "lane": "Pack Tactics",
        "position": (1, 4),
        "level": 80,
        "prerequisites": ("crippling-harrier",),
    },
    {
        "id": "cover",
        "kind": "ability",
        "identifier": "Cover",
        "lane": "Commands",
        "position": (2, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "guardpartner",
        "kind": "ability",
        "identifier": "GuardPartner",
        "lane": "Commands",
        "position": (2, 1),
        "level": 65,
        "prerequisites": ("cover",),
    },
    {
        "id": "beast-master-bonded-bulwark",
        "kind": "talent",
        "identifier": "beast-master.bonded-bulwark",
        "name": "Bonded Bulwark",
        "description": "Increase the companion's bond-derived combat bonus by 10 percentage points.",
        "lane": "Commands",
        "position": (2, 2),
        "level": 70,
        "prerequisites": ("guardpartner",),
    },
    {
        "id": "mendwounds",
        "kind": "ability",
        "identifier": "MendWounds",
        "lane": "Commands",
        "position": (2, 3),
        "level": 75,
        "prerequisites": ("beast-master-bonded-bulwark",),
    },
    {
        "id": "field-dressing",
        "kind": "talent",
        "identifier": "beast-master.field-dressing",
        "name": "Field Dressing",
        "description": "Mend Wounds also removes one harmful physical condition.",
        "lane": "Commands",
        "position": (2, 4),
        "level": 80,
        "prerequisites": ("mendwounds",),
    },
    {
        "id": "guardian-pack",
        "kind": "talent",
        "identifier": "beast-master.guardian-pack",
        "name": "Guardian Pack",
        "description": "Strengthen Guard Partner and let Mend Wounds restore both partners.",
        "lane": "Commands",
        "position": (2, 5),
        "level": 85,
        "prerequisites": ("field-dressing",),
    },
    {
        "id": "rally-partner",
        "kind": "ability",
        "identifier": "RallyPartner",
        "lane": "Commands",
        "position": (3, 0),
        "available_on_promotion": True,
    },
    {
        "id": "commanders-voice",
        "kind": "talent",
        "identifier": "beast-master.commanders-voice",
        "name": "Commander's Voice",
        "description": "Increase the damage, healing, protection, and pressure of companion commands by 15%.",
        "lane": "Commands",
        "position": (3, 1),
        "level": 65,
        "prerequisites": ("rally-partner",),
    },
    {
        "id": "adaptive-orders",
        "kind": "talent",
        "identifier": "beast-master.adaptive-orders",
        "name": "Adaptive Orders",
        "description": "Commands used against your quarry gain one turn of duration.",
        "lane": "Commands",
        "position": (3, 2),
        "level": 70,
        "prerequisites": ("commanders-voice",),
    },
    {
        "id": "perfect-coordination",
        "kind": "talent",
        "identifier": "beast-master.perfect-coordination",
        "name": "Perfect Coordination",
        "description": "Pack Strike triggers the companion's species trait even when its weapon attack misses.",
        "lane": "Commands",
        "position": (3, 3),
        "level": 75,
        "prerequisites": ("adaptive-orders",),
    },
    {
        "id": "true-bond",
        "kind": "talent",
        "identifier": "beast-master.true-bond",
        "name": "True Bond",
        "description": "Increase the companion's bond-derived combat bonus by a further 10 percentage points.",
        "lane": "Commands",
        "position": (3, 4),
        "level": 80,
        "prerequisites": ("perfect-coordination",),
    },
)


RANGER_TREE_NODE_SPECS = (
    {
        "id": "favored-enemy",
        "kind": "ability",
        "identifier": "FavoredEnemy",
        "lane": "Hunt",
        "position": (0, 0),
        "available_on_promotion": True,
    },
    {
        "id": "wild-sense",
        "kind": "ability",
        "identifier": "WildSense",
        "lane": "Hunt",
        "position": (0, 1),
        "level": 35,
        "prerequisites": ("favored-enemy",),
    },
    {
        "id": "relentless-tracker",
        "kind": "talent",
        "identifier": "ranger.relentless-tracker",
        "name": "Relentless Tracker",
        "description": "Retain half your Tracking Mastery instead of one third when changing quarry.",
        "lane": "Hunt",
        "position": (0, 2),
        "level": 40,
        "prerequisites": ("wild-sense",),
    },
    {
        "id": "quarrys-bane",
        "kind": "talent",
        "identifier": "ranger.quarrys-bane",
        "name": "Quarry's Bane",
        "description": "Deal 10% more weapon and crossbow damage to your favored enemy type.",
        "lane": "Hunt",
        "position": (0, 3),
        "level": 45,
        "prerequisites": ("relentless-tracker",),
    },
    {
        "id": "aggressive-pursuit",
        "kind": "ability",
        "identifier": "AggressivePursuit",
        "lane": "Hunt",
        "position": (0, 4),
        "level": 50,
        "prerequisites": ("quarrys-bane",),
    },
    {
        "id": "apex-hunter",
        "kind": "talent",
        "identifier": "ranger.apex-hunter",
        "name": "Apex Hunter",
        "description": "At Mastered Trail, deal a further 10% weapon and crossbow damage to your quarry.",
        "lane": "Hunt",
        "position": (0, 5),
        "level": 55,
        "prerequisites": ("aggressive-pursuit",),
    },
    {
        "id": "detect-animal",
        "kind": "ability",
        "identifier": "DetectAnimal",
        "lane": "Companion Bond",
        "position": (1, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "creature-comforts",
        "kind": "ability",
        "identifier": "CreatureComforts",
        "lane": "Companion Bond",
        "position": (1, 1),
        "level": 35,
        "owned_if_known": True,
        "prerequisites": ("detect-animal",),
    },
    {
        "id": "kindred-instinct",
        "kind": "talent",
        "identifier": "ranger.kindred-instinct",
        "name": "Kindred Instinct",
        "description": "Your tamed companion can use its species trait at 15 bond instead of 25.",
        "lane": "Companion Bond",
        "position": (1, 2),
        "level": 40,
        "prerequisites": ("creature-comforts",),
    },
    {
        "id": "pack-tactics",
        "kind": "talent",
        "identifier": "ranger.pack-tactics",
        "name": "Pack Tactics",
        "description": "Your tamed companion deals 20% more damage to your favored enemy type.",
        "lane": "Companion Bond",
        "position": (1, 4),
        "level": 50,
        "prerequisites": ("kindred-instinct", "quarrys-bane"),
        "prerequisite_mode": "any",
    },
    {
        "id": "companion-bond",
        "kind": "talent",
        "identifier": "ranger.companion-bond",
        "name": "Companion Bond",
        "description": "Increase the companion's bond-derived combat bonus by 5 percentage points.",
        "lane": "Companion Bond",
        "position": (1, 5),
        "level": 55,
        "prerequisites": ("pack-tactics",),
    },
    {
        "id": "duelist",
        "kind": "ability",
        "identifier": "Duelist",
        "lane": "Duelist / Ranged",
        "position": (2, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "crossbow-training",
        "kind": "talent",
        "identifier": "ranger.crossbow-training",
        "name": "Crossbow Training",
        "description": "Gain 10% crossbow accuracy. Ranger Duelist remains active with a crossbow off hand.",
        "lane": "Duelist / Ranged",
        "position": (2, 1),
        "level": 35,
        "prerequisites": ("duelist",),
    },
    {
        "id": "vision",
        "kind": "ability",
        "identifier": "Vision",
        "lane": "Duelist / Ranged",
        "position": (2, 2),
        "level": 40,
        "owned_if_known": True,
        "prerequisites": ("crossbow-training",),
    },
    {
        "id": "uncanny-volley",
        "kind": "ability",
        "identifier": "UncannyVolley",
        "lane": "Duelist / Ranged",
        "position": (2, 3),
        "level": 45,
        "prerequisites": ("vision",),
    },
    {
        "id": "quick-reload",
        "kind": "talent",
        "identifier": "ranger.quick-reload",
        "name": "Quick Reload",
        "description": "Add 20 percentage points to the recovery chance of fired crossbow bolts.",
        "lane": "Duelist / Ranged",
        "position": (2, 4),
        "level": 50,
        "prerequisites": ("uncanny-volley",),
    },
    {
        "id": "two-handed-proficiency",
        "kind": "ability",
        "identifier": "TwoHandedWeaponProficiency",
        "lane": "Two-Handed Fighting",
        "position": (3, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "quarry-cleave",
        "kind": "ability",
        "identifier": "QuarryCleave",
        "lane": "Two-Handed Fighting",
        "position": (3, 1),
        "level": 35,
        "prerequisites": ("two-handed-proficiency",),
    },
    {
        "id": "true-strike",
        "kind": "ability",
        "identifier": "TrueStrike",
        "lane": "Two-Handed Fighting",
        "position": (3, 2),
        "level": 40,
        "owned_if_known": True,
        "prerequisites": ("quarry-cleave",),
    },
    {
        "id": "braced-grip",
        "kind": "talent",
        "identifier": "ranger.braced-grip",
        "name": "Braced Grip",
        "description": "Reduce physical damage by 8% while wielding a two-handed main-hand weapon.",
        "lane": "Two-Handed Fighting",
        "position": (3, 3),
        "level": 45,
        "prerequisites": ("true-strike",),
    },
    {
        "id": "parry",
        "kind": "ability",
        "identifier": "Parry",
        "lane": "Defense",
        "position": (4, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "combo-breaker",
        "kind": "talent",
        "identifier": "ranger.combo-breaker",
        "name": "Combo Breaker",
        "description": "Each hit after the first in one enemy action takes 8% less damage, stacking to 32%.",
        "lane": "Defense",
        "position": (4, 1),
        "level": 35,
        "prerequisites": ("parry",),
    },
    {
        "id": "hunters-snare",
        "kind": "ability",
        "identifier": "HuntersSnare",
        "lane": "Defense",
        "position": (4, 2),
        "level": 40,
        "prerequisites": ("combo-breaker",),
    },
    {
        "id": "companion-cover",
        "kind": "talent",
        "identifier": "ranger.companion-cover",
        "name": "Companion Cover",
        "description": "Take 8% less damage while your active tamed companion is alive.",
        "lane": "Defense",
        "position": (4, 3),
        "level": 45,
        "prerequisites": ("hunters-snare",),
    },
)


def _pathfinder_kit_column(
    lane,
    column,
    stage,
    entries,
):
    """Build one compact authored Pathfinder promotion discipline."""
    levels = (None, 35, 40, 45, 50, 55, 55) if stage == 2 else (None, 65, 70, 75, 80, 85, 90)
    specs = []
    previous = None
    for row, entry in enumerate(entries):
        if entry is None:
            continue
        suffix, kind, identifier, name, description, rating, cost = entry
        spec = {
            "id": suffix,
            "kind": kind,
            "identifier": identifier,
            "lane": lane,
            "position": (column, row),
        }
        if previous:
            spec["prerequisites"] = (previous,)
        if row == 0:
            spec["available_on_promotion"] = True
            spec["owned_if_known"] = kind == "ability"
        elif levels[row] is not None:
            spec["level"] = levels[row]
        if name is not None:
            spec["name"] = name
        if description is not None:
            spec["description"] = description
        if rating is not None:
            spec["bonuses"] = {"rating_percentages": {rating: 0.10}}
        if cost != 1:
            spec["cost"] = cost
        specs.append(spec)
        previous = suffix
    return tuple(specs)


DRUID_TREE_NODE_SPECS = (
    *_pathfinder_kit_column(
        "Panther Form",
        0,
        2,
        (
            ("transform", "ability", "Transform", None, None, None, 1),
            ("predator-instinct", "rating", "Attack", None, None, None, 1),
            (
                "feline-grace",
                "talent",
                "druid.feline-grace",
                "Feline Grace",
                "Increase Attack by 10%; Panther form remains the precision route.",
                "Attack",
                1,
            ),
            ("mortalstrike", "ability", "MortalStrike", None, None, None, 1),
            (
                "razor-ambush",
                "talent",
                "druid.razor-ambush",
                "Razor Ambush",
                "Increase Attack by 10% and sharpen transformed opening pressure.",
                "Attack",
                1,
            ),
            (
                "apex-prowler",
                "talent",
                "druid.apex-prowler",
                "Apex Prowler",
                "Increase Attack by 10% after mastering the Panther discipline.",
                "Attack",
                1,
            ),
        ),
    ),
    *_pathfinder_kit_column(
        "Direbear Form",
        1,
        2,
        (
            ("transform2", "ability", "Transform2", None, None, None, 1),
            (
                "thick-hide",
                "talent",
                "druid.thick-hide",
                "Thick Hide",
                "Increase Defense by 10%; Direbear form remains the protection route.",
                "Defense",
                1,
            ),
            ("bear-fortitude", "rating", "Defense", None, None, None, 1),
            (
                "bearish-might",
                "talent",
                "druid.bearish-might",
                "Bearish Might",
                "Increase Attack by 10% while developing Direbear pressure.",
                "Attack",
                1,
            ),
            (
                "rooted-guard",
                "talent",
                "druid.rooted-guard",
                "Rooted Guard",
                "Increase Magic Defense by 10% against hostile magic.",
                "Magic Defense",
                1,
            ),
            (
                "guardian-beast",
                "talent",
                "druid.guardian-beast",
                "Guardian Beast",
                "Increase Defense by 10% after mastering the Direbear discipline.",
                "Defense",
                1,
            ),
        ),
    ),
    *_pathfinder_kit_column(
        "Venom and Stone",
        2,
        2,
        (
            ("poisondart", "ability", "PoisonDart", None, None, None, 1),
            ("ritual-potency", "rating", "Magic", None, None, None, 1),
            ("resist-poison", "ability", "ResistPoison", None, None, None, 1),
            ("noxious-mist", "ability", "NoxiousMist", None, None, None, 1),
            ("stoneskin", "ability", "StoneSkin", None, None, None, 1),
            (
                "earthen-toxins",
                "talent",
                "druid.earthen-toxins",
                "Earthen Toxins",
                "Increase Magic by 10% to reinforce poison and stone rites.",
                "Magic",
                1,
            ),
        ),
    ),
    *_pathfinder_kit_column(
        "Growth and Stars",
        3,
        2,
        (
            ("regrowth", "ability", "Regrowth", None, None, None, 1),
            ("restoring-boon", "ability", "RestoringBoon", None, None, None, 1),
            ("calmingbreeze", "ability", "CalmingBreeze", None, None, None, 1),
            ("natural-aegis", "rating", "Magic Defense", None, None, None, 1),
            (
                "seasonal-rite",
                "talent",
                "druid.seasonal-rite",
                "Seasonal Rite",
                "Increase Magic by 10% after mastering restorative and stellar rites.",
                "Magic",
                1,
            ),
            ("starfall", "ability", "Starfall", None, None, None, 1),
        ),
    ),
    *_pathfinder_kit_column(
        "Primal Practice",
        4,
        2,
        (
            ("primal-practice", "ability", "PrimalPractice", None, None, None, 1),
            ("primal-vitality", "health", "Health", None, None, None, 1),
            ("primal-reserve", "mana", "Mana", None, None, None, 1),
            (
                "primal-versatility",
                "talent",
                "druid.primal-versatility",
                "Primal Versatility",
                "Increase Magic Defense by 10% across forms and nature rites.",
                "Magic Defense",
                1,
            ),
        ),
    ),
)

DIVINER_TREE_NODE_SPECS = (
    *_pathfinder_kit_column(
        "Rune Lore",
        0,
        2,
        (
            ("vulcanize", "ability", "Vulcanize", None, None, None, 1),
            ("rune-potency", "rating", "Magic", None, None, None, 1),
            ("enfeeble", "ability", "Enfeeble", None, None, None, 1),
            (
                "elemental-script",
                "talent",
                "diviner.elemental-script",
                "Elemental Script",
                "Increase Magic by 10% while studying natural-element signs.",
                "Magic",
                1,
            ),
            ("dispel", "ability", "Dispel", None, None, None, 1),
            (
                "open-sigils",
                "talent",
                "diviner.open-sigils",
                "Open Sigils",
                "Increase Magic by 10% and improve natural-element rune acquisition.",
                "Magic",
                1,
            ),
        ),
    ),
    *_pathfinder_kit_column(
        "Rune Flow",
        1,
        2,
        (
            ("haste", "ability", "Haste", None, None, None, 1),
            ("rune-ward", "rating", "Magic Defense", None, None, None, 1),
            (
                "quick-inscription",
                "talent",
                "diviner.quick-inscription",
                "Quick Inscription",
                "Increase Magic Defense by 10% while preparing runic casts.",
                "Magic Defense",
                1,
            ),
            (
                "runic-focus",
                "talent",
                "diviner.runic-focus",
                "Runic Focus",
                "Increase Magic by 10% to reinforce Runic Boost output.",
                "Magic",
                1,
            ),
            (
                "balanced-grid",
                "talent",
                "diviner.balanced-grid",
                "Balanced Grid",
                "Increase Magic Defense by 10% after mastering rune flow.",
                "Magic Defense",
                1,
            ),
            ("doublecast", "ability", "Doublecast", None, None, None, 1),
        ),
    ),
    *_pathfinder_kit_column(
        "Foresight",
        2,
        2,
        (
            ("learnspell", "ability", "LearnSpell", None, None, None, 1),
            None,
            (
                "pattern-memory",
                "talent",
                "diviner.pattern-memory",
                "Pattern Memory",
                "Increase Magic by 10% while retaining witnessed rank-one patterns.",
                "Magic",
                1,
            ),
            (
                "clear-omen",
                "talent",
                "diviner.clear-omen",
                "Clear Omen",
                "Increase Magic Defense by 10% through defensive prediction.",
                "Magic Defense",
                1,
            ),
            (
                "witnessed-certainty",
                "talent",
                "diviner.witnessed-certainty",
                "Witnessed Certainty",
                "Increase Magic by 10% after mastering witnessed spellcraft.",
                "Magic",
                1,
            ),
            ("berserk", "ability", "Berserk", None, None, None, 1),
        ),
    ),
    *_pathfinder_kit_column(
        "Chronomancy",
        3,
        2,
        (
            None,
            (
                "held-moment",
                "talent",
                "diviner.held-moment",
                "Held Moment",
                "Increase Magic Defense by 10% while controlling hostile tempo.",
                "Magic Defense",
                1,
            ),
            ("chronal-guard", "rating", "Defense", None, None, None, 1),
            (
                "protected-future",
                "talent",
                "diviner.protected-future",
                "Protected Future",
                "Increase Defense by 10% through anticipated movement.",
                "Defense",
                1,
            ),
            (
                "far-sight",
                "talent",
                "diviner.far-sight",
                "Far Sight",
                "Increase Magic by 10% after mastering the chronomancy discipline.",
                "Magic",
                1,
            ),
            ("temporary-stasis", "ability", "TemporaryStasis", None, None, None, 1),
        ),
    ),
)

ARCHDRUID_TREE_NODE_SPECS = (
    *_pathfinder_kit_column(
        "Venom",
        0,
        3,
        (
            ("vilepotion", "ability", "VilePotion", None, None, None, 1),
            (
                "patient-venom",
                "talent",
                "archdruid.patient-venom",
                "Patient Venom",
                "Increase Magic by 10% while cultivating Venom attunement.",
                "Magic",
                1,
            ),
            ("poison-breath", "ability", "PoisonBreath", None, None, None, 1),
            (
                "toxic-memory",
                "talent",
                "archdruid.toxic-memory",
                "Toxic Memory",
                "Increase Magic Defense by 10% after surviving poison.",
                "Magic Defense",
                1,
            ),
            (
                "serpents-patience",
                "talent",
                "archdruid.serpents-patience",
                "Serpent's Patience",
                "Increase Magic by 10% for deliberate poison pressure.",
                "Magic",
                1,
            ),
            (
                "venom-aspect",
                "talent",
                "archdruid.venom-aspect",
                "Venom Aspect",
                "Increase Magic by 10% as the Venom aspect approaches mastery.",
                "Magic",
                1,
            ),
            (
                "venom-incarnate",
                "talent",
                "archdruid.venom-incarnate",
                "Venom Incarnate",
                "Increase Magic by 10% after completing the Venom discipline.",
                "Magic",
                2,
            ),
        ),
    ),
    *_pathfinder_kit_column(
        "Stone",
        1,
        3,
        (
            ("natureshield", "ability", "NatureShield", None, None, None, 1),
            (
                "granite-memory",
                "talent",
                "archdruid.granite-memory",
                "Granite Memory",
                "Increase Defense by 10% while cultivating Stone attunement.",
                "Defense",
                1,
            ),
            (
                "rooted-bastion",
                "talent",
                "archdruid.rooted-bastion",
                "Rooted Bastion",
                "Increase Magic Defense by 10% against control magic.",
                "Magic Defense",
                1,
            ),
            (
                "unyielding-crust",
                "talent",
                "archdruid.unyielding-crust",
                "Unyielding Crust",
                "Increase Defense by 10% after surviving physical blows.",
                "Defense",
                1,
            ),
            (
                "standing-stone",
                "talent",
                "archdruid.standing-stone",
                "Standing Stone",
                "Increase Defense by 10% for sustained protection.",
                "Defense",
                1,
            ),
            (
                "stone-aspect",
                "talent",
                "archdruid.stone-aspect",
                "Stone Aspect",
                "Increase Magic Defense by 10% as the Stone aspect approaches mastery.",
                "Magic Defense",
                1,
            ),
            (
                "mountain-incarnate",
                "talent",
                "archdruid.mountain-incarnate",
                "Mountain Incarnate",
                "Increase Defense by 10% after completing the Stone discipline.",
                "Defense",
                2,
            ),
        ),
    ),
    *_pathfinder_kit_column(
        "Growth",
        2,
        3,
        (
            ("plantseeds", "ability", "PlantSeeds", None, None, None, 1),
            (
                "verdant-memory",
                "talent",
                "archdruid.verdant-memory",
                "Verdant Memory",
                "Increase Magic by 10% while cultivating Growth attunement.",
                "Magic",
                1,
            ),
            ("expel-curse", "ability", "ExpelCurse", None, None, None, 1),
            ("grove-pulse", "ability", "GrovePulse", None, None, None, 1),
            (
                "deep-roots",
                "talent",
                "archdruid.deep-roots",
                "Deep Roots",
                "Increase Magic Defense by 10% for sustained Growth magic.",
                "Magic Defense",
                1,
            ),
            (
                "growth-aspect",
                "talent",
                "archdruid.growth-aspect",
                "Growth Aspect",
                "Increase Magic by 10% as the Growth aspect approaches mastery.",
                "Magic",
                1,
            ),
            (
                "world-tree-scion",
                "talent",
                "archdruid.world-tree-scion",
                "World-Tree Scion",
                "Increase Magic by 10% after completing the Growth discipline.",
                "Magic",
                1,
            ),
        ),
    ),
    *_pathfinder_kit_column(
        "Storm",
        3,
        3,
        (
            ("bolt", "ability", "Bolt", None, None, None, 1),
            ("windswept", "ability", "Windswept", None, None, None, 1),
            (
                "storm-memory",
                "talent",
                "archdruid.storm-memory",
                "Storm Memory",
                "Increase Magic by 10% while cultivating Storm attunement.",
                "Magic",
                1,
            ),
            ("balllightning", "ability", "BallLightning", None, None, None, 1),
            (
                "eye-of-storm",
                "talent",
                "archdruid.eye-of-storm",
                "Eye of the Storm",
                "Increase Magic Defense by 10% amid elemental pressure.",
                "Magic Defense",
                1,
            ),
            (
                "storm-aspect",
                "talent",
                "archdruid.storm-aspect",
                "Storm Aspect",
                "Increase Magic by 10% as the Storm aspect approaches mastery.",
                "Magic",
                1,
            ),
            ("fourfoldsurge", "ability", "FourfoldSurge", None, None, None, 1),
        ),
    ),
)

LYCAN_TREE_NODE_SPECS = (
    *_pathfinder_kit_column(
        "Frenzy",
        0,
        3,
        (
            ("transform3", "ability", "Transform3", None, None, None, 1),
            (
                "blood-scent",
                "talent",
                "lycan.blood-scent",
                "Blood Scent",
                "Increase Attack by 10% while hunting in Werewolf form.",
                "Attack",
                1,
            ),
            ("charge", "ability", "Charge", None, None, None, 1),
            (
                "frenzied-force",
                "talent",
                "lycan.frenzied-force",
                "Frenzied Force",
                "Increase Attack by 10% and deepen Frenzy's offensive payoff.",
                "Attack",
                1,
            ),
            ("battlecry", "ability", "BattleCry", None, None, None, 1),
            (
                "red-tooth",
                "talent",
                "lycan.red-tooth",
                "Red Tooth",
                "Increase Attack by 10% during transformed pressure.",
                "Attack",
                1,
            ),
            (
                "moon-ravager",
                "talent",
                "lycan.moon-ravager",
                "Moon Ravager",
                "Increase Attack by 10% after completing the Frenzy discipline.",
                "Attack",
                2,
            ),
        ),
    ),
    *_pathfinder_kit_column(
        "Moon Hunt",
        1,
        3,
        (
            ("mortalstrike2", "ability", "MortalStrike2", None, None, None, 1),
            ("lunar-rend", "ability", "LunarRend", None, None, None, 1),
            (
                "lunar-pursuit",
                "talent",
                "lycan.lunar-pursuit",
                "Lunar Pursuit",
                "Increase Defense by 10% while pursuing marked prey.",
                "Defense",
                1,
            ),
            (
                "full-moon-fury",
                "talent",
                "lycan.full-moon-fury",
                "Full Moon Fury",
                "Increase Attack by 10% at the most dangerous lunar peak.",
                "Attack",
                1,
            ),
            (
                "waning-guard",
                "talent",
                "lycan.waning-guard",
                "Waning Guard",
                "Increase Defense by 10% while the moon recedes.",
                "Defense",
                1,
            ),
            (
                "relentless-hunt",
                "talent",
                "lycan.relentless-hunt",
                "Relentless Hunt",
                "Increase Attack by 10% for sustained transformed combat.",
                "Attack",
                1,
            ),
            (
                "lunar-apex",
                "talent",
                "lycan.lunar-apex",
                "Lunar Apex",
                "Increase Attack by 10% after completing the Moon Hunt discipline.",
                "Attack",
                2,
            ),
        ),
    ),
    *_pathfinder_kit_column(
        "Dragon Essence",
        2,
        3,
        (
            ("wingedpounce", "ability", "WingedPounce", None, None, None, 1),
            (
                "scaled-hide",
                "talent",
                "lycan.scaled-hide",
                "Scaled Hide",
                "Increase Defense by 10% while channeling Dragon Essence.",
                "Defense",
                1,
            ),
            (
                "draconic-lift",
                "talent",
                "lycan.draconic-lift",
                "Draconic Lift",
                "Increase Attack by 10% for Winged Pounce follow-through.",
                "Attack",
                1,
            ),
            ("dragon-fang", "ability", "DragonFang", None, None, None, 1),
            (
                "sky-predator",
                "talent",
                "lycan.sky-predator",
                "Sky Predator",
                "Increase Defense by 10% during airborne pressure.",
                "Defense",
                1,
            ),
            (
                "ancient-essence",
                "talent",
                "lycan.ancient-essence",
                "Ancient Essence",
                "Increase Magic Defense by 10% against hostile elements.",
                "Magic Defense",
                1,
            ),
            (
                "dragon-wolf",
                "talent",
                "lycan.dragon-wolf",
                "Dragon-Wolf",
                "Increase Attack by 10% after completing the Dragon Essence discipline.",
                "Attack",
                1,
            ),
        ),
    ),
    *_pathfinder_kit_column(
        "Control",
        3,
        3,
        (
            ("dispel", "ability", "Dispel", None, None, None, 1),
            (
                "measured-breath",
                "talent",
                "lycan.measured-breath",
                "Measured Breath",
                "Increase Magic Defense by 10% without granting control ranks.",
                "Magic Defense",
                1,
            ),
            (
                "muzzled-instinct",
                "talent",
                "lycan.muzzled-instinct",
                "Muzzled Instinct",
                "Increase Defense by 10% while resisting Frenzy.",
                "Defense",
                1,
            ),
            (
                "restive-guard",
                "talent",
                "lycan.restive-guard",
                "Restive Guard",
                "Increase Defense by 10% during deliberate transformed defense.",
                "Defense",
                1,
            ),
            ("center-the-beast", "ability", "CenterBeast", None, None, None, 1),
            (
                "tame-heart",
                "talent",
                "lycan.tame-heart",
                "Tame Heart",
                "Increase Defense by 10%; control ranks remain behavior-earned.",
                "Defense",
                1,
            ),
            (
                "self-possessed",
                "talent",
                "lycan.self-possessed",
                "Self-Possessed",
                "Increase Magic Defense by 10% after completing the Control discipline.",
                "Magic Defense",
                1,
            ),
        ),
    ),
)

ASTROMANCER_TREE_NODE_SPECS = (
    *_pathfinder_kit_column(
        "Foresight Threads",
        0,
        3,
        (
            ("foretell", "ability", "Foretell", None, None, None, 1),
            (
                "thread-spinner",
                "talent",
                "astromancer.thread-spinner",
                "Thread Spinner",
                "Increase Magic by 10% while generating Foresight Threads.",
                "Magic",
                1,
            ),
            ("twistfate", "ability", "TwistFate", None, None, None, 1),
            ("threadedcast", "ability", "ThreadedCast", None, None, None, 1),
            (
                "woven-certainty",
                "talent",
                "astromancer.woven-certainty",
                "Woven Certainty",
                "Increase Magic by 10% for Threaded Cast output.",
                "Magic",
                1,
            ),
            ("rewind", "ability", "Rewind", None, None, None, 1),
            (
                "fate-loom",
                "talent",
                "astromancer.fate-loom",
                "Fate Loom",
                "Increase Magic by 10% without altering Rewind's safety rules.",
                "Magic",
                2,
            ),
        ),
    ),
    *_pathfinder_kit_column(
        "Runic Constellations",
        1,
        3,
        (
            ("vulcanize", "ability", "Vulcanize", None, None, None, 1),
            (
                "stellar-script",
                "talent",
                "astromancer.stellar-script",
                "Stellar Script",
                "Increase Magic by 10% while aligning natural runes.",
                "Magic",
                1,
            ),
            ("weakenmind", "ability", "WeakenMind", None, None, None, 1),
            ("boost", "ability", "Boost", None, None, None, 1),
            ("learnspell2", "ability", "LearnSpell2", None, None, None, 1),
            (
                "active-sign",
                "talent",
                "astromancer.active-sign",
                "Active Sign",
                "Increase Magic by 10% while cycling the active constellation.",
                "Magic",
                1,
            ),
            (
                "celestial-runes",
                "talent",
                "astromancer.celestial-runes",
                "Celestial Runes",
                "Increase Magic by 10% after completing the runic discipline.",
                "Magic",
                2,
            ),
        ),
    ),
    *_pathfinder_kit_column(
        "Celestial Force",
        2,
        3,
        (
            ("wormhole", "ability", "Wormhole", None, None, None, 1),
            (
                "astral-anchor",
                "talent",
                "astromancer.astral-anchor",
                "Astral Anchor",
                "Increase Magic Defense by 10% while opening a Wormhole.",
                "Magic Defense",
                1,
            ),
            ("triplecast", "ability", "Triplecast", None, None, None, 1),
            (
                "meteor-logic",
                "talent",
                "astromancer.meteor-logic",
                "Meteor Logic",
                "Increase Magic by 10% for celestial area pressure.",
                "Magic",
                1,
            ),
            (
                "astral-judgment",
                "talent",
                "astromancer.astral-judgment",
                "Celestial Mastery",
                "Increase Magic by 10% after completing the celestial discipline.",
                "Magic",
                1,
            ),
        ),
    ),
    *_pathfinder_kit_column(
        "Lucid Utility",
        3,
        3,
        (
            ("access-storage", "ability", "AccessStorage", None, None, None, 1),
            (
                "weightless-reach",
                "talent",
                "astromancer.weightless-reach",
                "Weightless Reach",
                "Increase Magic Defense by 10% while reaching beyond the dungeon.",
                "Magic Defense",
                1,
            ),
            ("silent-lucidity", "ability", "SilentLucidity", None, None, None, 1),
            (
                "dream-calculus",
                "talent",
                "astromancer.dream-calculus",
                "Dream Calculus",
                "Increase Magic by 10% while lucid spellcasting is available.",
                "Magic",
                1,
            ),
            (
                "sleepwalker-ward",
                "talent",
                "astromancer.sleepwalker-ward",
                "Sleepwalker Ward",
                "Increase Defense by 10% against waking threats.",
                "Defense",
                1,
            ),
            (
                "remote-cache",
                "talent",
                "astromancer.remote-cache",
                "Remote Cache",
                "Increase Magic Defense by 10% for remote dungeon utility.",
                "Magic Defense",
                1,
            ),
            (
                "lucid-horizon",
                "talent",
                "astromancer.lucid-horizon",
                "Lucid Horizon",
                "Increase Magic by 10% after completing the lucid discipline.",
                "Magic",
                1,
            ),
        ),
    ),
    {
        "id": "tephra",
        "kind": "ability",
        "identifier": "Tephra",
        "lane": "Witnessed Magic",
        "position": (4, 4),
        "level": 80,
        "cost": 1,
        "prerequisites": ("learnspell2",),
    },
)
