"""Warrior-line ability-tree declarations."""

from __future__ import annotations

# The Warrior tree is the first fully authored talent graph. Each tuple is:
# path name, promotion target, then ordered node specs of
# (kind, payload identifier, icon key). Path names remain useful metadata for
# diagnostics but are intentionally not rendered above Pygame columns.
WARRIOR_TREE_PATHS = (
    (
        "Arms",
        "Weapon Master",
        (
            ("ability", "PiercingStrike", "skill_offense"),
            ("ability", "Charge", "skill_mobility"),
            ("ability", "WeaponFocus", "skill_passive"),
            ("rating", "Attack", "rating_attack"),
            ("ability", "Cripple", "skill_control"),
            ("ability", "TrueStrike", "skill_offense"),
        ),
    ),
    (
        "Vanguard",
        "Lancer",
        (
            ("ability", "HonedAttack", "skill_passive"),
            ("ability", "DrivingThrust", "skill_offense"),
            ("rating", "Defense", "rating_defense"),
            ("ability", "Retaliate", "skill_defense"),
        ),
    ),
    (
        "Bulwark",
        "Sentinel",
        (
            ("ability", "ShieldSlam", "skill_defense"),
            ("ability", "ShieldBlock", "skill_defense"),
            ("ability", "Rally", "skill_support"),
            ("rating", "Defense", "rating_defense"),
            ("ability", "Dishearten", "skill_control"),
            ("ability", "AggressivePursuit", "skill_passive"),
        ),
    ),
    (
        "Command",
        "Paladin",
        (
            ("ability", "Goad", "skill_control"),
            ("ability", "Chastise", "skill_passive"),
            ("rating", "Magic Defense", "rating_magic_defense"),
            ("ability", "Commitment", "skill_passive"),
        ),
    ),
)

# Paladin begins after the shared Bulwark/Command trunk has reached row three.
WARRIOR_PATH_ROW_OFFSETS = {}

# Explicit geometry lets the defensive paths share a central trunk while
# keeping Shield Slam as an early Sentinel/Lancer side requirement.
WARRIOR_NODE_POSITION_OVERRIDES = {
    ("Weapon Master", "PiercingStrike"): (0.5, 0),
    ("Weapon Master", "Charge"): (0.5, 1),
    ("Weapon Master", "WeaponFocus"): (0, 2),
    ("Weapon Master", "Attack"): (0, 3),
    ("Weapon Master", "Cripple"): (0, 4),
    ("Weapon Master", "TrueStrike"): (0, 5),
    ("Lancer", "HonedAttack"): (1, 2),
    ("Lancer", "DrivingThrust"): (1, 3),
    ("Lancer", "Defense"): (1, 4),
    ("Lancer", "Retaliate"): (1, 5),
    ("Sentinel", "ShieldSlam"): (2.5, 0),
    ("Sentinel", "ShieldBlock"): (2.5, 1),
    ("Sentinel", "Rally"): (2, 2),
    ("Sentinel", "Defense"): (2, 3),
    ("Sentinel", "Dishearten"): (2, 4),
    ("Sentinel", "AggressivePursuit"): (2, 5),
    ("Paladin", "Goad"): (3, 2),
    ("Paladin", "Chastise"): (3, 3),
    ("Paladin", "Magic Defense"): (3, 4),
    ("Paladin", "Commitment"): (3, 5),
}

WARRIOR_FLOATING_NODES = (
    ("ability", "Disarm", "skill_control", (4, 0), None),
    ("rating", "Defense", "rating_defense", (4, 1), "Disarm"),
    ("ability", "ImprovedDefend", "skill_passive", (4, 2), "Defense"),
    ("ability", "Upsurge", "skill_support", (4, 3), "ImprovedDefend"),
    ("ability", "Parry", "skill_defense", (4, 4), "Upsurge"),
    ("ability", "BattleCry", "skill_support", (5, 0), None),
    ("ability", "Adrenaline", "skill_support", (5, 1), "BattleCry"),
    ("health", "Health", "skill_defense", (5, 2), "Adrenaline"),
    ("ability", "DoubleStrike", "skill_offense", (5, 3), "Health"),
    ("ability", "AchillesHeel", "skill_control", (5, 4), "DoubleStrike"),
)

WARRIOR_NODE_LEVEL_REQUIREMENTS = {
    "Charge": 5,
    "ShieldBlock": 5,
    "WeaponFocus": 10,
    "Rally": 10,
    "Goad": 10,
    "Adrenaline": 5,
    "DrivingThrust": 15,
    "Dishearten": 20,
    "HonedAttack": 10,
    "Chastise": 15,
    "Cripple": 20,
    "DoubleStrike": 15,
    "TrueStrike": 25,
    "Retaliate": 25,
    "AggressivePursuit": 25,
    "Commitment": 25,
    "ImprovedDefend": 10,
    "Upsurge": 15,
    "Parry": 20,
    "AchillesHeel": 20,
}

# Cross-path requirements can join an ordinary node or promotion. Required
# nodes use (promotion target, manifest identifier) so rating nodes can be
# referenced without depending on generated IDs.
WARRIOR_NODE_CROSS_REQUIREMENTS = {
    "Retaliate": (("Sentinel", "ShieldBlock"),),
}

# Cross-path connector channels are expressed as tree-column coordinates.
# Retaliate's Bulwark requirement routes between the Lancer and Sentinel
# columns instead of following Shield Block's half-column position.
WARRIOR_CONNECTOR_CHANNEL_OVERRIDES = {
    ("Retaliate", "ShieldBlock"): 1.5,
}

# Reserved for authored nodes that diverge from their manifest sequence.
WARRIOR_NODE_PREREQUISITE_OVERRIDES = {
    "HonedAttack": (("Weapon Master", "Charge"),),
    "Goad": (("Sentinel", "ShieldBlock"),),
}

# Cross-path gates occur at their exact development-node junctions rather than
# being repeated as direct promotion prerequisites.
WARRIOR_PROMOTION_CROSS_REQUIREMENTS = {}

# Weapon Master is intentionally asymmetric. The weapon-art column is
# independent of both promotion routes, while the Grandmaster route forks into
# permanently exclusive Dual Wield and Duelist styles before rejoining.
WEAPON_MASTER_TREE_NODE_SPECS = (
    {
        "id": "double-strike",
        "kind": "ability",
        "identifier": "DoubleStrike",
        "lane": "Berserker",
        "position": (0, 0),
        "owned_if_known": True,
    },
    {
        "id": "attack-1",
        "kind": "rating",
        "identifier": "Attack",
        "lane": "Berserker",
        "position": (0, 1),
        "prerequisites": ("double-strike",),
    },
    {
        "id": "two-handed-weapon-proficiency",
        "kind": "ability",
        "identifier": "TwoHandedWeaponProficiency",
        "lane": "Berserker",
        "position": (0, 2),
        "level": 35,
        "prerequisites": ("attack-1",),
        "exclusive_group": "weapon-master.style",
    },
    {
        "id": "mortal-strike",
        "kind": "ability",
        "identifier": "MortalStrike",
        "lane": "Berserker",
        "position": (0, 4),
        "level": 45,
        "prerequisites": ("two-handed-weapon-proficiency",),
    },
    {
        "id": "devastating-throw",
        "kind": "ability",
        "identifier": "DevastatingThrow",
        "lane": "Berserker",
        "position": (0, 5),
        "level": 50,
        "prerequisites": ("mortal-strike",),
    },
    {
        "id": "brutish-strength",
        "kind": "ability",
        "identifier": "BrutishStrength",
        "lane": "Berserker",
        "position": (0, 6),
        "level": 55,
        "prerequisites": ("devastating-throw",),
    },
    {
        "id": "parry",
        "kind": "ability",
        "identifier": "Parry",
        "lane": "Grandmaster",
        "position": (1.5, 0),
        "owned_if_known": True,
    },
    {
        "id": "defense-1",
        "kind": "rating",
        "identifier": "Defense",
        "lane": "Grandmaster",
        "position": (1.5, 1),
        "prerequisites": ("parry",),
    },
    {
        "id": "dual-wield",
        "kind": "ability",
        "identifier": "DualWield",
        "lane": "Dual Wield",
        "position": (1, 2),
        "level": 35,
        "prerequisites": ("defense-1",),
        "exclusive_group": "weapon-master.style",
    },
    {
        "id": "honed-attack",
        "kind": "ability",
        "identifier": "HonedAttack",
        "lane": "Dual Wield",
        "position": (1, 3),
        "level": 40,
        "prerequisites": ("dual-wield",),
        "stack_if_known": True,
    },
    {
        "id": "momentum",
        "kind": "ability",
        "identifier": "Momentum",
        "lane": "Dual Wield",
        "position": (1, 4),
        "level": 45,
        "prerequisites": ("honed-attack",),
    },
    {
        "id": "cross-block",
        "kind": "ability",
        "identifier": "CrossBlock",
        "lane": "Dual Wield",
        "position": (1, 5),
        "level": 50,
        "prerequisites": ("momentum",),
    },
    {
        "id": "duelist",
        "kind": "ability",
        "identifier": "Duelist",
        "lane": "Duelist",
        "position": (2, 2),
        "level": 35,
        "prerequisites": ("defense-1",),
        "exclusive_group": "weapon-master.style",
    },
    {
        "id": "blind-fighting",
        "kind": "ability",
        "identifier": "BlindFighting",
        "lane": "Duelist",
        "position": (2, 3),
        "level": 40,
        "prerequisites": ("duelist",),
    },
    {
        "id": "retort",
        "kind": "ability",
        "identifier": "Retort",
        "lane": "Duelist",
        "position": (2, 4),
        "level": 45,
        "prerequisites": ("blind-fighting",),
    },
    {
        "id": "maim",
        "kind": "ability",
        "identifier": "Maim",
        "lane": "Duelist",
        "position": (2, 5),
        "level": 50,
        "prerequisites": ("retort",),
    },
    {
        "id": "true-piercing-strike",
        "kind": "ability",
        "identifier": "TruePiercingStrike",
        "lane": "Grandmaster",
        "position": (1.5, 6),
        "level": 55,
        "prerequisites": ("cross-block", "maim"),
        "prerequisite_mode": "any",
    },
    *(
        {
            "id": node_id,
            "kind": "ability",
            "identifier": identifier,
            "lane": "Weapon Arts",
            "position": (3, row),
            "weapon_specialization": (weapon_type, 1),
        }
        for row, (node_id, identifier, weapon_type) in enumerate(
            (
                ("iron-palm", "IronPalm", "Fist"),
                ("hemorrhage", "Hemorrhage", "Dagger"),
                ("riposte-line", "RiposteLine", "Sword"),
                ("low-sweep", "LowSweep", "Club"),
                ("guard-cleaver", "GuardCleaver", "Longsword"),
                ("reavers-mark", "ReaversMark", "Battle Axe"),
                ("brace", "Brace", "Polearm"),
                ("anvil-strike", "AnvilStrike", "Hammer"),
            )
        )
    ),
    *(
        {
            "id": f"{node_id}-2",
            "kind": "ability",
            "identifier": f"{identifier}2",
            "lane": "Weapon Arts",
            "position": (4, row),
            "prerequisites": (node_id,),
            "weapon_specialization": (weapon_type, 5),
        }
        for row, (node_id, identifier, weapon_type) in enumerate(
            (
                ("iron-palm", "IronPalm", "Fist"),
                ("hemorrhage", "Hemorrhage", "Dagger"),
                ("riposte-line", "RiposteLine", "Sword"),
                ("low-sweep", "LowSweep", "Club"),
                ("guard-cleaver", "GuardCleaver", "Longsword"),
                ("reavers-mark", "ReaversMark", "Battle Axe"),
                ("brace", "Brace", "Polearm"),
                ("anvil-strike", "AnvilStrike", "Hammer"),
            )
        )
    ),
)

WEAPON_DISCIPLINE_ARTS = (
    ("iron-palm", "IronPalm", "Fist"),
    ("hemorrhage", "Hemorrhage", "Dagger"),
    ("riposte-line", "RiposteLine", "Sword"),
    ("low-sweep", "LowSweep", "Club"),
    ("guard-cleaver", "GuardCleaver", "Longsword"),
    ("reavers-mark", "ReaversMark", "Battle Axe"),
    ("brace", "Brace", "Polearm"),
    ("anvil-strike", "AnvilStrike", "Hammer"),
)

BERSERKER_TREE_NODE_SPECS = (
    {
        "id": "monkey-grip",
        "kind": "ability",
        "identifier": "MonkeyGrip",
        "lane": "Heavy Weapons",
        "position": (0, 1),
        "available_on_promotion": True,
    },
    {
        "id": "momentum",
        "kind": "ability",
        "identifier": "Momentum",
        "lane": "Heavy Weapons",
        "position": (0, 2),
        "level": 65,
        "prerequisites": ("monkey-grip",),
    },
    {
        "id": "tectonic-rift",
        "kind": "ability",
        "identifier": "TectonicRift",
        "lane": "Heavy Weapons",
        "position": (0, 4),
        "level": 75,
        "prerequisites": ("momentum",),
    },
    {
        "id": "monkey-grip-2",
        "kind": "ability",
        "identifier": "MonkeyGrip2",
        "lane": "Heavy Weapons",
        "position": (0, 5),
        "level": 80,
        "cost": 2,
        "prerequisites": ("tectonic-rift",),
    },
    {
        "id": "mortal-strike-2",
        "kind": "ability",
        "identifier": "MortalStrike2",
        "name": "Mortal Strike 2",
        "lane": "Two-Weapon Assault",
        "position": (1, 1),
        "available_on_promotion": True,
    },
    {
        "id": "boomerang-toss",
        "kind": "ability",
        "identifier": "BoomerangToss",
        "lane": "Two-Weapon Assault",
        "position": (1, 2),
        "level": 65,
        "prerequisites": ("mortal-strike-2",),
    },
    {
        "id": "attack-1",
        "kind": "rating",
        "identifier": "Attack",
        "lane": "Two-Weapon Assault",
        "position": (1, 3),
        "prerequisites": ("boomerang-toss",),
    },
    {
        "id": "thunderous-vault",
        "kind": "ability",
        "identifier": "ThunderousVault",
        "lane": "Two-Weapon Assault",
        "position": (1, 4),
        "level": 75,
        "prerequisites": ("attack-1",),
    },
    {
        "id": "triple-strike",
        "kind": "ability",
        "identifier": "TripleStrike",
        "lane": "Two-Weapon Assault",
        "position": (1, 5),
        "level": 80,
        "cost": 2,
        "prerequisites": ("thunderous-vault",),
    },
    {
        "id": "frenzy",
        "kind": "ability",
        "identifier": "Frenzy",
        "lane": "Fury",
        "position": (2, 1),
        "available_on_promotion": True,
    },
    {
        "id": "hemorrhage-thirst",
        "kind": "ability",
        "identifier": "HemorrhageThirst",
        "lane": "Fury",
        "position": (2, 3),
        "level": 70,
        "prerequisites": ("frenzy",),
    },
    {
        "id": "fatality",
        "kind": "ability",
        "identifier": "Fatality",
        "lane": "Fury",
        "position": (2, 4),
        "level": 75,
        "prerequisites": ("hemorrhage-thirst",),
    },
    {
        "id": "composed-wrath",
        "kind": "ability",
        "identifier": "ComposedWrath",
        "lane": "Fury",
        "position": (2, 5),
        "level": 80,
        "cost": 2,
        "prerequisites": ("fatality",),
    },
    {
        "id": "parry",
        "kind": "ability",
        "identifier": "Parry",
        "lane": "Survival",
        "position": (3, 1),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "pain-tolerance",
        "kind": "ability",
        "identifier": "PainTolerance",
        "lane": "Survival",
        "position": (3, 2),
        "level": 65,
        "prerequisites": ("parry",),
    },
    {
        "id": "final-assault",
        "kind": "ability",
        "identifier": "FinalAssault",
        "lane": "Survival",
        "position": (3, 3),
        "level": 70,
        "prerequisites": ("pain-tolerance",),
    },
    {
        "id": "reckless-onslaught",
        "kind": "ability",
        "identifier": "RecklessOnslaught",
        "lane": "Survival",
        "position": (3, 4),
        "level": 75,
        "cost": 2,
        "prerequisites": ("final-assault",),
    },
    *(
        {
            "id": node_id,
            "kind": "ability",
            "identifier": identifier,
            "lane": "Weapon Arts",
            "position": (4, row + 2),
            "owned_if_known": True,
            "weapon_specialization": (weapon_type, 1),
        }
        for row, (node_id, identifier, weapon_type) in enumerate(WEAPON_DISCIPLINE_ARTS[4:])
    ),
    *(
        {
            "id": f"{node_id}-2",
            "kind": "ability",
            "identifier": f"{identifier}2",
            "lane": "Weapon Arts",
            "position": (5, row + 2),
            "prerequisites": (node_id,),
            "owned_if_known": True,
            "cost": 2,
            "weapon_specialization": (weapon_type, 5),
        }
        for row, (node_id, identifier, weapon_type) in enumerate(WEAPON_DISCIPLINE_ARTS[4:])
    ),
)

GRANDMASTER_TREE_NODE_SPECS = (
    *(
        {
            "id": node_id,
            "kind": "ability",
            "identifier": identifier,
            "lane": "Weapon Arts",
            "position": (0, row),
            "owned_if_known": True,
            "weapon_specialization": (weapon_type, 1),
        }
        for row, (node_id, identifier, weapon_type) in enumerate(WEAPON_DISCIPLINE_ARTS)
    ),
    *(
        {
            "id": f"{node_id}-2",
            "kind": "ability",
            "identifier": f"{identifier}2",
            "lane": "Weapon Arts",
            "position": (1, row),
            "prerequisites": (node_id,),
            "owned_if_known": True,
            "weapon_specialization": (weapon_type, 5),
        }
        for row, (node_id, identifier, weapon_type) in enumerate(WEAPON_DISCIPLINE_ARTS)
    ),
    *(
        {
            "id": f"{node_id}-3",
            "kind": "ability",
            "identifier": f"{identifier}3",
            "lane": "Weapon Arts",
            "position": (2, row),
            "prerequisites": (f"{node_id}-2",),
            "owned_if_known": True,
            "cost": 2,
            "weapon_specialization": (weapon_type, 10),
        }
        for row, (node_id, identifier, weapon_type) in enumerate(WEAPON_DISCIPLINE_ARTS)
    ),
    {
        "id": "double-strike",
        "kind": "ability",
        "identifier": "DoubleStrike",
        "lane": "Mastery",
        "position": (4, 1),
        "owned_if_known": True,
    },
    {
        "id": "dual-wield-excellence",
        "kind": "ability",
        "identifier": "DualWieldExcellence",
        "lane": "Mastery",
        "position": (4, 2),
        "level": 65,
        "prerequisites": ("double-strike",),
    },
    {
        "id": "weapon-swap",
        "kind": "ability",
        "identifier": "WeaponSwap",
        "lane": "Mastery",
        "position": (4, 3),
        "level": 70,
        "prerequisites": ("dual-wield-excellence",),
    },
    {
        "id": "perfect-form",
        "kind": "talent",
        "identifier": "grandmaster.perfect-form",
        "name": "Perfect Form",
        "lane": "Mastery",
        "position": (3, 4),
        "level": 75,
        "cost": 2,
        "description": (
            "Increase weapon damage by 1% and hit chance by 0.5% per rank "
            "of the equipped weapon's discipline."
        ),
        "prerequisites": ("weapon-swap",),
    },
    {
        "id": "adaptive-arsenal",
        "kind": "talent",
        "identifier": "grandmaster.adaptive-arsenal",
        "name": "Adaptive Arsenal",
        "lane": "Mastery",
        "position": (5, 4),
        "level": 75,
        "cost": 2,
        "description": (
            "Increase parry chance by 0.5% and Riposte critical chance "
            "by 1% per rank of the equipped weapon's discipline."
        ),
        "prerequisites": ("weapon-swap",),
    },
    {
        "id": "dual-wield-mastery",
        "kind": "ability",
        "identifier": "DualWieldMastery",
        "lane": "Mastery",
        "position": (4, 5),
        "level": 80,
        "prerequisites": ("perfect-form", "adaptive-arsenal"),
    },
)

# Lancer and Dragoon use explicit graphs because Jump modifications are
# progression purchases rather than spellbook abilities. Modifier nodes keep
# stable ``*.jump-mod.*`` IDs and unlock configuration on the learned Jump.
LANCER_TREE_NODE_SPECS = (
    {
        "id": "jump",
        "kind": "ability",
        "identifier": "Jump",
        "lane": "Jump Core",
        "position": (1, 0),
        "available_on_promotion": True,
    },
    {
        "id": "aerial-footwork",
        "kind": "talent",
        "identifier": "lancer.aerial-footwork",
        "name": "Aerial Footwork",
        "lane": "Assault Mods",
        "position": (2, 1),
        "level": 35,
        "prerequisites": ("jump",),
        "description": ("Increase Attack by 20% and Aerial Tempo capacity by 1."),
        "bonuses": {"rating_percentages": {"Attack": 0.20}},
        "kit_effect": ("meter_cap", "aerial_tempo", 1),
    },
    {
        "id": "grounded-landing",
        "kind": "talent",
        "identifier": "lancer.grounded-landing",
        "name": "Grounded Landing",
        "lane": "Guard Mods",
        "position": (0, 3),
        "level": 45,
        "prerequisites": ("acrobat",),
        "description": (
            "Increase Defense by 20% and reduce final incoming "
            "damage by 10% while Jump is charging."
        ),
        "bonuses": {"rating_percentages": {"Defense": 0.20}},
    },
    {
        "id": "polearm-proficiency",
        "kind": "ability",
        "identifier": "PolearmProficiency",
        "lane": "Polearm Discipline",
        "position": (4, 0),
        "available_on_promotion": True,
    },
    {
        "id": "lance-sweep",
        "kind": "ability",
        "identifier": "LanceSweep",
        "lane": "Polearm Discipline",
        "position": (3, 1),
        "level": 35,
        "prerequisites": ("polearm-proficiency",),
    },
    {
        "id": "extended-reach",
        "kind": "ability",
        "identifier": "ExtendedReach",
        "lane": "Polearm Assault",
        "position": (3, 2),
        "level": 40,
        "prerequisites": ("lance-sweep",),
    },
    {
        "id": "zephyrstrike",
        "kind": "ability",
        "identifier": "Zephyrstrike",
        "lane": "Polearm Assault",
        "position": (3, 3),
        "level": 45,
        "prerequisites": ("extended-reach",),
    },
    {
        "id": "swing-and-bash",
        "kind": "ability",
        "identifier": "SwingAndBash",
        "lane": "Polearm Assault",
        "position": (3, 4),
        "level": 50,
        "prerequisites": ("zephyrstrike",),
    },
    {
        "id": "polearm-excellence",
        "kind": "ability",
        "identifier": "PolearmExcellence",
        "lane": "Polearm Assault",
        "position": (4, 5),
        "level": 55,
        "cost": 2,
        "prerequisites": ("polearm-proficiency",),
    },
    {
        "id": "phalanx",
        "kind": "ability",
        "identifier": "Phalanx",
        "lane": "Polearm Guard",
        "position": (5, 1),
        "level": 35,
        "prerequisites": ("polearm-proficiency",),
    },
    {
        "id": "critical-vigor",
        "kind": "ability",
        "identifier": "CriticalVigor",
        "lane": "Polearm Guard",
        "position": (5, 2),
        "level": 40,
        "prerequisites": ("phalanx",),
    },
    {
        "id": "health-1",
        "kind": "health",
        "identifier": "Health",
        "lane": "Polearm Guard",
        "position": (5, 3),
        "level": 45,
        "level_band_gate": True,
        "prerequisites": ("critical-vigor",),
    },
    {
        "id": "dragon-soul",
        "kind": "ability",
        "identifier": "DragonSoul",
        "lane": "Polearm Guard",
        "position": (5, 4),
        "level": 50,
        "prerequisites": ("health-1",),
    },
    {
        "id": "defense-1",
        "kind": "rating",
        "identifier": "Defense",
        "lane": "Guard Mods",
        "position": (1, 2),
        "prerequisites": ("jump",),
    },
    {
        "id": "defend",
        "kind": "jump_mod",
        "identifier": "lancer.jump-mod.defend",
        "name": "Defend",
        "jump_modification": "Defend",
        "lane": "Guard Mods",
        "position": (0, 1),
        "level": 35,
        "prerequisites": ("jump",),
    },
    {
        "id": "acrobat",
        "kind": "jump_mod",
        "identifier": "lancer.jump-mod.acrobat",
        "name": "Acrobat",
        "jump_modification": "Acrobat",
        "lane": "Guard Mods",
        "position": (0, 2),
        "level": 40,
        "prerequisites": ("defend",),
    },
    {
        "id": "quick-dive",
        "kind": "jump_mod",
        "identifier": "lancer.jump-mod.quick-dive",
        "name": "Quick Dive",
        "jump_modification": "Quick Dive",
        "lane": "Assault Mods",
        "position": (2, 2),
        "level": 40,
        "prerequisites": ("aerial-footwork",),
    },
    {
        "id": "attack-1",
        "kind": "rating",
        "identifier": "Attack",
        "lane": "Assault Mods",
        "position": (1, 1),
        "prerequisites": ("jump",),
    },
    {
        "id": "vigilant-landing",
        "kind": "ability",
        "identifier": "VigilantLanding",
        "lane": "Guard Mods",
        "position": (1, 3),
        "level": 45,
        "cost": 2,
        "prerequisites": ("defense-1",),
    },
    {
        "id": "thrust",
        "kind": "jump_mod",
        "identifier": "lancer.jump-mod.thrust",
        "name": "Thrust",
        "jump_modification": "Thrust",
        "lane": "Assault Mods",
        "position": (2, 3),
        "level": 45,
        "prerequisites": ("quick-dive",),
    },
    {
        "id": "rend",
        "kind": "jump_mod",
        "identifier": "lancer.jump-mod.rend",
        "name": "Rend",
        "jump_modification": "Rend",
        "lane": "Assault Mods",
        "position": (2, 4),
        "level": 50,
        "prerequisites": ("thrust",),
    },
    {
        "id": "true-strike",
        "kind": "ability",
        "identifier": "TrueStrike",
        "lane": "Unbound",
        "position": (6, 3),
        "owned_if_known": True,
    },
)

DRAGOON_TREE_NODE_SPECS = (
    {
        "id": "attack-1",
        "kind": "rating",
        "identifier": "Attack",
        "lane": "Polearm Assault",
        "position": (4, 6),
        "prerequisites": ("lancer.ability.polearm-excellence",),
    },
    {
        "id": "polearm-mastery",
        "kind": "ability",
        "identifier": "PolearmMastery",
        "lane": "Polearm Assault",
        "position": (4, 7),
        "level": 80,
        "cost": 2,
        "prerequisites": ("attack-1",),
    },
    {
        "id": "dragonheart",
        "kind": "ability",
        "identifier": "Dragonheart",
        "lane": "Polearm Guard",
        "position": (5, 7),
        "level": 75,
        "cost": 2,
        "prerequisites": ("lancer.ability.dragon-soul",),
    },
    {
        "id": "true-piercing-strike",
        "kind": "ability",
        "identifier": "TruePiercingStrike",
        "lane": "Unbound",
        "position": (6, 7),
        "level": 75,
        "prerequisites": ("lancer.ability.true-strike",),
    },
    {
        "id": "quake",
        "kind": "jump_mod",
        "identifier": "dragoon.jump-mod.quake",
        "name": "Quake",
        "jump_modification": "Quake",
        "lane": "Assault Mods",
        "position": (2, 6),
        "level": 65,
        "prerequisites": ("lancer.jump-mod.rend",),
    },
    {
        "id": "soaring-strike",
        "kind": "jump_mod",
        "identifier": "dragoon.jump-mod.soaring-strike",
        "name": "Soaring Strike",
        "jump_modification": "Soaring Strike",
        "lane": "Assault Mods",
        "position": (2, 7),
        "level": 70,
        "prerequisites": ("quake",),
    },
    {
        "id": "dragons-ascent",
        "kind": "talent",
        "identifier": "dragoon.dragons-ascent",
        "name": "Dragon's Ascent",
        "lane": "Assault Mods",
        "position": (1, 5),
        "prerequisites": ("lancer.rating.attack-1",),
        "available_on_promotion": True,
        "description": (
            "Increase Attack by 30%. A clean Soaring Strike landing grants 2 Aerial Tempo."
        ),
        "bonuses": {"rating_percentages": {"Attack": 0.30}},
    },
    {
        "id": "dragon-dive",
        "kind": "ability",
        "identifier": "DragonDive",
        "lane": "Guard Mods",
        "position": (1, 7),
        "level": 80,
        "cost": 2,
        "prerequisites": (
            "dragons-ascent",
            "soaring-strike",
            "unstoppable",
        ),
    },
    {
        "id": "defense-1",
        "kind": "rating",
        "identifier": "Defense",
        "lane": "Guard Mods",
        "position": (1, 6),
        "prerequisites": ("dragons-ascent",),
    },
    {
        "id": "retribution",
        "kind": "jump_mod",
        "identifier": "dragoon.jump-mod.retribution",
        "name": "Retribution",
        "jump_modification": "Retribution",
        "lane": "Guard Mods",
        "position": (0, 6),
        "level": 65,
        "prerequisites": ("lancer.talent.grounded-landing",),
    },
    {
        "id": "unstoppable",
        "kind": "jump_mod",
        "identifier": "dragoon.jump-mod.unstoppable",
        "name": "Unstoppable",
        "jump_modification": "Unstoppable",
        "lane": "Guard Mods",
        "position": (0, 7),
        "level": 70,
        "prerequisites": ("retribution",),
    },
)

# Sentinel, Stalwart Defender, Paladin, and Crusader use compact authored
# graphs. First-promotion trees close after promotion; terminal trees contain
# only their new development nodes.
SENTINEL_TREE_NODE_SPECS = (
    {
        "id": "retaliate",
        "kind": "ability",
        "identifier": "Retaliate",
        "lane": "Assault",
        "position": (0, 2),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "swing-and-bash",
        "kind": "ability",
        "identifier": "SwingAndBash",
        "lane": "Assault",
        "position": (0, 3),
        "level": 35,
        "prerequisites": ("retaliate",),
    },
    {
        "id": "attack-1",
        "kind": "rating",
        "identifier": "Attack",
        "lane": "Assault",
        "position": (0, 4),
        "level": 40,
        "level_band_gate": True,
        "prerequisites": ("swing-and-bash",),
    },
    {
        "id": "focused-assault",
        "kind": "ability",
        "identifier": "FocusedAssault",
        "lane": "Assault",
        "position": (0, 5),
        "level": 45,
        "prerequisites": ("attack-1",),
    },
    {
        "id": "repercussion",
        "kind": "ability",
        "identifier": "Repercussion",
        "lane": "Assault",
        "position": (0, 6),
        "level": 50,
        "prerequisites": ("focused-assault",),
    },
    {
        "id": "watchful-reprisal",
        "kind": "talent",
        "identifier": "sentinel.watchful-reprisal",
        "name": "Watchful Reprisal",
        "lane": "Assault",
        "position": (0, 7),
        "level": 55,
        "prerequisites": ("repercussion",),
        "description": ("Increase Attack by 20% and Retaliate chance by 10 percentage points."),
        "bonuses": {"rating_percentages": {"Attack": 0.20}},
    },
    {
        "id": "hold-the-line",
        "kind": "ability",
        "identifier": "HoldTheLine",
        "lane": "Wall",
        "position": (1, 2),
        "available_on_promotion": True,
    },
    {
        "id": "shield-riposte",
        "kind": "ability",
        "identifier": "ShieldRiposte",
        "lane": "Wall",
        "position": (1, 3),
        "level": 35,
        "prerequisites": ("hold-the-line",),
    },
    {
        "id": "defense-1",
        "kind": "rating",
        "identifier": "Defense",
        "lane": "Wall",
        "position": (1, 4),
        "level": 40,
        "level_band_gate": True,
        "prerequisites": ("shield-riposte",),
    },
    {
        "id": "brace-wall",
        "kind": "ability",
        "identifier": "BraceWall",
        "lane": "Wall",
        "position": (1, 5),
        "level": 45,
        "prerequisites": ("defense-1",),
    },
    {
        "id": "resolute-guard",
        "kind": "talent",
        "identifier": "sentinel.resolute-guard",
        "name": "Resolute Guard",
        "lane": "Wall",
        "position": (1, 7),
        "level": 55,
        "prerequisites": ("brace-wall",),
        "description": (
            "Increase Defense by 20% and improve Hold the Line's "
            "block and mitigation by 5 percentage points."
        ),
        "bonuses": {"rating_percentages": {"Defense": 0.20}},
    },
    {
        "id": "adrenaline",
        "kind": "ability",
        "identifier": "Adrenaline",
        "lane": "Resolve Roots",
        "position": (2.5, 2),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "spell-block",
        "kind": "ability",
        "identifier": "SpellBlock",
        "lane": "Resistance",
        "position": (2, 3),
        "level": 35,
        "prerequisites": ("adrenaline",),
    },
    {
        "id": "magic-defense-1",
        "kind": "rating",
        "identifier": "Magic Defense",
        "lane": "Resistance",
        "position": (2, 4),
        "level": 40,
        "level_band_gate": True,
        "prerequisites": ("spell-block",),
    },
    {
        "id": "bulwark-guard",
        "kind": "ability",
        "identifier": "BulwarkGuard",
        "lane": "Resistance",
        "position": (2, 5),
        "level": 45,
        "prerequisites": ("magic-defense-1",),
    },
    {
        "id": "spell-reflection",
        "kind": "ability",
        "identifier": "SpellReflection",
        "lane": "Resistance",
        "position": (2, 6),
        "level": 50,
        "prerequisites": ("bulwark-guard",),
    },
    {
        "id": "shielding-ward",
        "kind": "talent",
        "identifier": "sentinel.shielding-ward",
        "name": "Shielding Ward",
        "lane": "Resistance",
        "position": (2, 7),
        "level": 55,
        "prerequisites": ("spell-reflection",),
        "description": (
            "Increase Magic Defense by 20% and halve damage remaining after Spell Block."
        ),
        "bonuses": {"rating_percentages": {"Magic Defense": 0.20}},
    },
    {
        "id": "purge-weakness",
        "kind": "ability",
        "identifier": "PurgeWeakness",
        "lane": "Support",
        "position": (3, 3),
        "level": 35,
        "prerequisites": ("adrenaline",),
    },
    {
        "id": "health-1",
        "kind": "health",
        "identifier": "Health",
        "lane": "Support",
        "position": (3, 4),
        "level": 40,
        "level_band_gate": True,
        "prerequisites": ("purge-weakness",),
    },
    {
        "id": "boast",
        "kind": "ability",
        "identifier": "Boast",
        "lane": "Support",
        "position": (3, 5),
        "level": 45,
        "prerequisites": ("health-1",),
    },
    {
        "id": "braggadocious",
        "kind": "talent",
        "identifier": "sentinel.braggadocious",
        "name": "Braggadocious",
        "lane": "Support",
        "position": (3, 7),
        "level": 55,
        "prerequisites": ("boast",),
        "description": (
            "Increase maximum HP by 10% and convert unused Boast health "
            "into Resolve when it expires in combat."
        ),
        "bonuses": {"health_percentage": 0.10},
    },
    {
        "id": "goad",
        "kind": "ability",
        "identifier": "Goad",
        "lane": "Unbound",
        "position": (4, 3),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "charge",
        "kind": "ability",
        "identifier": "Charge",
        "lane": "Unbound",
        "position": (4, 4),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "double-strike",
        "kind": "ability",
        "identifier": "DoubleStrike",
        "lane": "Unbound",
        "position": (4, 5),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
)

STALWART_DEFENDER_TREE_NODE_SPECS = (
    {
        "id": "repercussion",
        "kind": "ability",
        "identifier": "Repercussion",
        "lane": "Assault",
        "position": (0, 1),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "focused-assault",
        "kind": "ability",
        "identifier": "FocusedAssault",
        "lane": "Assault",
        "position": (0, 2),
        "available_on_promotion": True,
        "owned_if_known": True,
        "prerequisites": ("repercussion",),
    },
    {
        "id": "punishing-guard",
        "kind": "talent",
        "identifier": "stalwart.punishing-guard",
        "name": "Punishing Guard",
        "lane": "Assault",
        "position": (0, 3),
        "level": 70,
        "cost": 2,
        "prerequisites": ("focused-assault",),
        "description": (
            "Increase Attack by 30%. Repercussion deals 25% more "
            "damage and can knock enemies prone."
        ),
        "bonuses": {"rating_percentages": {"Attack": 0.30}},
    },
    {
        "id": "crushing-vengeance",
        "kind": "ability",
        "identifier": "CrushingVengeance",
        "lane": "Assault",
        "position": (0, 4),
        "level": 75,
        "prerequisites": ("punishing-guard",),
    },
    {
        "id": "double-payback",
        "kind": "ability",
        "identifier": "DoublePayback",
        "lane": "Assault",
        "position": (0, 5),
        "level": 80,
        "cost": 2,
        "prerequisites": ("crushing-vengeance",),
    },
    {
        "id": "hold-the-line",
        "kind": "ability",
        "identifier": "HoldTheLine",
        "lane": "Bulwark",
        "position": (1, 1),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "brace-wall",
        "kind": "ability",
        "identifier": "BraceWall",
        "lane": "Bulwark",
        "position": (1, 2),
        "available_on_promotion": True,
        "owned_if_known": True,
        "prerequisites": ("hold-the-line",),
    },
    {
        "id": "last-stand",
        "kind": "ability",
        "identifier": "LastStand",
        "lane": "Bulwark",
        "position": (1, 3),
        "level": 70,
        "prerequisites": ("brace-wall",),
    },
    {
        "id": "unbroken-wall",
        "kind": "talent",
        "identifier": "stalwart.unbroken-wall",
        "name": "Unbroken Wall",
        "lane": "Bulwark",
        "position": (1, 5),
        "level": 80,
        "cost": 2,
        "prerequisites": ("last-stand",),
        "description": (
            "Increase Defense by 30%. Last Stand gains 10 "
            "percentage points of block chance and 50% more Resolve gain."
        ),
        "bonuses": {"rating_percentages": {"Defense": 0.30}},
    },
    {
        "id": "iron-maiden",
        "kind": "ability",
        "identifier": "IronMaiden",
        "lane": "Bulwark",
        "position": (1, 6),
        "level": 85,
        "cost": 2,
        "prerequisites": ("unbroken-wall",),
    },
    {
        "id": "retaliate",
        "kind": "ability",
        "identifier": "Retaliate",
        "lane": "Shield Offense",
        "position": (2, 1),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "shield-ricochet",
        "kind": "ability",
        "identifier": "ShieldRicochet",
        "lane": "Shield Offense",
        "position": (2, 2),
        "level": 65,
        "prerequisites": ("retaliate",),
    },
    {
        "id": "tower-offense",
        "kind": "ability",
        "identifier": "TowerOffense",
        "lane": "Shield Offense",
        "position": (2, 3),
        "level": 70,
        "prerequisites": ("shield-ricochet",),
    },
    {
        "id": "get-even",
        "kind": "ability",
        "identifier": "GetEven",
        "lane": "Shield Offense",
        "position": (2, 4),
        "level": 75,
        "prerequisites": ("tower-offense",),
    },
    {
        "id": "generator-shield",
        "kind": "ability",
        "identifier": "GeneratorShield",
        "lane": "Shield Offense",
        "position": (2, 5),
        "level": 80,
        "prerequisites": ("get-even",),
    },
    {
        "id": "spell-block",
        "kind": "ability",
        "identifier": "SpellBlock",
        "lane": "Resistance",
        "position": (3, 1),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "bulwark-guard",
        "kind": "ability",
        "identifier": "BulwarkGuard",
        "lane": "Resistance",
        "position": (3, 2),
        "available_on_promotion": True,
        "owned_if_known": True,
        "prerequisites": ("spell-block",),
    },
    {
        "id": "spell-reflection",
        "kind": "ability",
        "identifier": "SpellReflection",
        "lane": "Resistance",
        "position": (3, 3),
        "available_on_promotion": True,
        "owned_if_known": True,
        "prerequisites": ("bulwark-guard",),
    },
    {
        "id": "mirror-bastion",
        "kind": "talent",
        "identifier": "stalwart.mirror-bastion",
        "name": "Mirror Bastion",
        "lane": "Resistance",
        "position": (3, 4),
        "level": 75,
        "prerequisites": ("spell-reflection",),
        "description": "Spell Reflection grants +50 Magic Defense when it triggers.",
    },
    {
        "id": "fortified-citadel",
        "kind": "talent",
        "identifier": "stalwart.fortified-citadel",
        "name": "Fortified Citadel",
        "lane": "Resistance",
        "position": (3, 5),
        "level": 80,
        "cost": 2,
        "prerequisites": ("mirror-bastion",),
        "description": (
            "When Citadel Aegis ends, divide its absorbed magic damage evenly among all enemies."
        ),
    },
    {
        "id": "purge-weakness",
        "kind": "ability",
        "identifier": "PurgeWeakness",
        "lane": "Support",
        "position": (4, 1),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "boast",
        "kind": "ability",
        "identifier": "Boast",
        "lane": "Support",
        "position": (4, 2),
        "available_on_promotion": True,
        "owned_if_known": True,
        "prerequisites": ("purge-weakness",),
    },
    {
        "id": "battle-cry",
        "kind": "ability",
        "identifier": "BattleCry",
        "lane": "Support",
        "position": (4, 3),
        "level": 70,
        "prerequisites": ("boast",),
    },
    {
        "id": "battle-determination",
        "kind": "ability",
        "identifier": "BattleDetermination",
        "lane": "Support",
        "position": (4, 4),
        "level": 75,
        "prerequisites": ("battle-cry",),
    },
    {
        "id": "final-redoubt",
        "kind": "talent",
        "identifier": "stalwart.final-redoubt",
        "name": "Final Redoubt",
        "lane": "Support",
        "position": (4, 5),
        "level": 80,
        "cost": 2,
        "prerequisites": ("battle-determination",),
        "description": (
            "Last Bastion restores 40% maximum HP, grants a 75-point barrier, "
            "and enters a three-turn defensive stance."
        ),
    },
)

PALADIN_TREE_NODE_SPECS = (
    {
        "id": "oath-judgment",
        "kind": "ability",
        "identifier": "OathsJudgment",
        "name": "Oath's Judgment",
        "lane": "Zeal",
        "position": (1, 0),
        "available_on_promotion": True,
    },
    {
        "id": "double-strike",
        "kind": "ability",
        "identifier": "DoubleStrike",
        "lane": "Zeal",
        "position": (0, 1),
        "owned_if_known": True,
        "prerequisites": ("oath-judgment",),
    },
    {
        "id": "attack-1",
        "kind": "rating",
        "identifier": "Attack",
        "lane": "Zeal",
        "position": (0, 2),
        "prerequisites": ("double-strike",),
    },
    {
        "id": "tempered-conviction",
        "kind": "talent",
        "identifier": "paladin.tempered-conviction",
        "name": "Tempered Conviction",
        "lane": "Zeal",
        "position": (0, 4),
        "level": 45,
        "prerequisites": ("attack-1",),
        "description": ("Increase Defense by 20% and Oath Conviction capacity by 1."),
        "bonuses": {"rating_percentages": {"Defense": 0.20}},
        "kit_effect": ("meter_cap", "oath_conviction", 1),
    },
    {
        "id": "true-strike",
        "kind": "ability",
        "identifier": "TrueStrike",
        "lane": "Zeal",
        "position": (0, 5),
        "owned_if_known": True,
        "prerequisites": ("tempered-conviction",),
    },
    {
        "id": "smite",
        "kind": "ability",
        "identifier": "Smite",
        "lane": "Zeal",
        "position": (2, 1),
        "available_on_promotion": True,
        "prerequisites": ("oath-judgment",),
    },
    {
        "id": "detect-undead",
        "kind": "ability",
        "identifier": "DetectUndead",
        "lane": "Zeal",
        "position": (2, 2),
        "level": 35,
        "prerequisites": ("smite",),
    },
    {
        "id": "repel-the-wicked",
        "kind": "ability",
        "identifier": "RepelTheWicked",
        "name": "Repel the Wicked",
        "lane": "Zeal",
        "position": (2, 3),
        "level": 40,
        "prerequisites": ("detect-undead",),
    },
    {
        "id": "magic-1",
        "kind": "rating",
        "identifier": "Magic",
        "lane": "Zeal",
        "position": (2, 4),
        "prerequisites": ("repel-the-wicked",),
    },
    {
        "id": "hallowed-ground",
        "kind": "ability",
        "identifier": "HallowedGround",
        "name": "Hallowed Ground",
        "lane": "Zeal",
        "position": (2, 6),
        "level": 55,
        "prerequisites": ("detect-fiend",),
    },
    {
        "id": "detect-fiend",
        "kind": "ability",
        "identifier": "DetectFiend",
        "lane": "Zeal",
        "position": (2, 5),
        "level": 50,
        "prerequisites": ("magic-1",),
    },
    {
        "id": "oath-shelter",
        "kind": "ability",
        "identifier": "OathsShelter",
        "name": "Oath's Shelter",
        "lane": "Grace",
        "position": (4, 0),
        "available_on_promotion": True,
    },
    {
        "id": "heal",
        "kind": "ability",
        "identifier": "Heal",
        "lane": "Grace",
        "position": (3, 1),
        "available_on_promotion": True,
        "prerequisites": ("oath-shelter",),
    },
    {
        "id": "mana-1",
        "kind": "mana",
        "identifier": "Mana",
        "lane": "Grace",
        "position": (3, 2),
        "prerequisites": ("heal",),
    },
    {
        "id": "sworn-purpose",
        "kind": "talent",
        "identifier": "paladin.sworn-purpose",
        "name": "Sworn Purpose",
        "lane": "Grace",
        "position": (3, 5),
        "level": 50,
        "prerequisites": ("resist-shadow",),
        "description": ("Increase Magic and Magic Defense by 20%."),
        "bonuses": {
            "rating_percentages": {
                "Magic": 0.20,
                "Magic Defense": 0.20,
            },
        },
    },
    {
        "id": "blessed-light",
        "kind": "ability",
        "identifier": "BlessedLight",
        "name": "Blessed Light",
        "lane": "Grace",
        "position": (3, 6),
        "level": 55,
        "prerequisites": ("sworn-purpose",),
    },
    {
        "id": "bless",
        "kind": "ability",
        "identifier": "Bless",
        "lane": "Sanctity",
        "position": (5, 1),
        "available_on_promotion": True,
        "prerequisites": ("oath-shelter",),
    },
    {
        "id": "magic-defense-1",
        "kind": "rating",
        "identifier": "Magic Defense",
        "lane": "Sanctity",
        "position": (5, 2),
        "prerequisites": ("bless",),
    },
    {
        "id": "divine-protection",
        "kind": "ability",
        "identifier": "DivineProtection",
        "lane": "Sanctity",
        "position": (5, 5),
        "level": 50,
        "prerequisites": ("defense-1",),
    },
    {
        "id": "defense-1",
        "kind": "rating",
        "identifier": "Defense",
        "lane": "Sanctity",
        "position": (5, 4),
        "prerequisites": ("parry",),
    },
    {
        "id": "resist-shadow",
        "kind": "ability",
        "identifier": "ResistShadow",
        "name": "Resist Shadow",
        "lane": "Sanctity",
        "position": (3, 4),
        "level": 45,
        "prerequisites": ("mana-1",),
    },
    {
        "id": "parry",
        "kind": "ability",
        "identifier": "Parry",
        "lane": "Sanctity",
        "position": (5, 3),
        "owned_if_known": True,
        "prerequisites": ("magic-defense-1",),
    },
)

CRUSADER_TREE_NODE_SPECS = (
    {
        "id": "condemnation",
        "kind": "ability",
        "identifier": "Condemnation",
        "lane": "Melee",
        "position": (1, 0),
        "available_on_promotion": True,
    },
    {
        "id": "two-handed-proficiency",
        "kind": "ability",
        "identifier": "TwoHandedWeaponProficiency",
        "name": "Two-Handed Weapon Proficiency",
        "lane": "Melee",
        "position": (0, 1),
        "level": 65,
        "prerequisites": ("condemnation",),
        "exclusive_group": "crusader.melee-style",
        "cost": 2,
    },
    {
        "id": "mortal-strike",
        "kind": "ability",
        "identifier": "MortalStrike",
        "lane": "Melee",
        "position": (0, 3),
        "level": 75,
        "prerequisites": ("two-handed-proficiency",),
    },
    {
        "id": "righteous-advance",
        "kind": "talent",
        "identifier": "crusader.righteous-advance",
        "name": "Righteous Advance",
        "lane": "Melee",
        "position": (0, 4),
        "level": 80,
        "prerequisites": ("mortal-strike",),
        "available_on_promotion": True,
        "description": ("Increase Attack by 30% and improve every form of Oath's Judgment."),
        "bonuses": {"rating_percentages": {"Attack": 0.30}},
    },
    {
        "id": "penalization",
        "kind": "ability",
        "identifier": "Penalization",
        "lane": "Melee",
        "position": (0, 5),
        "level": 85,
        "cost": 2,
        "prerequisites": ("righteous-advance",),
    },
    {
        "id": "sword-and-board",
        "kind": "ability",
        "identifier": "SwordAndBoard",
        "name": "Sword & Board",
        "lane": "Melee",
        "position": (2, 1),
        "level": 65,
        "prerequisites": ("condemnation",),
        "exclusive_group": "crusader.melee-style",
        "cost": 2,
    },
    {
        "id": "censure",
        "kind": "ability",
        "identifier": "Censure",
        "lane": "Melee",
        "position": (2, 2),
        "level": 70,
        "prerequisites": ("sword-and-board",),
    },
    {
        "id": "true-piercing-strike",
        "kind": "ability",
        "identifier": "TruePiercingStrike",
        "lane": "Melee",
        "position": (2, 3),
        "level": 75,
        "prerequisites": ("censure",),
    },
    {
        "id": "shield-ricochet",
        "kind": "ability",
        "identifier": "ShieldRicochet",
        "lane": "Melee",
        "position": (2, 4),
        "level": 80,
        "prerequisites": ("true-piercing-strike",),
    },
    {
        "id": "triple-strike",
        "kind": "ability",
        "identifier": "TripleStrike",
        "lane": "Melee",
        "position": (2, 5),
        "level": 85,
        "prerequisites": ("shield-ricochet",),
    },
    {
        "id": "beyond-reproach",
        "kind": "ability",
        "identifier": "BeyondReproach",
        "lane": "Melee",
        "position": (1, 3),
        "level": 75,
        "prerequisites": ("condemnation",),
    },
    {
        "id": "repel-the-wicked",
        "kind": "ability",
        "identifier": "RepelTheWicked",
        "name": "Repel the Wicked",
        "lane": "Spells",
        "position": (3, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "smite-2",
        "kind": "ability",
        "identifier": "Smite2",
        "name": "Smite II",
        "lane": "Spells",
        "position": (3, 1),
        "level": 65,
        "prerequisites": ("repel-the-wicked",),
    },
    {
        "id": "sanctification",
        "kind": "ability",
        "identifier": "Sanctification",
        "lane": "Spells",
        "position": (3, 2),
        "level": 70,
        "prerequisites": ("smite-2",),
    },
    {
        "id": "undead-hunter",
        "kind": "ability",
        "identifier": "UndeadHunter",
        "lane": "Spells",
        "position": (3, 3),
        "level": 75,
        "prerequisites": ("sanctification",),
    },
    {
        "id": "smite-3",
        "kind": "ability",
        "identifier": "Smite3",
        "name": "Smite III",
        "lane": "Spells",
        "position": (3, 6),
        "level": 90,
        "cost": 2,
        "prerequisites": ("undead-hunter",),
    },
    {
        "id": "dispel",
        "kind": "ability",
        "identifier": "Dispel",
        "lane": "Healing",
        "position": (4, 0),
        "available_on_promotion": True,
    },
    {
        "id": "cleanse",
        "kind": "ability",
        "identifier": "Cleanse",
        "lane": "Healing",
        "position": (4, 1),
        "level": 65,
        "prerequisites": ("dispel",),
    },
    {
        "id": "heal-2",
        "kind": "ability",
        "identifier": "Heal2",
        "name": "Heal II",
        "lane": "Healing",
        "position": (4, 2),
        "level": 70,
        "prerequisites": ("cleanse",),
    },
    {
        "id": "radiant-healing",
        "kind": "ability",
        "identifier": "RadiantHealing",
        "lane": "Healing",
        "position": (4, 3),
        "level": 75,
        "prerequisites": ("heal-2",),
    },
    {
        "id": "prayer-of-faith",
        "kind": "ability",
        "identifier": "PrayerOfFaith",
        "lane": "Healing",
        "position": (4, 5),
        "level": 85,
        "cost": 2,
        "prerequisites": ("radiant-healing",),
    },
    {
        "id": "divine-protection",
        "kind": "ability",
        "identifier": "DivineProtection",
        "name": "Divine Protection",
        "lane": "Protection",
        "position": (5, 0),
        "available_on_promotion": True,
        "owned_if_known": True,
    },
    {
        "id": "parry",
        "kind": "ability",
        "identifier": "Parry",
        "lane": "Melee",
        "position": (0, 2),
        "prerequisites": ("two-handed-proficiency",),
        "owned_if_known": True,
    },
    {
        "id": "posturing",
        "kind": "ability",
        "identifier": "Posturing",
        "lane": "Protection",
        "position": (5, 2),
        "level": 70,
        "prerequisites": ("divine-protection",),
    },
    {
        "id": "consecrated-bulwark",
        "kind": "talent",
        "identifier": "crusader.consecrated-bulwark",
        "name": "Consecrated Bulwark",
        "lane": "Protection",
        "position": (5, 3),
        "level": 75,
        "prerequisites": ("posturing",),
        "description": ("Increase Magic Defense by 30% and improve every form of Oath's Shelter."),
        "bonuses": {"rating_percentages": {"Magic Defense": 0.30}},
    },
    {
        "id": "divine-protection-2",
        "kind": "ability",
        "identifier": "DivineProtection2",
        "name": "Divine Protection II",
        "lane": "Protection",
        "position": (5, 4),
        "level": 80,
        "cost": 2,
        "prerequisites": ("consecrated-bulwark",),
    },
)
