"""Public class ability-mechanics API.

Equipment, passive, companion, exploration, rewind, and summon mechanics live
in focused modules. Existing imports remain supported.
"""

from .equipment import (
    ELEMENTS,
    TAMED_COMPANION_START_BOND,
    TAMED_COMPANION_ROSTER_LIMIT,
    TAMED_COMPANION_EVOLUTIONS,
    TAMED_COMPANION_SPECIALS,
    BEAST_COMPANION_COMMANDS,
    TAMED_COMPANION_CLASS_ALIASES,
    TAMED_COMPANION_SPECIES,
    _skills,
    has_skill,
    can_dual_wield_item,
    dual_wield_accuracy_modifier,
    cross_block_profile,
    duelist_accuracy_bonus,
    duelist_critical_bonus,
    duelist_damage_multiplier,
    duelist_style_active,
    _is_two_handed_polearm,
    _is_two_handed_staff,
    can_keep_polearm_shield,
    can_keep_staff_shield,
    can_keep_berserker_heavy_offhand,
    _one_handed_polearm_active,
    polearm_damage_multiplier,
    polearm_accuracy_modifier,
    _berserker_heavy_dual_wield_active,
    monkey_grip_damage_multiplier,
    monkey_grip_accuracy_modifier,
)
from .passives import (
    third_eye_intelligence,
    drunken_brawler_damage_bonus,
    drunken_brawler_crit_bonus,
    trigger_drunken_brawler,
    trigger_zephyrstrike,
    trigger_blessed_light,
    power_up_active,
    passive_power_up_unlocked,
    tricksters_gambit_magic_bonus,
    tricksters_gambit_crit_bonus,
    tricksters_gambit_dodge_bonus,
    primal_ascendance_multiplier,
    abyssal_covenant_magic_bonus,
    abyssal_contract_count,
    arsenal_mastery_weapon_multiplier,
    shield_mastery_block_bonus,
    melody_inspiration_bonus,
    pack_bond_multiplier,
    last_stand_attack_multiplier,
    last_stand_defense_bonus,
    last_stand_block_bonus,
    activate_last_stand,
    posturing_parry_bonus,
    retort_counter_multiplier,
    pain_tolerance_bleed_multiplier,
    bandage_healing_multiplier,
    trigger_hemorrhage_thirst,
    retort_parry_bonus,
    retaliate_after_block,
    final_assault_response,
    nature_shield_orbs,
    spend_nature_shield_orb,
)
from .companions import (
    default_tamed_companion,
    _tamed_enemy_class_key,
    _tamed_species_data,
    tamed_companion_species,
    tamed_companion_evolution_for_bond,
    _infer_tamed_special_from_name,
    tamed_special_from_enemy,
    _known_tamed_evolutions,
    tamed_companion_display_name,
    rename_tamed_companion,
    _tamed_entry_from_state,
    tamed_companion_base_snapshot,
    _tamed_roster_key,
    _with_active_tamed_companion,
    normalize_tamed_companion,
    activate_tamed_companion,
    release_tamed_companion,
    tamed_special_description,
    apply_tamed_companion_growth,
    tamed_companion_special_turn,
    tamed_companion_bond,
    has_living_tamed_companion,
    _class_name,
    available_beast_companion_commands,
    _companion_command_state,
    pending_companion_command,
    set_pending_companion_command,
    tamed_auto_action_chance,
    tamed_companion_should_auto_act,
    _favored_enemy_pressure,
    resolve_tamed_companion_command,
)
from .exploration import (
    default_exploration_effects,
    normalize_exploration_effects,
    ensure_exploration_effects,
    sync_exploration_flags,
    apply_exploration_effect,
    tick_exploration_effects,
    favorite_enemy_type,
    favored_enemy_state,
    favored_enemy_rank,
    favored_enemy_practice_bonus,
    favored_enemy_label,
    mark_favored_enemy,
    gain_favored_enemy_practice,
    favored_enemy_bonus,
    consume_favored_enemy_bonus_message,
)
from .rewind import (
    attempt_tame,
    capture_battle_snapshot,
    store_rewind_snapshot,
    restore_battle_snapshot,
    restore_rewind_snapshot,
)
from .summons import (
    heal_all_summons,
)

from .passives import random
from .rewind import deepcopy
